import type { TranslationBundle } from './en';

/** Bengali (বাংলা) */
export const bn: TranslationBundle = {
  common: {
    appName: 'MerchantOne',
    ok: 'ঠিক আছে',
    cancel: 'বাতিল',
    continue: 'এগিয়ে যান',
    back: 'পিছনে',
    next: 'পরবর্তী',
    skip: 'এড়িয়ে যান',
    done: 'সম্পন্ন',
    retry: 'আবার চেষ্টা করুন',
    save: 'সেভ করুন',
    close: 'বন্ধ করুন',
    share: 'শেয়ার করুন',
    download: 'ডাউনলোড',
    search: 'খুঁজুন',
    viewAll: 'সব দেখুন',
    today: 'আজ',
    yesterday: 'গতকাল',
    loading: 'লোড হচ্ছে…',
    yes: 'হ্যাঁ',
    no: 'না',
    optional: 'ঐচ্ছিক',
    verified: 'যাচাই হয়েছে',
    verifying: 'যাচাই হচ্ছে…',
    edit: 'বদলান',
    remove: 'সরান',
    confirm: 'নিশ্চিত করুন',
    comingSoon: 'শীঘ্রই আসছে',
    comingSoonBody: 'এই অংশটি তৈরি হচ্ছে।',
    months: {
      jan: 'জানু',
      feb: 'ফেব্রু',
      mar: 'মার্চ',
      apr: 'এপ্রি',
      may: 'মে',
      jun: 'জুন',
      jul: 'জুলা',
      aug: 'আগ',
      sep: 'সেপ্ট',
      oct: 'অক্টো',
      nov: 'নভে',
      dec: 'ডিসে',
    },
  },

  a11y: {
    back: 'পিছনে যান',
    close: 'বন্ধ করুন',
    notifications: 'বিজ্ঞপ্তি',
    loading: 'বিষয়বস্তু লোড হচ্ছে',
    amount: 'পরিমাণ {{amount}}',
    step: 'ধাপ {{current}} / {{total}}',
  },

  tabs: {
    home: 'হোম',
    collect: 'টাকা নিন',
    transactions: 'লেনদেন',
    settlements: 'সেটলমেন্ট',
    more: 'আরও',
  },

  network: {
    offlineTitle: 'আপনি অফলাইনে আছেন',
    offlineBanner: 'ইন্টারনেট নেই। সেভ করা তথ্য দেখানো হচ্ছে।',
    offlineActionDisabled: 'এর জন্য ইন্টারনেট সংযোগ দরকার।',
    backOnline: 'ইন্টারনেট ফিরে এসেছে',
  },

  errors: {
    title: 'কিছু ভুল হয়েছে',
    network_error: 'সার্ভারে পৌঁছানো যাচ্ছে না। সংযোগ দেখে আবার চেষ্টা করুন।',
    timeout: 'অনেক সময় লাগছে। আবার চেষ্টা করুন।',
    offline: 'আপনি অফলাইনে আছেন। ইন্টারনেটে যুক্ত হয়ে আবার চেষ্টা করুন।',
    unauthorized: 'আপনার সেশন শেষ হয়েছে। আবার লগ ইন করুন।',
    forbidden: 'এটি করার অনুমতি আপনার নেই।',
    not_found: 'আপনি যা খুঁজছিলেন পাওয়া যায়নি।',
    validation_error: 'আপনি যে তথ্য দিয়েছেন তা দেখে নিন।',
    rate_limited: 'অনেক বার চেষ্টা হয়েছে। কিছুক্ষণ পরে চেষ্টা করুন।',
    invalid_otp: 'এই OTP ভুল। দেখে আবার দিন।',
    otp_expired: 'এই OTP-র সময় শেষ। নতুন OTP নিন।',
    invalid_mobile: 'সঠিক ১০ সংখ্যার মোবাইল নম্বর দিন।',
    kyc_incomplete: 'এই সুবিধার জন্য আপনার KYC সম্পূর্ণ করুন।',
    kyc_rejected: 'আপনার KYC অনুমোদিত হয়নি। দেখে আবার জমা দিন।',
    bank_verification_failed: 'এই ব্যাঙ্ক অ্যাকাউন্ট যাচাই করা যায়নি। তথ্য দেখে নিন।',
    pan_verification_failed: 'এই PAN যাচাই করা যায়নি। নম্বর দেখে নিন।',
    already_refunded: 'এই লেনদেনের টাকা আগেই ফেরত দেওয়া হয়েছে।',
    refund_limit_exceeded: 'ফেরতের পরিমাণ উপলব্ধ পরিমাণের চেয়ে বেশি।',
    payment_expired: 'এই পেমেন্ট অনুরোধের সময় শেষ। নতুন তৈরি করুন।',
    server_error: 'আমাদের সার্ভারে সমস্যা। কিছুক্ষণ পরে চেষ্টা করুন।',
    unknown: 'কিছু ভুল হয়েছে। আবার চেষ্টা করুন।',
  },

  auth: {
    splash: {
      tagline: 'পেমেন্ট এখন সহজ',
    },
    login: {
      title: 'স্বাগতম',
      subtitle: 'আপনার ব্যবসা পরিচালনা করতে মোবাইল নম্বর দিয়ে লগ ইন করুন',
      mobileLabel: 'মোবাইল নম্বর',
      mobilePlaceholder: '১০ সংখ্যার মোবাইল নম্বর',
      mobileRequired: 'আপনার মোবাইল নম্বর দিন',
      mobileInvalid: 'সঠিক ১০ সংখ্যার মোবাইল নম্বর দিন',
      consent: 'আমি পরিষেবার শর্তাবলী এবং গোপনীয়তা নীতিতে সম্মত',
      consentRequired: 'এগিয়ে যেতে শর্তাবলী মানুন',
      getOtp: 'OTP নিন',
      secureNote: 'আপনার নম্বর যাচাই করতে ৬ সংখ্যার কোড পাঠাব।',
    },
    otp: {
      title: 'আপনার নম্বর যাচাই করুন',
      subtitle: '{{mobile}} এ পাঠানো ৬ সংখ্যার কোড দিন',
      otpRequired: '৬ সংখ্যার কোড দিন',
      otpInvalid: 'কোড ৬ সংখ্যার হতে হবে',
      verify: 'যাচাই করুন',
      resend: 'কোড আবার পাঠান',
      resendIn: '{{seconds}} সেকেন্ডে আবার পাঠান',
      changeNumber: 'নম্বর বদলান',
      autoReadHint: 'অনুমতি থাকলে কোড আমরা নিজেই পড়ে নেব।',
      hintDev: 'ডেমো মোড: {{otp}} ব্যবহার করুন',
    },
  },

  kyc: {
    title: 'ব্যবসা যাচাই',
    stepOf: 'ধাপ {{current}} / {{total}}',
    saveAndExit: 'সেভ করে বেরিয়ে যান',
    resumeTitle: 'যাচাই চালিয়ে যান',
    resumeBody: 'আপনি ধাপ {{step}} এ থেমেছিলেন। সেখান থেকেই এগিয়ে যান।',
    progress: {
      business: 'ব্যবসা',
      identity: 'পরিচয়',
      bank: 'ব্যাঙ্ক',
      aadhaar: 'আধার',
    },
    business: {
      title: 'আপনার ব্যবসা সম্পর্কে বলুন',
      subtitle: 'গ্রাহকরা যে QR স্ক্যান করবেন তাতে এটি দেখা যাবে।',
      name: 'ব্যবসার নাম',
      namePlaceholder: 'যেমন শর্মা জেনারেল স্টোর',
      nameRequired: 'আপনার ব্যবসার নাম দিন',
      nameTooShort: 'নাম কমপক্ষে ৩ অক্ষরের হতে হবে',
      category: 'ব্যবসার ধরন',
      categoryPlaceholder: 'একটি ধরন বাছুন',
      categoryRequired: 'আপনার ব্যবসার ধরন বাছুন',
      categorySheetTitle: 'ব্যবসার ধরন বাছুন',
      addressLine1: 'দোকান / বাড়ির ঠিকানা',
      addressPlaceholder: 'দোকান নম্বর, রাস্তা, এলাকা',
      addressRequired: 'আপনার ব্যবসার ঠিকানা দিন',
      pincode: 'পিন কোড',
      pincodePlaceholder: '৬ সংখ্যার পিন কোড',
      pincodeRequired: 'আপনার পিন কোড দিন',
      pincodeInvalid: 'সঠিক ৬ সংখ্যার পিন কোড দিন',
      city: 'শহর',
      cityRequired: 'আপনার শহর দিন',
      state: 'রাজ্য',
      stateRequired: 'আপনার রাজ্য দিন',
      pincodeLookup: 'আপনার এলাকা খোঁজা হচ্ছে…',
    },
    identity: {
      title: 'পরিচয়ের তথ্য',
      subtitle: 'পেমেন্ট নিতে RBI বাধ্যতামূলক করেছে।',
      pan: 'PAN নম্বর',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'আপনার PAN নম্বর দিন',
      panInvalid: 'সঠিক PAN দিন (যেমন ABCDE1234F)',
      panHelp: 'আপনার PAN কার্ডে যেমন ছাপা আছে।',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'সঠিক ১৫ অক্ষরের GSTIN দিন',
      gstinHelp: 'GST বিল চাইলে এটি যোগ করুন।',
    },
    bank: {
      title: 'আপনার টাকা কোথায় পাঠাব?',
      subtitle: 'আপনার আদায় এখানে জমা হবে, সাধারণত পরের দিন।',
      accountNumber: 'অ্যাকাউন্ট নম্বর',
      accountNumberPlaceholder: 'ব্যাঙ্ক অ্যাকাউন্ট নম্বর',
      accountNumberRequired: 'আপনার অ্যাকাউন্ট নম্বর দিন',
      accountNumberInvalid: 'অ্যাকাউন্ট নম্বর ৯ থেকে ১৮ সংখ্যার হতে হবে',
      confirmAccountNumber: 'অ্যাকাউন্ট নম্বর আবার দিন',
      accountMismatch: 'অ্যাকাউন্ট নম্বর মিলছে না',
      ifsc: 'IFSC কোড',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'IFSC কোড দিন',
      ifscInvalid: 'সঠিক IFSC দিন (যেমন HDFC0001234)',
      holderName: 'অ্যাকাউন্টধারীর নাম',
      holderNamePlaceholder: 'ব্যাঙ্কের নথি অনুযায়ী নাম',
      holderNameRequired: 'অ্যাকাউন্টধারীর নাম দিন',
      verifyCta: 'অ্যাকাউন্ট যাচাই করুন',
      verifying: 'আপনার অ্যাকাউন্ট যাচাই হচ্ছে…',
      verifyingBody: 'এই অ্যাকাউন্ট আপনারই কিনা নিশ্চিত করতে আমরা ₹১ পাঠাচ্ছি।',
      verifiedTitle: 'অ্যাকাউন্ট যাচাই হয়েছে',
      verifiedNameAtBank: 'ব্যাঙ্কে নাম: {{name}}',
      unlockNote: 'এই ধাপের পরে সীমা সহ পেমেন্ট নেওয়া শুরু করতে পারেন, যাচাই শেষ হওয়া পর্যন্ত।',
    },
    aadhaar: {
      title: 'আধার যাচাই',
      subtitle: 'সব সুবিধা খুলতে শেষ ধাপ।',
      numberLabel: 'আধার নম্বর',
      numberPlaceholder: '১২ সংখ্যার আধার নম্বর',
      numberRequired: 'আপনার আধার নম্বর দিন',
      numberInvalid: 'আধার নম্বর ১২ সংখ্যার হতে হবে',
      consent: 'আমি আধার eKYC দিয়ে আমার পরিচয় যাচাইয়ে সম্মতি দিচ্ছি। আমি বুঝেছি আমার আধার তথ্য শুধু এই যাচাইয়ের জন্যই ব্যবহার হবে।',
      consentRequired: 'এগিয়ে যেতে আপনার সম্মতি দরকার',
      sendOtp: 'আধার OTP পাঠান',
      otpLabel: 'আধার OTP',
      otpSentTo: 'আধারের সঙ্গে যুক্ত মোবাইলে পাঠানো কোড দিন।',
      otpRequired: '৬ সংখ্যার আধার OTP দিন',
      verifyCta: 'আধার যাচাই করুন',
      verifiedTitle: 'আধার যাচাই হয়েছে',
      skipForNow: 'পরে করুন',
      privacyNote: 'আপনার পুরো আধার নম্বর আমরা কখনও সংরক্ষণ করি না।',
    },
    done: {
      title: 'সব তৈরি!',
      subtitle: 'আপনার তথ্য জমা হয়েছে। এখনই পেমেন্ট নেওয়া শুরু করতে পারেন।',
      pendingTitle: 'যাচাই চলছে',
      pendingSubtitle: 'আমরা আপনার তথ্য দেখছি। সাধারণত কয়েক ঘণ্টা লাগে।',
      generateQr: 'আমার QR তৈরি করুন',
      goHome: 'ড্যাশবোর্ডে যান',
      vpaLabel: 'আপনার UPI ID',
      limitsNote: 'যাচাই শেষ হওয়া পর্যন্ত দিনে {{limit}} পর্যন্ত নিতে পারবেন।',
    },
    status: {
      not_started: 'KYC বাকি',
      in_progress: 'KYC অসম্পূর্ণ',
      pending_review: 'পরীক্ষাধীন',
      approved: 'যাচাই হয়েছে',
      rejected: 'ব্যবস্থা দরকার',
    },
    rejected: {
      title: 'আমাদের আবার দেখতে হবে',
      reasonLabel: 'কারণ',
      retryCta: 'তথ্য আপডেট করুন',
    },
    submitCta: 'যাচাইয়ের জন্য জমা দিন',
    mcc: {
      grocery: 'মুদি / জেনারেল স্টোর',
      restaurant: 'রেস্টুরেন্ট / ক্যাফে',
      apparel: 'পোশাক',
      electronics: 'ইলেকট্রনিকস ও মোবাইল',
      pharmacy: 'ওষুধের দোকান / মেডিকেল',
      salon: 'সালোঁ ও প্রসাধন',
      hardware: 'হার্ডওয়্যার ও নির্মাণ সামগ্রী',
      services: 'পেশাদার পরিষেবা',
      education: 'শিক্ষা ও কোচিং',
      transport: 'পরিবহন ও ভ্রমণ',
      online: 'অনলাইন / D2C বিক্রেতা',
      other: 'অন্যান্য',
    },
  },

  home: {
    greeting: 'নমস্কার',
    summary: {
      title: 'আজের আদায়',
      collected: 'আজ পেয়েছেন',
      txnCount: '{{count}} পেমেন্ট',
      txnCount_plural: '{{count}} পেমেন্ট',
      pendingSettlement: 'সেটলমেন্ট বাকি',
      settlementHint: 'আপনার ব্যাঙ্ক অ্যাকাউন্টে জমা হবে',
    },
    collectCta: 'টাকা নিন',
    quickActions: {
      title: 'দ্রুত কাজ',
      myQr: 'আমার QR',
      paymentLink: 'পেমেন্ট লিঙ্ক',
      reports: 'রিপোর্ট',
      refund: 'ফেরত',
    },
    recent: {
      title: 'সাম্প্রতিক পেমেন্ট',
      emptyTitle: 'এখনও কোনও পেমেন্ট নেই',
      emptyBody: 'প্রথম পেমেন্ট পেতে গ্রাহককে আপনার QR দেখান।',
      emptyCta: 'আমার QR দেখান',
    },
    kycNudge: {
      title: 'যাচাই সম্পূর্ণ করুন',
      body: 'সীমা তুলতে আপনার তথ্য সম্পূর্ণ করুন।',
      cta: 'এগিয়ে যান',
    },
    error: {
      title: 'ড্যাশবোর্ড লোড করা যায়নি',
      body: 'সংযোগ দেখে আবার চেষ্টা করুন।',
    },
  },

  notifications: {
    title: 'বিজ্ঞপ্তি',
    emptyTitle: 'কোনও বিজ্ঞপ্তি নেই',
    emptyBody: 'পেমেন্ট ও সেটলমেন্টের খবর এখানে দেখা যাবে।',
  },

  transactions: {
    title: 'লেনদেন',
    status: {
      success: 'পেয়েছেন',
      pending: 'বাকি',
      failed: 'ব্যর্থ',
      refunded: 'ফেরত দেওয়া',
      partially_refunded: 'আংশিক ফেরত',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI অ্যাপ',
      payment_link: 'পেমেন্ট লিঙ্ক',
      card: 'কার্ড',
      netbanking: 'নেট ব্যাঙ্কিং',
      wallet: 'ওয়ালেট',
    },
    filters: {
      all: 'সব',
      success: 'পেয়েছেন',
      pending: 'বাকি',
      failed: 'ব্যর্থ',
      refunded: 'ফেরত দেওয়া',
    },
    searchPlaceholder: 'পরিমাণ, UTR বা প্রদানকারী খুঁজুন',
    emptyTitle: 'কোনও লেনদেন নেই',
    emptyBody: 'আপনি যে পেমেন্ট পাবেন তা এখানে দেখা যাবে।',
    emptyFilteredTitle: 'কিছু মেলেনি',
    emptyFilteredBody: 'অন্য ফিল্টার বা তারিখ বেছে দেখুন।',
    clearFilters: 'ফিল্টার সরান',
    resultCount: '{{count}} লেনদেন',
    resultCount_plural: '{{count}} লেনদেন',
    loadingMore: 'আরও লোড হচ্ছে…',
    endOfList: 'এটুকুই',
    detail: {
      title: 'পেমেন্টের বিবরণ',
      amountLabel: 'পরিমাণ',
      statusLabel: 'অবস্থা',
      modeLabel: 'কীভাবে পেয়েছেন',
      txnIdLabel: 'লেনদেন ID',
      utrLabel: 'UTR / RRN',
      timeLabel: 'তারিখ ও সময়',
      payerLabel: 'যিনি দিয়েছেন',
      noteLabel: 'নোট',
      breakdownTitle: 'হিসাব',
      grossLabel: 'প্রাপ্ত পরিমাণ',
      feeLabel: 'ফি (MDR)',
      netLabel: 'আপনি পাবেন',
      noFee: 'কোনও ফি নেই',
      settlementTitle: 'সেটলমেন্ট',
      settlementPending: 'আপনার ব্যাঙ্ক অ্যাকাউন্টে পাঠানো হবে',
      settlementDone: 'আপনার ব্যাঙ্ক অ্যাকাউন্টে পাঠানো হয়েছে',
      viewSettlement: 'সেটলমেন্ট দেখুন',
      refundedLabel: 'এখন পর্যন্ত ফেরত',
      actions: 'কাজ',
      refund: 'ফেরত',
      shareReceipt: 'রসিদ শেয়ার করুন',
      raiseDispute: 'অভিযোগ জানান',
      reportIssue: 'সমস্যা জানান',
      notRefundable: 'এই পেমেন্ট ফেরত দেওয়া যাবে না',
      receiptMessage: '{{time}} এ {{amount}} পেয়েছেন। লেনদেন ID: {{id}}.',
    },
  },

  refund: {
    title: 'ফেরত দিন',
    originalLabel: 'মূল পেমেন্ট',
    refundableLabel: 'ফেরতের জন্য উপলব্ধ',
    alreadyRefunded: '{{amount}} আগেই ফেরত দেওয়া হয়েছে',
    typeFull: 'সম্পূর্ণ ফেরত',
    typePartial: 'আংশিক ফেরত',
    fullBody: 'পুরো পরিমাণ ফেরত দিন',
    partialBody: 'পরিমাণের কিছু অংশ ফেরত দিন',
    amountLabel: 'ফেরতের পরিমাণ',
    reasonLabel: 'কারণ',
    reasonPlaceholder: 'কেন ফেরত? (ঐচ্ছিক)',
    exceedsRefundable: '{{max}} এর বেশি ফেরত দেওয়া যাবে না',
    tooLow: '{{min}} এর বেশি পরিমাণ দিন',
    confirmCta: '{{amount}} ফেরত দিন',
    reauthReason: '{{amount}} ফেরত নিশ্চিত করুন',
    processingTitle: 'ফেরত চলছে…',
    processingBody: 'অ্যাপটি খোলা রাখুন।',
    successTitle: 'ফেরত শুরু হয়েছে',
    successBody: '{{amount}} গ্রাহকের কাছে ফেরত পাঠানো হচ্ছে। সাধারণত ৩-৫ কর্মদিবস লাগে।',
    successDone: 'সম্পন্ন',
    offlineTitle: 'ইন্টারনেট নেই',
    offlineBody: 'ফেরতের জন্য ইন্টারনেট সংযোগ দরকার।',
    notEligibleTitle: 'ফেরত দেওয়া যাবে না',
    notEligibleBody: 'শুধু সফল পেমেন্ট ফেরত দেওয়া যায়।',
  },

  appLock: {
    title: 'আপনিই কি না নিশ্চিত করুন',
    biometricPrompt: 'নিশ্চিত করতে আঙুলের ছাপ বা মুখ ব্যবহার করুন',
    biometricFailed: 'যাচাই করা গেল না। বদলে PIN দিন।',
    usePin: 'PIN ব্যবহার করুন',
    pinIncorrect: 'ভুল PIN। {{count}} বার বাকি।',
    lockedOut: 'অনেকবার ভুল হয়েছে। অ্যাপ বন্ধ করে আবার খুলুন।',
    setupTitle: 'অ্যাপ PIN তৈরি করুন',
    setupBody: 'ফেরতের মতো গুরুত্বপূর্ণ কাজ অনুমোদনের জন্য {{min}} সংখ্যার PIN বাছুন।',
    confirmTitle: 'PIN আবার দিন',
    pinMismatch: 'PIN মেলেনি। আবার চেষ্টা করুন।',
    pinTooShort: 'PIN কমপক্ষে {{min}} সংখ্যার হতে হবে',
  },

  dateRange: {
    label: 'তারিখের পরিসর',
    all: 'সব সময়',
    today: 'আজ',
    yesterday: 'গতকাল',
    last7: 'গত ৭ দিন',
    last30: 'গত ৩০ দিন',
    thisMonth: 'এই মাস',
    custom: 'নিজের পরিসর',
    from: 'থেকে',
    to: 'পর্যন্ত',
  },

  settlements: {
    title: 'সেটলমেন্ট',
    status: {
      pending: 'বাকি',
      processing: 'চলছে',
      settled: 'জমা হয়েছে',
      failed: 'ব্যর্থ',
    },
    tabs: {
      pending: 'বাকি',
      settled: 'জমা হয়েছে',
    },
    batchLabel: '{{count}} পেমেন্টের ব্যাচ',
    batchLabel_plural: '{{count}} পেমেন্টের ব্যাচ',
    utrLabel: 'UTR',
    expectedLabel: 'আপনার ব্যাঙ্ক অ্যাকাউন্টে আসবে',
    creditedLabel: 'আপনার ব্যাঙ্ক অ্যাকাউন্টে জমা',
    emptyPendingTitle: 'কিছু বাকি নেই',
    emptyPendingBody: 'আজ পাওয়া পেমেন্ট কাল আপনার ব্যাঙ্ক অ্যাকাউন্টে পাঠানো হবে।',
    emptySettledTitle: 'এখনও সেটলমেন্ট নেই',
    emptySettledBody: 'টাকা ব্যাঙ্ক অ্যাকাউন্টে পৌঁছলে UTR সহ এখানে দেখা যাবে।',
    errorTitle: 'সেটলমেন্ট লোড করা যায়নি',
    t1Note: 'পরের কর্মদিবসে টাকা আপনার ব্যাঙ্ক অ্যাকাউন্টে পৌঁছয়।',
    detail: {
      title: 'সেটলমেন্টের বিবরণ',
      breakdownTitle: 'হিসাব',
      grossLabel: 'মোট পেয়েছেন',
      feeLabel: 'ফি',
      netLabel: 'ব্যাঙ্কে জমা',
      bankTitle: 'ব্যাঙ্ক অ্যাকাউন্ট',
      accountLabel: 'অ্যাকাউন্ট',
      ifscLabel: 'IFSC',
      utrLabel: 'UTR / রেফারেন্স',
      createdLabel: 'ব্যাচ তৈরি হয়েছে',
      settledLabel: 'জমা হয়েছে',
      txnTitle: 'এই ব্যাচের পেমেন্ট',
      txnCount: '{{count}} পেমেন্ট',
      txnCount_plural: '{{count}} পেমেন্ট',
      reconcileNote: 'নিচের সব পেমেন্ট মিলে মোট পরিমাণ হয়।',
      noTxnTitle: 'পেমেন্টের তালিকা নেই',
      noTxnBody: 'এই ব্যাচের আলাদা পেমেন্ট পাওয়া যাচ্ছে না।',
    },
    statement: {
      download: 'স্টেটমেন্ট ডাউনলোড করুন',
      preparing: 'স্টেটমেন্ট তৈরি হচ্ছে…',
      failed: 'স্টেটমেন্ট তৈরি করা যায়নি। আবার চেষ্টা করুন।',
      fileName: 'সেটলমেন্ট স্টেটমেন্ট',
      colDate: 'তারিখ',
      colTime: 'সময়',
      colTxnId: 'লেনদেন ID',
      colUtr: 'UTR',
      colMode: 'মাধ্যম',
      colStatus: 'অবস্থা',
      colGross: 'পরিমাণ (INR)',
      colFee: 'ফি (INR)',
      colNet: 'নিট (INR)',
      totalsLabel: 'মোট',
      formatNote: 'CSV ফাইল হিসেবে সেভ হয়, যা Excel ও Google Sheets-এ খোলে।',
    },
    instant: {
      cta: 'এখনই সেটল করুন',
      sheetTitle: 'তৎক্ষণাৎ সেটল করুন',
      sheetBody: 'কাল পর্যন্ত অপেক্ষা না করে এই টাকা কয়েক মিনিটে ব্যাঙ্ক অ্যাকাউন্টে পান।',
      netLabel: 'সেটলমেন্টের পরিমাণ',
      feeLabel: 'তৎক্ষণাৎ সেটলমেন্ট ফি ({{percent}}%)',
      gstLabel: 'ফির উপর GST',
      payoutLabel: 'আপনি পাবেন',
      confirmCta: '{{amount}} এখনই সেটল করুন',
      processing: 'সেটল হচ্ছে…',
      successTitle: 'টাকা পাঠানো হচ্ছে',
      successBody: '{{amount}} আপনার ব্যাঙ্ক অ্যাকাউন্টে জমা হচ্ছে। সাধারণত কয়েক মিনিটে পৌঁছয়।',
      ineligible: {
        already_settled: 'এই ব্যাচ আগেই সেটল হয়েছে।',
        below_minimum: 'তৎক্ষণাৎ সেটলমেন্টের জন্য কমপক্ষে {{min}} দরকার।',
        failed_batch: 'এই ব্যাচ ব্যর্থ হয়েছে, তৎক্ষণাৎ সেটল করা যাবে না।',
      },
      offlineBody: 'তৎক্ষণাৎ সেটলমেন্টের জন্য ইন্টারনেট সংযোগ দরকার।',
    },
  },

  collect: {
    title: 'টাকা নিন',
    subtitle: 'আপনি কীভাবে টাকা নিতে চান?',
    modes: {
      staticQr: 'আমার QR কোড',
      staticQrBody: 'যে কোনও পরিমাণের জন্য একটাই কোড। দেখান বা ছাপান।',
      dynamicQr: 'পরিমাণ দিন',
      dynamicQrBody: 'নির্দিষ্ট পরিমাণের জন্য QR তৈরি করুন।',
      paymentLink: 'পেমেন্ট লিঙ্ক',
      paymentLinkBody: 'WhatsApp বা SMS-এ লিঙ্ক পাঠান।',
    },
    staticQr: {
      title: 'আমার QR কোড',
      instruction: 'গ্রাহককে স্ক্যান করে যে কোনও পরিমাণ দিতে বলুন।',
      vpaLabel: 'UPI ID',
      noQrTitle: 'QR এখনও তৈরি নয়',
      noQrBody: 'QR কোড পেতে ব্যাঙ্ক যাচাই সম্পূর্ণ করুন।',
      noQrCta: 'যাচাই সম্পূর্ণ করুন',
      offlineUsable: 'আপনার QR ইন্টারনেট ছাড়াও কাজ করে।',
    },
    amount: {
      title: 'পরিমাণ দিন',
      generateQr: 'QR তৈরি করুন',
      createLink: 'লিঙ্ক তৈরি করুন',
      noteLabel: 'নোট',
      notePlaceholder: 'কী জন্য? (ঐচ্ছিক)',
      tooLow: '{{min}} এর বেশি পরিমাণ দিন',
      limitExceeded: 'যাচাই শেষ হওয়া পর্যন্ত দৈনিক সীমা {{limit}}',
      upiCap: 'একটি UPI পেমেন্টে সর্বোচ্চ {{max}}',
    },
    dynamicQr: {
      title: 'টাকা দিতে স্ক্যান করুন',
      waiting: 'পেমেন্টের অপেক্ষায়…',
      waitingBody: 'গ্রাহককে এই কোড স্ক্যান করতে বলুন।',
      expiresIn: '{{time}} এ শেষ হবে',
      expiredTitle: 'QR-এর সময় শেষ',
      expiredBody: 'এই কোড আর বৈধ নয়। নতুন তৈরি করুন।',
      newQr: 'নতুন QR তৈরি করুন',
      cancel: 'বাতিল',
      checkingSlowly: 'এখনও দেখা হচ্ছে। আপনার সংযোগ ধীর মনে হচ্ছে।',
      failedTitle: 'পেমেন্ট ব্যর্থ',
      failedBody: 'গ্রাহকের পেমেন্ট হয়নি। আবার চেষ্টা করতে বলুন।',
      offlineTitle: 'ইন্টারনেট নেই',
      offlineBody: 'নির্দিষ্ট পরিমাণের QR-এর জন্য ইন্টারনেট দরকার। বদলে আপনার QR কোড ব্যবহার করুন।',
      useStaticQr: 'আমার QR কোড ব্যবহার করুন',
    },
    link: {
      title: 'পেমেন্ট লিঙ্ক',
      createdTitle: 'লিঙ্ক তৈরি',
      createdBody: 'এটি গ্রাহককে পাঠান। ২৪ ঘণ্টায় শেষ হবে।',
      copy: 'লিঙ্ক কপি করুন',
      copied: 'লিঙ্ক কপি হয়েছে',
      shareVia: 'লিঙ্ক শেয়ার করুন',
      newLink: 'আরেকটি তৈরি করুন',
      shareMessage: 'এই লিঙ্ক দিয়ে {{amount}} দিন: {{url}}',
    },
    success: {
      title: 'পেমেন্ট পেয়েছেন!',
      amountLabel: 'প্রাপ্ত পরিমাণ',
      txnIdLabel: 'লেনদেন ID',
      timeLabel: 'সময়',
      payerLabel: 'যিনি দিয়েছেন',
      utrLabel: 'UPI রেফারেন্স',
      shareReceipt: 'রসিদ শেয়ার করুন',
      newPayment: 'নতুন পেমেন্ট',
      done: 'সম্পন্ন',
      receiptMessage: 'পেমেন্ট পেয়েছেন: {{time}} এ {{amount}}. লেনদেন ID: {{id}}.',
    },
    audio: {
      received: '{{amount}} টাকা পেয়েছেন',
      mutedHint: 'অডিও নিশ্চিতকরণ বন্ধ। সেটিংসে চালু করুন।',
    },
  },
};

export default bn;
