/**
 * English resource bundle — the canonical source of truth.
 *
 * Every other language must satisfy the `TranslationBundle` type derived from
 * this file, so a missing key is a compile error rather than a runtime fallback.
 * Per App-PRD Section 5: "All strings via i18n keys — no hardcoded text."
 *
 * Keys are added as screens are built; this bundle covers Section 16 steps 1-4
 * (scaffold, auth, KYC, home) plus the navigation shell.
 */
export const en = {
  common: {
    appName: 'MerchantOne',
    ok: 'OK',
    cancel: 'Cancel',
    continue: 'Continue',
    back: 'Back',
    next: 'Next',
    skip: 'Skip',
    done: 'Done',
    retry: 'Try again',
    save: 'Save',
    close: 'Close',
    share: 'Share',
    download: 'Download',
    search: 'Search',
    viewAll: 'View all',
    today: 'Today',
    yesterday: 'Yesterday',
    loading: 'Loading…',
    yes: 'Yes',
    no: 'No',
    optional: 'Optional',
    verified: 'Verified',
    verifying: 'Verifying…',
    edit: 'Edit',
    remove: 'Remove',
    confirm: 'Confirm',
    comingSoon: 'Coming soon',
    comingSoonBody: 'This section is being built.',
    months: {
      jan: 'Jan',
      feb: 'Feb',
      mar: 'Mar',
      apr: 'Apr',
      may: 'May',
      jun: 'Jun',
      jul: 'Jul',
      aug: 'Aug',
      sep: 'Sep',
      oct: 'Oct',
      nov: 'Nov',
      dec: 'Dec',
    },
  },

  a11y: {
    back: 'Go back',
    close: 'Close',
    notifications: 'Notifications',
    loading: 'Loading content',
    amount: 'Amount {{amount}}',
    step: 'Step {{current}} of {{total}}',
  },

  tabs: {
    home: 'Home',
    collect: 'Collect',
    transactions: 'Transactions',
    settlements: 'Settlements',
    more: 'More',
  },

  network: {
    offlineTitle: 'You are offline',
    offlineBanner: 'No internet connection. Showing saved data.',
    offlineActionDisabled: 'This needs an internet connection.',
    backOnline: 'Back online',
  },

  errors: {
    title: 'Something went wrong',
    network_error: 'Cannot reach our servers. Check your connection and try again.',
    timeout: 'This is taking too long. Please try again.',
    offline: 'You are offline. Connect to the internet and try again.',
    unauthorized: 'Your session has expired. Please log in again.',
    forbidden: 'You do not have permission to do this.',
    not_found: 'We could not find what you were looking for.',
    validation_error: 'Please check the details you entered.',
    rate_limited: 'Too many attempts. Please wait a moment and try again.',
    invalid_otp: 'That OTP is incorrect. Please check and try again.',
    otp_expired: 'This OTP has expired. Request a new one.',
    invalid_mobile: 'Enter a valid 10-digit mobile number.',
    kyc_incomplete: 'Complete your KYC to use this feature.',
    kyc_rejected: 'Your KYC was not approved. Please review and resubmit.',
    bank_verification_failed: 'We could not verify this bank account. Check the details and try again.',
    pan_verification_failed: 'We could not verify this PAN. Check the number and try again.',
    already_refunded: 'This transaction has already been refunded.',
    refund_limit_exceeded: 'The refund amount is more than the available balance.',
    payment_expired: 'This payment request has expired. Create a new one.',
    server_error: 'Our servers are having trouble. Please try again shortly.',
    unknown: 'Something went wrong. Please try again.',
  },

  auth: {
    splash: {
      tagline: 'Payments made simple',
    },
    login: {
      title: 'Welcome',
      subtitle: 'Log in with your mobile number to manage your business',
      mobileLabel: 'Mobile number',
      mobilePlaceholder: '10-digit mobile number',
      mobileRequired: 'Enter your mobile number',
      mobileInvalid: 'Enter a valid 10-digit mobile number',
      consent: 'I agree to the Terms of Service and Privacy Policy',
      consentRequired: 'Please accept the Terms to continue',
      getOtp: 'Get OTP',
      secureNote: 'We will send a 6-digit code to verify your number.',
    },
    otp: {
      title: 'Verify your number',
      subtitle: 'Enter the 6-digit code sent to {{mobile}}',
      otpRequired: 'Enter the 6-digit code',
      otpInvalid: 'The code must be 6 digits',
      verify: 'Verify',
      resend: 'Resend code',
      resendIn: 'Resend code in {{seconds}}s',
      changeNumber: 'Change number',
      autoReadHint: 'We will read the code automatically if permitted.',
      hintDev: 'Demo mode: use {{otp}}',
    },
  },

  kyc: {
    title: 'Business verification',
    stepOf: 'Step {{current}} of {{total}}',
    saveAndExit: 'Save & exit',
    resumeTitle: 'Resume verification',
    resumeBody: 'You left off at step {{step}}. Pick up where you stopped.',
    progress: {
      business: 'Business',
      identity: 'Identity',
      bank: 'Bank',
      aadhaar: 'Aadhaar',
    },
    business: {
      title: 'Tell us about your business',
      subtitle: 'This appears on the QR your customers scan.',
      name: 'Business name',
      namePlaceholder: 'e.g. Sharma General Store',
      nameRequired: 'Enter your business name',
      nameTooShort: 'Business name must be at least 3 characters',
      category: 'Business category',
      categoryPlaceholder: 'Select a category',
      categoryRequired: 'Select your business category',
      categorySheetTitle: 'Select business category',
      addressLine1: 'Shop / building address',
      addressPlaceholder: 'Shop number, street, area',
      addressRequired: 'Enter your business address',
      pincode: 'PIN code',
      pincodePlaceholder: '6-digit PIN code',
      pincodeRequired: 'Enter your PIN code',
      pincodeInvalid: 'Enter a valid 6-digit PIN code',
      city: 'City',
      cityRequired: 'Enter your city',
      state: 'State',
      stateRequired: 'Enter your state',
      pincodeLookup: 'Finding your area…',
    },
    identity: {
      title: 'Identity details',
      subtitle: 'Required by RBI to accept payments.',
      pan: 'PAN number',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'Enter your PAN number',
      panInvalid: 'Enter a valid PAN (e.g. ABCDE1234F)',
      panHelp: 'As printed on your PAN card.',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'Enter a valid 15-character GSTIN',
      gstinHelp: 'Add this if you want GST-compliant invoices.',
    },
    bank: {
      title: 'Where should we settle your money?',
      subtitle: 'Your collections are credited here, by default the next day.',
      accountNumber: 'Account number',
      accountNumberPlaceholder: 'Bank account number',
      accountNumberRequired: 'Enter your account number',
      accountNumberInvalid: 'Account number must be 9 to 18 digits',
      confirmAccountNumber: 'Re-enter account number',
      accountMismatch: 'Account numbers do not match',
      ifsc: 'IFSC code',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'Enter the IFSC code',
      ifscInvalid: 'Enter a valid IFSC (e.g. HDFC0001234)',
      holderName: 'Account holder name',
      holderNamePlaceholder: 'Name as per bank records',
      holderNameRequired: 'Enter the account holder name',
      verifyCta: 'Verify account',
      verifying: 'Verifying your account…',
      verifyingBody: 'We are sending ₹1 to confirm this account belongs to you.',
      verifiedTitle: 'Account verified',
      verifiedNameAtBank: 'Name at bank: {{name}}',
      unlockNote: 'After this step you can start accepting payments, with limits, while we finish checks.',
    },
    aadhaar: {
      title: 'Aadhaar verification',
      subtitle: 'The last step to unlock all features.',
      numberLabel: 'Aadhaar number',
      numberPlaceholder: '12-digit Aadhaar number',
      numberRequired: 'Enter your Aadhaar number',
      numberInvalid: 'Aadhaar number must be 12 digits',
      consent: 'I consent to verify my identity using Aadhaar eKYC. I understand my Aadhaar details will be used only for this verification.',
      consentRequired: 'Your consent is required to continue',
      sendOtp: 'Send Aadhaar OTP',
      otpLabel: 'Aadhaar OTP',
      otpSentTo: 'Enter the code sent to the mobile linked with your Aadhaar.',
      otpRequired: 'Enter the 6-digit Aadhaar OTP',
      verifyCta: 'Verify Aadhaar',
      verifiedTitle: 'Aadhaar verified',
      skipForNow: 'Do this later',
      privacyNote: 'We never store your full Aadhaar number.',
    },
    done: {
      title: 'You are all set!',
      subtitle: 'Your details are submitted. You can start accepting payments right away.',
      pendingTitle: 'Verification in progress',
      pendingSubtitle: 'We are reviewing your details. This usually takes a few hours.',
      generateQr: 'Generate my QR',
      goHome: 'Go to dashboard',
      vpaLabel: 'Your UPI ID',
      limitsNote: 'Until verification completes, you can collect up to {{limit}} per day.',
    },
    status: {
      not_started: 'KYC pending',
      in_progress: 'KYC incomplete',
      pending_review: 'Under review',
      approved: 'Verified',
      rejected: 'Action needed',
    },
    rejected: {
      title: 'We need another look',
      reasonLabel: 'Reason',
      retryCta: 'Update details',
    },
    submitCta: 'Submit for verification',
    mcc: {
      grocery: 'Grocery / Kirana store',
      restaurant: 'Restaurant / Café',
      apparel: 'Clothing & apparel',
      electronics: 'Electronics & mobiles',
      pharmacy: 'Pharmacy / Medical',
      salon: 'Salon & beauty',
      hardware: 'Hardware & building supplies',
      services: 'Professional services',
      education: 'Education & coaching',
      transport: 'Transport & travel',
      online: 'Online / D2C seller',
      other: 'Other',
    },
  },

  home: {
    greeting: 'Namaste',
    summary: {
      title: "Today's collections",
      collected: 'Collected today',
      txnCount: '{{count}} payment',
      txnCount_plural: '{{count}} payments',
      pendingSettlement: 'Pending settlement',
      settlementHint: 'Credited to your bank account',
    },
    collectCta: 'Collect payment',
    quickActions: {
      title: 'Quick actions',
      myQr: 'My QR',
      paymentLink: 'Payment link',
      reports: 'Reports',
      refund: 'Refund',
    },
    recent: {
      title: 'Recent payments',
      emptyTitle: 'No payments yet',
      emptyBody: 'Show your QR to a customer to receive your first payment.',
      emptyCta: 'Show my QR',
    },
    kycNudge: {
      title: 'Finish verification',
      body: 'Complete your details to remove collection limits.',
      cta: 'Continue',
    },
    error: {
      title: 'Could not load your dashboard',
      body: 'Check your connection and try again.',
    },
  },

  notifications: {
    title: 'Notifications',
    emptyTitle: 'No notifications',
    emptyBody: 'Payment and settlement updates will appear here.',
  },

  transactions: {
    title: 'Transactions',
    status: {
      success: 'Received',
      pending: 'Pending',
      failed: 'Failed',
      refunded: 'Refunded',
      partially_refunded: 'Part refunded',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI app',
      payment_link: 'Payment link',
      card: 'Card',
      netbanking: 'Net banking',
      wallet: 'Wallet',
    },
    filters: {
      all: 'All',
      success: 'Received',
      pending: 'Pending',
      failed: 'Failed',
      refunded: 'Refunded',
    },
    searchPlaceholder: 'Search amount, UTR or payer',
    emptyTitle: 'No transactions',
    emptyBody: 'Payments you receive will appear here.',
    emptyFilteredTitle: 'Nothing matches',
    emptyFilteredBody: 'Try a different filter or date range.',
    clearFilters: 'Clear filters',
    resultCount: '{{count}} transaction',
    resultCount_plural: '{{count}} transactions',
    loadingMore: 'Loading more…',
    endOfList: 'That\u2019s everything',
    detail: {
      title: 'Payment details',
      amountLabel: 'Amount',
      statusLabel: 'Status',
      modeLabel: 'Paid via',
      txnIdLabel: 'Transaction ID',
      utrLabel: 'UTR / RRN',
      timeLabel: 'Date & time',
      payerLabel: 'Paid by',
      noteLabel: 'Note',
      breakdownTitle: 'Breakdown',
      grossLabel: 'Amount received',
      feeLabel: 'Fee (MDR)',
      netLabel: 'You get',
      noFee: 'No fee',
      settlementTitle: 'Settlement',
      settlementPending: 'Will be settled to your bank account',
      settlementDone: 'Settled to your bank account',
      viewSettlement: 'View settlement',
      refundedLabel: 'Refunded so far',
      actions: 'Actions',
      refund: 'Refund',
      shareReceipt: 'Share receipt',
      raiseDispute: 'Raise dispute',
      reportIssue: 'Report an issue',
      notRefundable: 'This payment cannot be refunded',
      receiptMessage: '{{amount}} received on {{time}}. Transaction ID: {{id}}.',
    },
  },

  refund: {
    title: 'Issue refund',
    originalLabel: 'Original payment',
    refundableLabel: 'Available to refund',
    alreadyRefunded: '{{amount}} already refunded',
    typeFull: 'Full refund',
    typePartial: 'Part refund',
    fullBody: 'Return the whole amount',
    partialBody: 'Return part of the amount',
    amountLabel: 'Refund amount',
    reasonLabel: 'Reason',
    reasonPlaceholder: 'Why is this being refunded? (optional)',
    exceedsRefundable: 'Cannot refund more than {{max}}',
    tooLow: 'Enter an amount above {{min}}',
    confirmCta: 'Refund {{amount}}',
    reauthReason: 'Confirm this refund of {{amount}}',
    processingTitle: 'Processing refund…',
    processingBody: 'Please keep the app open.',
    successTitle: 'Refund started',
    successBody: '{{amount}} is on its way back to the customer. It usually reaches them in 3-5 working days.',
    successDone: 'Done',
    offlineTitle: 'No internet',
    offlineBody: 'Refunds need an internet connection.',
    notEligibleTitle: 'Cannot refund',
    notEligibleBody: 'Only successful payments can be refunded.',
  },

  appLock: {
    title: 'Confirm it\u2019s you',
    biometricPrompt: 'Use your fingerprint or face to confirm',
    biometricFailed: 'Could not verify. Enter your PIN instead.',
    usePin: 'Use PIN instead',
    pinIncorrect: 'Wrong PIN. {{count}} attempts left.',
    lockedOut: 'Too many wrong attempts. Close and reopen the app to try again.',
    setupTitle: 'Create an app PIN',
    setupBody: 'Choose a {{min}}-digit PIN to approve refunds and other sensitive actions.',
    confirmTitle: 'Re-enter your PIN',
    pinMismatch: 'The PINs did not match. Try again.',
    pinTooShort: 'PIN must be at least {{min}} digits',
  },

  reports: {
    title: 'Reports',
    chartTitle: 'Sales trend',
    chartHint: 'Tap a bar to see that day\u2019s total',
    chartA11y: 'Sales trend chart for the selected period',
    statsTitle: 'Summary',
    totalSales: 'Total sales',
    txnCount: 'Payments',
    avgTicket: 'Average sale',
    topMode: 'Most used',
    bestDay: 'Best day',
    tradingDays: 'Days with sales',
    avgPerTradingDay: 'Average per day with sales',
    emptyTitle: 'No sales in this period',
    emptyBody: 'Choose a different date range, or start collecting payments.',
    emptyCta: 'Collect payment',
    errorTitle: 'Could not load your report',
    export: {
      cta: 'Export report',
      preparing: 'Preparing export…',
      failed: 'Could not create the export. Please try again.',
      fileName: 'Sales report',
      formatNote: 'Saved as a CSV file, which opens in Excel and Google Sheets.',
      colDate: 'Date',
      colSales: 'Sales (INR)',
      colCount: 'Payments',
      totalsLabel: 'Total',
      periodLabel: 'Period',
      generatedLabel: 'Generated',
    },
    gst: {
      title: 'GST',
      summaryCta: 'Export GST summary',
      summaryBody: 'A period sales summary with your GSTIN, for your accountant\u2019s GST filing.',
      noGstinTitle: 'No GSTIN on file',
      noGstinBody: 'Add your GSTIN in your business profile to include it in GST exports.',
      invoiceNote: 'Per-payment tax invoices need customer details and item lines, so they are issued from the invoicing feature rather than from payment records.',
      gstinLabel: 'GSTIN',
      fileName: 'GST summary',
      colField: 'Field',
      colValue: 'Value',
      rowBusiness: 'Business name',
      rowGstin: 'GSTIN',
      rowPeriodFrom: 'Period from',
      rowPeriodTo: 'Period to',
      rowTotalSales: 'Total sales (INR)',
      rowTxnCount: 'Number of payments',
      rowNote: 'Note',
      noteValue: 'Summary of payments received. Not a tax invoice.',
    },
  },

  more: {
    title: 'More',
    reports: 'Reports',
    reportsBody: 'Sales trends and exports',
    profile: 'Business profile',
    profileBody: 'Your details, bank account and KYC',
    staff: 'Staff',
    staffBody: 'Add people who can collect payments',
    support: 'Help & support',
    supportBody: 'FAQs, raise a ticket, contact us',
    settings: 'Settings',
    settingsBody: 'Language, audio, notifications, app lock',
    comingSoonBadge: 'Soon',
  },

  dateRange: {
    label: 'Date range',
    all: 'All time',
    today: 'Today',
    yesterday: 'Yesterday',
    last7: 'Last 7 days',
    last30: 'Last 30 days',
    thisMonth: 'This month',
    custom: 'Custom range',
    from: 'From',
    to: 'To',
  },

  settlements: {
    title: 'Settlements',
    status: {
      pending: 'Pending',
      processing: 'In progress',
      settled: 'Settled',
      failed: 'Failed',
    },
    tabs: {
      pending: 'Pending',
      settled: 'Settled',
    },
    batchLabel: 'Batch of {{count}} payment',
    batchLabel_plural: 'Batch of {{count}} payments',
    utrLabel: 'UTR',
    expectedLabel: 'Expected in your bank account',
    creditedLabel: 'Credited to your bank account',
    emptyPendingTitle: 'Nothing pending',
    emptyPendingBody: 'Payments you receive today will be settled to your bank account tomorrow.',
    emptySettledTitle: 'No settlements yet',
    emptySettledBody: 'Once money reaches your bank account it will show here with a UTR.',
    errorTitle: 'Could not load settlements',
    t1Note: 'Money reaches your bank account the next working day.',
    detail: {
      title: 'Settlement details',
      breakdownTitle: 'Breakdown',
      grossLabel: 'Total collected',
      feeLabel: 'Fees',
      netLabel: 'Credited to bank',
      bankTitle: 'Bank account',
      accountLabel: 'Account',
      ifscLabel: 'IFSC',
      utrLabel: 'UTR / reference',
      createdLabel: 'Batch created',
      settledLabel: 'Credited on',
      txnTitle: 'Payments in this batch',
      txnCount: '{{count}} payment',
      txnCount_plural: '{{count}} payments',
      reconcileNote: 'Each payment below adds up to the total collected.',
      noTxnTitle: 'No payments listed',
      noTxnBody: 'This batch has no itemised payments available.',
    },
    statement: {
      download: 'Download statement',
      preparing: 'Preparing statement…',
      failed: 'Could not create the statement. Please try again.',
      fileName: 'Settlement statement',
      /** CSV column headings. */
      colDate: 'Date',
      colTime: 'Time',
      colTxnId: 'Transaction ID',
      colUtr: 'UTR',
      colMode: 'Mode',
      colStatus: 'Status',
      colGross: 'Amount (INR)',
      colFee: 'Fee (INR)',
      colNet: 'Net (INR)',
      totalsLabel: 'Total',
      formatNote: 'Saved as a CSV file, which opens in Excel and Google Sheets.',
    },
    instant: {
      cta: 'Settle now',
      sheetTitle: 'Settle instantly',
      sheetBody: 'Get this money in your bank account within minutes instead of waiting for tomorrow.',
      netLabel: 'Settlement amount',
      feeLabel: 'Instant settlement fee ({{percent}}%)',
      gstLabel: 'GST on fee',
      payoutLabel: 'You will receive',
      confirmCta: 'Settle {{amount}} now',
      processing: 'Settling…',
      successTitle: 'Money on its way',
      successBody: '{{amount}} is being credited to your bank account. It usually arrives within a few minutes.',
      ineligible: {
        already_settled: 'This batch is already settled.',
        below_minimum: 'Instant settlement needs at least {{min}}.',
        failed_batch: 'This batch failed and cannot be settled instantly.',
      },
      offlineBody: 'Instant settlement needs an internet connection.',
    },
  },

  collect: {
    title: 'Collect payment',
    subtitle: 'How would you like to get paid?',
    modes: {
      staticQr: 'My QR code',
      staticQrBody: 'One code for any amount. Show or print it.',
      dynamicQr: 'Enter amount',
      dynamicQrBody: 'Create a QR for an exact amount.',
      paymentLink: 'Payment link',
      paymentLinkBody: 'Send a link on WhatsApp or SMS.',
    },
    staticQr: {
      title: 'My QR code',
      instruction: 'Ask the customer to scan and pay any amount.',
      vpaLabel: 'UPI ID',
      noQrTitle: 'QR not ready yet',
      noQrBody: 'Finish your bank verification to get your QR code.',
      noQrCta: 'Complete verification',
      offlineUsable: 'Your QR works without internet.',
    },
    amount: {
      title: 'Enter amount',
      generateQr: 'Generate QR',
      createLink: 'Create link',
      noteLabel: 'Note',
      notePlaceholder: 'What is this for? (optional)',
      tooLow: 'Enter an amount above {{min}}',
      limitExceeded: 'Daily limit is {{limit}} until verification completes',
      upiCap: 'Maximum {{max}} per UPI payment',
    },
    dynamicQr: {
      title: 'Scan to pay',
      waiting: 'Waiting for payment…',
      waitingBody: 'Ask the customer to scan this code.',
      expiresIn: 'Expires in {{time}}',
      expiredTitle: 'QR expired',
      expiredBody: 'This code is no longer valid. Create a new one.',
      newQr: 'Create new QR',
      cancel: 'Cancel',
      checkingSlowly: 'Still checking. Your connection seems slow.',
      failedTitle: 'Payment failed',
      failedBody: 'The customer\u2019s payment did not go through. Ask them to try again.',
      offlineTitle: 'No internet',
      offlineBody: 'A QR for a fixed amount needs internet. Use your own QR code instead.',
      useStaticQr: 'Use my QR code',
    },
    link: {
      title: 'Payment link',
      createdTitle: 'Link ready',
      createdBody: 'Send this to your customer. It expires in 24 hours.',
      copy: 'Copy link',
      copied: 'Link copied',
      shareVia: 'Share link',
      newLink: 'Create another',
      shareMessage: 'Please pay {{amount}} using this link: {{url}}',
    },
    success: {
      title: 'Payment received!',
      amountLabel: 'Amount received',
      txnIdLabel: 'Transaction ID',
      timeLabel: 'Time',
      payerLabel: 'Paid by',
      utrLabel: 'UPI reference',
      shareReceipt: 'Share receipt',
      newPayment: 'New payment',
      done: 'Done',
      receiptMessage: 'Payment received: {{amount}} on {{time}}. Transaction ID: {{id}}.',
    },
    audio: {
      /** Spoken aloud. `amount` is a bare numeral, so keep the currency word here. */
      received: '{{amount}} rupees received',
      mutedHint: 'Audio confirmation is off. Turn it on in Settings.',
    },
  },
} as const;

/**
 * Widens the literal types produced by `as const` into plain `string`s, so other
 * language bundles are checked for *structural* completeness (same key tree)
 * without being forced to reproduce the English text verbatim.
 */
type Widen<T> = T extends string ? string : { [K in keyof T]: Widen<T[K]> };

export type TranslationBundle = Widen<typeof en>;
export default en;
