/**
 * English resource bundle — the canonical source of truth.
 *
 * Every other language must satisfy the `TranslationBundle` type derived from
 * this file, so a missing key is a compile error rather than a runtime fallback.
 * Per App-PRD Section 5: "All strings via i18n keys — no hardcoded text."
 *
 * Keys are added as screens are built; this bundle covers Section 16 steps 1-4
 * (scaffold, auth, KYC, home) plus the navigation shell.
 */
export const en = {
  common: {
    appName: 'MerchantOne',
    ok: 'OK',
    cancel: 'Cancel',
    continue: 'Continue',
    back: 'Back',
    next: 'Next',
    skip: 'Skip',
    done: 'Done',
    retry: 'Try again',
    save: 'Save',
    close: 'Close',
    share: 'Share',
    download: 'Download',
    search: 'Search',
    viewAll: 'View all',
    today: 'Today',
    yesterday: 'Yesterday',
    loading: 'Loading…',
    yes: 'Yes',
    no: 'No',
    optional: 'Optional',
    verified: 'Verified',
    verifying: 'Verifying…',
    edit: 'Edit',
    remove: 'Remove',
    confirm: 'Confirm',
    comingSoon: 'Coming soon',
    comingSoonBody: 'This section is being built.',
    months: {
      jan: 'Jan',
      feb: 'Feb',
      mar: 'Mar',
      apr: 'Apr',
      may: 'May',
      jun: 'Jun',
      jul: 'Jul',
      aug: 'Aug',
      sep: 'Sep',
      oct: 'Oct',
      nov: 'Nov',
      dec: 'Dec',
    },
  },

  a11y: {
    back: 'Go back',
    close: 'Close',
    notifications: 'Notifications',
    loading: 'Loading content',
    amount: 'Amount {{amount}}',
    step: 'Step {{current}} of {{total}}',
  },

  tabs: {
    home: 'Home',
    collect: 'Collect',
    transactions: 'Transactions',
    settlements: 'Settlements',
    more: 'More',
  },

  network: {
    offlineTitle: 'You are offline',
    offlineBanner: 'No internet connection. Showing saved data.',
    offlineActionDisabled: 'This needs an internet connection.',
    backOnline: 'Back online',
  },

  errors: {
    title: 'Something went wrong',
    network_error: 'Cannot reach our servers. Check your connection and try again.',
    timeout: 'This is taking too long. Please try again.',
    offline: 'You are offline. Connect to the internet and try again.',
    unauthorized: 'Your session has expired. Please log in again.',
    forbidden: 'You do not have permission to do this.',
    not_found: 'We could not find what you were looking for.',
    validation_error: 'Please check the details you entered.',
    rate_limited: 'Too many attempts. Please wait a moment and try again.',
    invalid_otp: 'That OTP is incorrect. Please check and try again.',
    otp_expired: 'This OTP has expired. Request a new one.',
    invalid_mobile: 'Enter a valid 10-digit mobile number.',
    kyc_incomplete: 'Complete your KYC to use this feature.',
    kyc_rejected: 'Your KYC was not approved. Please review and resubmit.',
    bank_verification_failed: 'We could not verify this bank account. Check the details and try again.',
    pan_verification_failed: 'We could not verify this PAN. Check the number and try again.',
    already_refunded: 'This transaction has already been refunded.',
    refund_limit_exceeded: 'The refund amount is more than the available balance.',
    payment_expired: 'This payment request has expired. Create a new one.',
    server_error: 'Our servers are having trouble. Please try again shortly.',
    unknown: 'Something went wrong. Please try again.',
  },

  auth: {
    splash: {
      tagline: 'Payments made simple',
    },
    login: {
      title: 'Welcome',
      subtitle: 'Log in with your mobile number to manage your business',
      mobileLabel: 'Mobile number',
      mobilePlaceholder: '10-digit mobile number',
      mobileRequired: 'Enter your mobile number',
      mobileInvalid: 'Enter a valid 10-digit mobile number',
      consent: 'I agree to the Terms of Service and Privacy Policy',
      consentRequired: 'Please accept the Terms to continue',
      getOtp: 'Get OTP',
      secureNote: 'We will send a 6-digit code to verify your number.',
    },
    otp: {
      title: 'Verify your number',
      subtitle: 'Enter the 6-digit code sent to {{mobile}}',
      otpRequired: 'Enter the 6-digit code',
      otpInvalid: 'The code must be 6 digits',
      verify: 'Verify',
      resend: 'Resend code',
      resendIn: 'Resend code in {{seconds}}s',
      changeNumber: 'Change number',
      autoReadHint: 'We will read the code automatically if permitted.',
      hintDev: 'Demo mode: use {{otp}}',
    },
  },

  kyc: {
    title: 'Business verification',
    stepOf: 'Step {{current}} of {{total}}',
    saveAndExit: 'Save & exit',
    resumeTitle: 'Resume verification',
    resumeBody: 'You left off at step {{step}}. Pick up where you stopped.',
    progress: {
      business: 'Business',
      identity: 'Identity',
      bank: 'Bank',
      aadhaar: 'Aadhaar',
    },
    business: {
      title: 'Tell us about your business',
      subtitle: 'This appears on the QR your customers scan.',
      name: 'Business name',
      namePlaceholder: 'e.g. Sharma General Store',
      nameRequired: 'Enter your business name',
      nameTooShort: 'Business name must be at least 3 characters',
      category: 'Business category',
      categoryPlaceholder: 'Select a category',
      categoryRequired: 'Select your business category',
      categorySheetTitle: 'Select business category',
      addressLine1: 'Shop / building address',
      addressPlaceholder: 'Shop number, street, area',
      addressRequired: 'Enter your business address',
      pincode: 'PIN code',
      pincodePlaceholder: '6-digit PIN code',
      pincodeRequired: 'Enter your PIN code',
      pincodeInvalid: 'Enter a valid 6-digit PIN code',
      city: 'City',
      cityRequired: 'Enter your city',
      state: 'State',
      stateRequired: 'Enter your state',
      pincodeLookup: 'Finding your area…',
    },
    identity: {
      title: 'Identity details',
      subtitle: 'Required by RBI to accept payments.',
      pan: 'PAN number',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'Enter your PAN number',
      panInvalid: 'Enter a valid PAN (e.g. ABCDE1234F)',
      panHelp: 'As printed on your PAN card.',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'Enter a valid 15-character GSTIN',
      gstinHelp: 'Add this if you want GST-compliant invoices.',
    },
    bank: {
      title: 'Where should we settle your money?',
      subtitle: 'Your collections are credited here, by default the next day.',
      accountNumber: 'Account number',
      accountNumberPlaceholder: 'Bank account number',
      accountNumberRequired: 'Enter your account number',
      accountNumberInvalid: 'Account number must be 9 to 18 digits',
      confirmAccountNumber: 'Re-enter account number',
      accountMismatch: 'Account numbers do not match',
      ifsc: 'IFSC code',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'Enter the IFSC code',
      ifscInvalid: 'Enter a valid IFSC (e.g. HDFC0001234)',
      holderName: 'Account holder name',
      holderNamePlaceholder: 'Name as per bank records',
      holderNameRequired: 'Enter the account holder name',
      verifyCta: 'Verify account',
      verifying: 'Verifying your account…',
      verifyingBody: 'We are sending ₹1 to confirm this account belongs to you.',
      verifiedTitle: 'Account verified',
      verifiedNameAtBank: 'Name at bank: {{name}}',
      unlockNote: 'After this step you can start accepting payments, with limits, while we finish checks.',
    },
    aadhaar: {
      title: 'Aadhaar verification',
      subtitle: 'The last step to unlock all features.',
      numberLabel: 'Aadhaar number',
      numberPlaceholder: '12-digit Aadhaar number',
      numberRequired: 'Enter your Aadhaar number',
      numberInvalid: 'Aadhaar number must be 12 digits',
      consent: 'I consent to verify my identity using Aadhaar eKYC. I understand my Aadhaar details will be used only for this verification.',
      consentRequired: 'Your consent is required to continue',
      sendOtp: 'Send Aadhaar OTP',
      otpLabel: 'Aadhaar OTP',
      otpSentTo: 'Enter the code sent to the mobile linked with your Aadhaar.',
      otpRequired: 'Enter the 6-digit Aadhaar OTP',
      verifyCta: 'Verify Aadhaar',
      verifiedTitle: 'Aadhaar verified',
      skipForNow: 'Do this later',
      privacyNote: 'We never store your full Aadhaar number.',
    },
    done: {
      title: 'You are all set!',
      subtitle: 'Your details are submitted. You can start accepting payments right away.',
      pendingTitle: 'Verification in progress',
      pendingSubtitle: 'We are reviewing your details. This usually takes a few hours.',
      generateQr: 'Generate my QR',
      goHome: 'Go to dashboard',
      vpaLabel: 'Your UPI ID',
      limitsNote: 'Until verification completes, you can collect up to {{limit}} per day.',
    },
    status: {
      not_started: 'KYC pending',
      in_progress: 'KYC incomplete',
      pending_review: 'Under review',
      approved: 'Verified',
      rejected: 'Action needed',
    },
    rejected: {
      title: 'We need another look',
      reasonLabel: 'Reason',
      retryCta: 'Update details',
    },
    submitCta: 'Submit for verification',
    mcc: {
      grocery: 'Grocery / Kirana store',
      restaurant: 'Restaurant / Café',
      apparel: 'Clothing & apparel',
      electronics: 'Electronics & mobiles',
      pharmacy: 'Pharmacy / Medical',
      salon: 'Salon & beauty',
      hardware: 'Hardware & building supplies',
      services: 'Professional services',
      education: 'Education & coaching',
      transport: 'Transport & travel',
      online: 'Online / D2C seller',
      other: 'Other',
    },
  },

  home: {
    greeting: 'Namaste',
    summary: {
      title: "Today's collections",
      collected: 'Collected today',
      txnCount: '{{count}} payment',
      txnCount_plural: '{{count}} payments',
      pendingSettlement: 'Pending settlement',
      settlementHint: 'Credited to your bank account',
    },
    collectCta: 'Collect payment',
    quickActions: {
      title: 'Quick actions',
      myQr: 'My QR',
      paymentLink: 'Payment link',
      reports: 'Reports',
      refund: 'Refund',
    },
    recent: {
      title: 'Recent payments',
      emptyTitle: 'No payments yet',
      emptyBody: 'Show your QR to a customer to receive your first payment.',
      emptyCta: 'Show my QR',
    },
    kycNudge: {
      title: 'Finish verification',
      body: 'Complete your details to remove collection limits.',
      cta: 'Continue',
    },
    error: {
      title: 'Could not load your dashboard',
      body: 'Check your connection and try again.',
    },
  },

  notifications: {
    title: 'Notifications',
    emptyTitle: 'No notifications',
    emptyBody: 'Payment and settlement updates will appear here.',
  },

  transactions: {
    title: 'Transactions',
    status: {
      success: 'Received',
      pending: 'Pending',
      failed: 'Failed',
      refunded: 'Refunded',
      partially_refunded: 'Part refunded',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI app',
      payment_link: 'Payment link',
      card: 'Card',
      netbanking: 'Net banking',
      wallet: 'Wallet',
    },
  },

  settlements: {
    title: 'Settlements',
    status: {
      pending: 'Pending',
      processing: 'In progress',
      settled: 'Settled',
      failed: 'Failed',
    },
  },
} as const;

/**
 * Widens the literal types produced by `as const` into plain `string`s, so other
 * language bundles are checked for *structural* completeness (same key tree)
 * without being forced to reproduce the English text verbatim.
 */
type Widen<T> = T extends string ? string : { [K in keyof T]: Widen<T[K]> };

export type TranslationBundle = Widen<typeof en>;
export default en;
