import type { TranslationBundle } from './en';

/** Gujarati (ગુજરાતી) */
export const gu: TranslationBundle = {
  common: {
    appName: 'MerchantOne',
    ok: 'ઠીક',
    cancel: 'રદ કરો',
    continue: 'આગળ વધો',
    back: 'પાછળ',
    next: 'આગળ',
    skip: 'છોડી દો',
    done: 'થઈ ગયું',
    retry: 'ફરી પ્રયાસ કરો',
    save: 'સેવ કરો',
    close: 'બંધ કરો',
    share: 'શેર કરો',
    download: 'ડાઉનલોડ',
    search: 'શોધો',
    viewAll: 'બધું જુઓ',
    today: 'આજે',
    yesterday: 'ગઈકાલે',
    loading: 'લોડ થઈ રહ્યું છે…',
    yes: 'હા',
    no: 'ના',
    optional: 'વૈકલ્પિક',
    verified: 'ચકાસાયેલ',
    verifying: 'ચકાસી રહ્યા છીએ…',
    edit: 'બદલો',
    remove: 'દૂર કરો',
    confirm: 'ખાતરી કરો',
    comingSoon: 'ટૂંક સમયમાં',
    comingSoonBody: 'આ વિભાગ તૈયાર થઈ રહ્યો છે.',
    months: {
      jan: 'જાન્યુ',
      feb: 'ફેબ્રુ',
      mar: 'માર્ચ',
      apr: 'એપ્રિ',
      may: 'મે',
      jun: 'જૂન',
      jul: 'જુલા',
      aug: 'ઓગ',
      sep: 'સપ્ટે',
      oct: 'ઓક્ટો',
      nov: 'નવે',
      dec: 'ડિસે',
    },
  },

  a11y: {
    back: 'પાછળ જાઓ',
    close: 'બંધ કરો',
    notifications: 'સૂચનાઓ',
    loading: 'સામગ્રી લોડ થઈ રહી છે',
    amount: 'રકમ {{amount}}',
    step: 'પગલું {{current}} / {{total}}',
  },

  tabs: {
    home: 'હોમ',
    collect: 'પૈસા લો',
    transactions: 'વ્યવહારો',
    settlements: 'સેટલમેન્ટ',
    more: 'વધુ',
  },

  network: {
    offlineTitle: 'તમે ઓફલાઇન છો',
    offlineBanner: 'ઇન્ટરનેટ નથી. સેવ કરેલી માહિતી બતાવી રહ્યા છીએ.',
    offlineActionDisabled: 'આ માટે ઇન્ટરનેટ કનેક્શન જરૂરી છે.',
    backOnline: 'ઇન્ટરનેટ પરત આવ્યું',
  },

  errors: {
    title: 'કંઈક ખોટું થયું',
    network_error: 'સર્વર સાથે સંપર્ક થતો નથી. કનેક્શન તપાસી ફરી પ્રયાસ કરો.',
    timeout: 'ઘણો સમય લાગી રહ્યો છે. ફરી પ્રયાસ કરો.',
    offline: 'તમે ઓફલાઇન છો. ઇન્ટરનેટ સાથે જોડાઈ ફરી પ્રયાસ કરો.',
    unauthorized: 'તમારું સેશન સમાપ્ત થયું. કૃપા કરી ફરી લોગ ઇન કરો.',
    forbidden: 'આ કરવાની તમને પરવાનગી નથી.',
    not_found: 'તમે જે શોધી રહ્યા હતા તે મળ્યું નથી.',
    validation_error: 'કૃપા કરી ભરેલી માહિતી તપાસો.',
    rate_limited: 'ઘણા પ્રયાસો થયા. થોડી વાર પછી પ્રયાસ કરો.',
    invalid_otp: 'આ OTP ખોટો છે. તપાસી ફરી નાખો.',
    otp_expired: 'આ OTP સમાપ્ત થયો. નવો મંગાવો.',
    invalid_mobile: 'સાચો 10 અંકનો મોબાઇલ નંબર નાખો.',
    kyc_incomplete: 'આ સુવિધા માટે તમારું KYC પૂર્ણ કરો.',
    kyc_rejected: 'તમારું KYC મંજૂર થયું નથી. તપાસી ફરી મોકલો.',
    bank_verification_failed: 'આ બેંક ખાતું ચકાસી શકાયું નથી. માહિતી તપાસો.',
    pan_verification_failed: 'આ PAN ચકાસી શકાયો નથી. નંબર તપાસો.',
    already_refunded: 'આ વ્યવહારનું રિફંડ પહેલેથી થઈ ગયું છે.',
    refund_limit_exceeded: 'રિફંડની રકમ ઉપલબ્ધ રકમથી વધુ છે.',
    payment_expired: 'આ પેમેન્ટ વિનંતી સમાપ્ત થઈ. નવી બનાવો.',
    server_error: 'અમારા સર્વરમાં તકલીફ છે. થોડી વાર પછી પ્રયાસ કરો.',
    unknown: 'કંઈક ખોટું થયું. ફરી પ્રયાસ કરો.',
  },

  auth: {
    splash: {
      tagline: 'પેમેન્ટ હવે સરળ',
    },
    login: {
      title: 'સ્વાગત છે',
      subtitle: 'તમારો ધંધો સંભાળવા મોબાઇલ નંબરથી લોગ ઇન કરો',
      mobileLabel: 'મોબાઇલ નંબર',
      mobilePlaceholder: '10 અંકનો મોબાઇલ નંબર',
      mobileRequired: 'તમારો મોબાઇલ નંબર નાખો',
      mobileInvalid: 'સાચો 10 અંકનો મોબાઇલ નંબર નાખો',
      consent: 'હું સેવાની શરતો અને ગોપનીયતા નીતિ સ્વીકારું છું',
      consentRequired: 'આગળ વધવા શરતો સ્વીકારો',
      getOtp: 'OTP મેળવો',
      secureNote: 'તમારો નંબર ચકાસવા અમે 6 અંકનો કોડ મોકલીશું.',
    },
    otp: {
      title: 'તમારો નંબર ચકાસો',
      subtitle: '{{mobile}} પર મોકલેલો 6 અંકનો કોડ નાખો',
      otpRequired: '6 અંકનો કોડ નાખો',
      otpInvalid: 'કોડ 6 અંકનો હોવો જોઈએ',
      verify: 'ચકાસો',
      resend: 'કોડ ફરી મોકલો',
      resendIn: '{{seconds}} સેકંડમાં ફરી મોકલો',
      changeNumber: 'નંબર બદલો',
      autoReadHint: 'પરવાનગી હોય તો કોડ અમે જાતે ભરી દઈશું.',
      hintDev: 'ડેમો મોડ: {{otp}} વાપરો',
    },
  },

  kyc: {
    title: 'ધંધાની ચકાસણી',
    stepOf: 'પગલું {{current}} / {{total}}',
    saveAndExit: 'સેવ કરીને બહાર નીકળો',
    resumeTitle: 'ચકાસણી ચાલુ રાખો',
    resumeBody: 'તમે પગલું {{step}} પર અટક્યા હતા. ત્યાંથી આગળ વધો.',
    progress: {
      business: 'ધંધો',
      identity: 'ઓળખ',
      bank: 'બેંક',
      aadhaar: 'આધાર',
    },
    business: {
      title: 'તમારા ધંધા વિશે જણાવો',
      subtitle: 'ગ્રાહકો સ્કેન કરે તે QR પર આ દેખાશે.',
      name: 'ધંધાનું નામ',
      namePlaceholder: 'જેમ કે શર્મા જનરલ સ્ટોર',
      nameRequired: 'તમારા ધંધાનું નામ નાખો',
      nameTooShort: 'નામ ઓછામાં ઓછું 3 અક્ષરનું હોવું જોઈએ',
      category: 'ધંધાનો પ્રકાર',
      categoryPlaceholder: 'એક પ્રકાર પસંદ કરો',
      categoryRequired: 'તમારા ધંધાનો પ્રકાર પસંદ કરો',
      categorySheetTitle: 'ધંધાનો પ્રકાર પસંદ કરો',
      addressLine1: 'દુકાન / મકાનનું સરનામું',
      addressPlaceholder: 'દુકાન નંબર, શેરી, વિસ્તાર',
      addressRequired: 'તમારા ધંધાનું સરનામું નાખો',
      pincode: 'પિન કોડ',
      pincodePlaceholder: '6 અંકનો પિન કોડ',
      pincodeRequired: 'તમારો પિન કોડ નાખો',
      pincodeInvalid: 'સાચો 6 અંકનો પિન કોડ નાખો',
      city: 'શહેર',
      cityRequired: 'તમારું શહેર નાખો',
      state: 'રાજ્ય',
      stateRequired: 'તમારું રાજ્ય નાખો',
      pincodeLookup: 'તમારો વિસ્તાર શોધી રહ્યા છીએ…',
    },
    identity: {
      title: 'ઓળખની માહિતી',
      subtitle: 'પેમેન્ટ સ્વીકારવા RBI દ્વારા જરૂરી.',
      pan: 'PAN નંબર',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'તમારો PAN નંબર નાખો',
      panInvalid: 'સાચો PAN નાખો (જેમ કે ABCDE1234F)',
      panHelp: 'તમારા PAN કાર્ડ પર છપાયેલ છે તે પ્રમાણે.',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'સાચો 15 અક્ષરનો GSTIN નાખો',
      gstinHelp: 'GST બિલ જોઈએ તો આ ઉમેરો.',
    },
    bank: {
      title: 'તમારા પૈસા ક્યાં મોકલવા?',
      subtitle: 'તમારી આવક અહીં જમા થશે, સામાન્ય રીતે બીજા દિવસે.',
      accountNumber: 'ખાતા નંબર',
      accountNumberPlaceholder: 'બેંક ખાતા નંબર',
      accountNumberRequired: 'તમારો ખાતા નંબર નાખો',
      accountNumberInvalid: 'ખાતા નંબર 9 થી 18 અંકનો હોવો જોઈએ',
      confirmAccountNumber: 'ખાતા નંબર ફરી નાખો',
      accountMismatch: 'ખાતા નંબર મળતા નથી',
      ifsc: 'IFSC કોડ',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'IFSC કોડ નાખો',
      ifscInvalid: 'સાચો IFSC નાખો (જેમ કે HDFC0001234)',
      holderName: 'ખાતાધારકનું નામ',
      holderNamePlaceholder: 'બેંક રેકોર્ડ પ્રમાણે નામ',
      holderNameRequired: 'ખાતાધારકનું નામ નાખો',
      verifyCta: 'ખાતું ચકાસો',
      verifying: 'તમારું ખાતું ચકાસી રહ્યા છીએ…',
      verifyingBody: 'આ ખાતું તમારું જ છે તેની ખાતરી માટે અમે ₹1 મોકલી રહ્યા છીએ.',
      verifiedTitle: 'ખાતું ચકાસાયું',
      verifiedNameAtBank: 'બેંકમાં નામ: {{name}}',
      unlockNote: 'આ પગલા પછી મર્યાદા સાથે પેમેન્ટ લેવાનું શરૂ કરી શકો, ચકાસણી પૂરી થાય ત્યાં સુધી.',
    },
    aadhaar: {
      title: 'આધાર ચકાસણી',
      subtitle: 'બધી સુવિધા ખોલવા છેલ્લું પગલું.',
      numberLabel: 'આધાર નંબર',
      numberPlaceholder: '12 અંકનો આધાર નંબર',
      numberRequired: 'તમારો આધાર નંબર નાખો',
      numberInvalid: 'આધાર નંબર 12 અંકનો હોવો જોઈએ',
      consent: 'હું આધાર eKYC દ્વારા મારી ઓળખ ચકાસવા સંમતિ આપું છું. મારી આધાર માહિતી ફક્ત આ ચકાસણી માટે વપરાશે તે હું સમજું છું.',
      consentRequired: 'આગળ વધવા તમારી સંમતિ જરૂરી છે',
      sendOtp: 'આધાર OTP મોકલો',
      otpLabel: 'આધાર OTP',
      otpSentTo: 'આધાર સાથે જોડાયેલા મોબાઇલ પર મોકલેલો કોડ નાખો.',
      otpRequired: '6 અંકનો આધાર OTP નાખો',
      verifyCta: 'આધાર ચકાસો',
      verifiedTitle: 'આધાર ચકાસાયો',
      skipForNow: 'પછી કરો',
      privacyNote: 'તમારો પૂરો આધાર નંબર અમે કદી સાચવતા નથી.',
    },
    done: {
      title: 'બધું તૈયાર!',
      subtitle: 'તમારી માહિતી મોકલાઈ ગઈ. તમે હવે પેમેન્ટ લેવાનું શરૂ કરી શકો.',
      pendingTitle: 'ચકાસણી ચાલુ છે',
      pendingSubtitle: 'અમે તમારી માહિતી તપાસી રહ્યા છીએ. સામાન્ય રીતે થોડા કલાક લાગે.',
      generateQr: 'મારો QR બનાવો',
      goHome: 'ડેશબોર્ડ પર જાઓ',
      vpaLabel: 'તમારી UPI ID',
      limitsNote: 'ચકાસણી પૂરી થાય ત્યાં સુધી તમે રોજ {{limit}} સુધી લઈ શકો.',
    },
    status: {
      not_started: 'KYC બાકી',
      in_progress: 'KYC અધૂરું',
      pending_review: 'તપાસ હેઠળ',
      approved: 'ચકાસાયેલ',
      rejected: 'પગલું જરૂરી',
    },
    rejected: {
      title: 'અમારે ફરી જોવું પડશે',
      reasonLabel: 'કારણ',
      retryCta: 'માહિતી અપડેટ કરો',
    },
    submitCta: 'ચકાસણી માટે મોકલો',
    mcc: {
      grocery: 'કરિયાણા / જનરલ સ્ટોર',
      restaurant: 'રેસ્ટોરન્ટ / કેફે',
      apparel: 'કપડાં',
      electronics: 'ઇલેક્ટ્રોનિક્સ અને મોબાઇલ',
      pharmacy: 'દવાની દુકાન / મેડિકલ',
      salon: 'સેલૂન અને બ્યુટી',
      hardware: 'હાર્ડવેર અને બાંધકામ સામગ્રી',
      services: 'વ્યાવસાયિક સેવાઓ',
      education: 'શિક્ષણ અને કોચિંગ',
      transport: 'પરિવહન અને પ્રવાસ',
      online: 'ઓનલાઇન / D2C વિક્રેતા',
      other: 'અન્ય',
    },
  },

  home: {
    greeting: 'નમસ્તે',
    summary: {
      title: 'આજની આવક',
      collected: 'આજે મળ્યું',
      txnCount: '{{count}} પેમેન્ટ',
      txnCount_plural: '{{count}} પેમેન્ટ',
      pendingSettlement: 'સેટલમેન્ટ બાકી',
      settlementHint: 'તમારા બેંક ખાતામાં જમા થશે',
    },
    collectCta: 'પૈસા લો',
    quickActions: {
      title: 'ઝડપી કામ',
      myQr: 'મારો QR',
      paymentLink: 'પેમેન્ટ લિંક',
      reports: 'રિપોર્ટ',
      refund: 'રિફંડ',
    },
    recent: {
      title: 'તાજેતરના પેમેન્ટ',
      emptyTitle: 'હજી કોઈ પેમેન્ટ નથી',
      emptyBody: 'પહેલું પેમેન્ટ મેળવવા ગ્રાહકને તમારો QR બતાવો.',
      emptyCta: 'મારો QR બતાવો',
    },
    kycNudge: {
      title: 'ચકાસણી પૂરી કરો',
      body: 'મર્યાદા દૂર કરવા તમારી માહિતી પૂરી કરો.',
      cta: 'આગળ વધો',
    },
    error: {
      title: 'ડેશબોર્ડ લોડ થઈ શક્યું નથી',
      body: 'કનેક્શન તપાસી ફરી પ્રયાસ કરો.',
    },
  },

  notifications: {
    title: 'સૂચનાઓ',
    emptyTitle: 'કોઈ સૂચના નથી',
    emptyBody: 'પેમેન્ટ અને સેટલમેન્ટની માહિતી અહીં દેખાશે.',
  },

  transactions: {
    title: 'વ્યવહારો',
    status: {
      success: 'મળ્યું',
      pending: 'બાકી',
      failed: 'નિષ્ફળ',
      refunded: 'પરત કર્યું',
      partially_refunded: 'આંશિક પરત',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI એપ',
      payment_link: 'પેમેન્ટ લિંક',
      card: 'કાર્ડ',
      netbanking: 'નેટ બેંકિંગ',
      wallet: 'વોલેટ',
    },
    filters: {
      all: 'બધા',
      success: 'મળ્યું',
      pending: 'બાકી',
      failed: 'નિષ્ફળ',
      refunded: 'પરત કર્યું',
    },
    searchPlaceholder: 'રકમ, UTR કે ભરનાર શોધો',
    emptyTitle: 'કોઈ વ્યવહાર નથી',
    emptyBody: 'તમને મળતા પેમેન્ટ અહીં દેખાશે.',
    emptyFilteredTitle: 'કંઈ મળ્યું નથી',
    emptyFilteredBody: 'બીજું ફિલ્ટર કે તારીખ પસંદ કરીને જુઓ.',
    clearFilters: 'ફિલ્ટર દૂર કરો',
    resultCount: '{{count}} વ્યવહાર',
    resultCount_plural: '{{count}} વ્યવહારો',
    loadingMore: 'વધુ લોડ થઈ રહ્યું છે…',
    endOfList: 'આટલું જ છે',
    detail: {
      title: 'પેમેન્ટની વિગત',
      amountLabel: 'રકમ',
      statusLabel: 'સ્થિતિ',
      modeLabel: 'કઈ રીતે મળ્યું',
      txnIdLabel: 'વ્યવહાર ID',
      utrLabel: 'UTR / RRN',
      timeLabel: 'તારીખ અને સમય',
      payerLabel: 'ભરનાર',
      noteLabel: 'નોંધ',
      breakdownTitle: 'હિસાબ',
      grossLabel: 'મળેલી રકમ',
      feeLabel: 'ફી (MDR)',
      netLabel: 'તમને મળશે',
      noFee: 'કોઈ ફી નથી',
      settlementTitle: 'સેટલમેન્ટ',
      settlementPending: 'તમારા બેંક ખાતામાં મોકલવામાં આવશે',
      settlementDone: 'તમારા બેંક ખાતામાં મોકલી દીધું',
      viewSettlement: 'સેટલમેન્ટ જુઓ',
      refundedLabel: 'હજી સુધી પરત કર્યું',
      actions: 'ક્રિયાઓ',
      refund: 'રિફંડ',
      shareReceipt: 'રસીદ શેર કરો',
      raiseDispute: 'ફરિયાદ નોંધાવો',
      reportIssue: 'સમસ્યા જણાવો',
      notRefundable: 'આ પેમેન્ટ રિફંડ થઈ શકતું નથી',
      receiptMessage: '{{time}} વાગ્યે {{amount}} મળ્યું. વ્યવહાર ID: {{id}}.',
    },
  },

  refund: {
    title: 'રિફંડ કરો',
    originalLabel: 'મૂળ પેમેન્ટ',
    refundableLabel: 'રિફંડ માટે ઉપલબ્ધ',
    alreadyRefunded: '{{amount}} પહેલેથી પરત કર્યું',
    typeFull: 'પૂરું રિફંડ',
    typePartial: 'આંશિક રિફંડ',
    fullBody: 'પૂરી રકમ પરત કરો',
    partialBody: 'રકમનો કેટલોક ભાગ પરત કરો',
    amountLabel: 'રિફંડની રકમ',
    reasonLabel: 'કારણ',
    reasonPlaceholder: 'રિફંડ કેમ? (વૈકલ્પિક)',
    exceedsRefundable: '{{max}} થી વધુ રિફંડ થઈ શકતું નથી',
    tooLow: '{{min}} થી વધુ રકમ નાખો',
    confirmCta: '{{amount}} રિફંડ કરો',
    reauthReason: '{{amount}} ના રિફંડની ખાતરી કરો',
    processingTitle: 'રિફંડ થઈ રહ્યું છે…',
    processingBody: 'કૃપા કરી એપ ખુલ્લી રાખો.',
    successTitle: 'રિફંડ શરૂ થયું',
    successBody: '{{amount}} ગ્રાહકને પરત મોકલાઈ રહ્યું છે. સામાન્ય રીતે 3-5 કામકાજના દિવસ લાગે.',
    successDone: 'થઈ ગયું',
    offlineTitle: 'ઇન્ટરનેટ નથી',
    offlineBody: 'રિફંડ માટે ઇન્ટરનેટ કનેક્શન જરૂરી છે.',
    notEligibleTitle: 'રિફંડ થઈ શકતું નથી',
    notEligibleBody: 'ફક્ત સફળ પેમેન્ટનું રિફંડ થઈ શકે.',
  },

  appLock: {
    title: 'ખાતરી કરો કે આ તમે છો',
    biometricPrompt: 'ખાતરી માટે આંગળીની છાપ કે ચહેરો વાપરો',
    biometricFailed: 'ચકાસી શકાયું નથી. તેના બદલે PIN નાખો.',
    usePin: 'PIN વાપરો',
    pinIncorrect: 'ખોટો PIN. {{count}} પ્રયાસ બાકી.',
    lockedOut: 'ઘણા ખોટા પ્રયાસ. એપ બંધ કરીને ફરી ખોલો.',
    setupTitle: 'એપ PIN બનાવો',
    setupBody: 'રિફંડ જેવી મહત્વની ક્રિયાઓ મંજૂર કરવા {{min}} અંકનો PIN પસંદ કરો.',
    confirmTitle: 'PIN ફરી નાખો',
    pinMismatch: 'PIN મળતા નથી. ફરી પ્રયાસ કરો.',
    pinTooShort: 'PIN ઓછામાં ઓછો {{min}} અંકનો હોવો જોઈએ',
  },

  dateRange: {
    label: 'તારીખની શ્રેણી',
    all: 'બધો સમય',
    today: 'આજે',
    yesterday: 'ગઈકાલે',
    last7: 'છેલ્લા 7 દિવસ',
    last30: 'છેલ્લા 30 દિવસ',
    thisMonth: 'આ મહિને',
    custom: 'તમારી શ્રેણી',
    from: 'થી',
    to: 'સુધી',
  },

  settlements: {
    title: 'સેટલમેન્ટ',
    status: {
      pending: 'બાકી',
      processing: 'ચાલુ છે',
      settled: 'જમા થયું',
      failed: 'નિષ્ફળ',
    },
  },

  collect: {
    title: 'પૈસા લો',
    subtitle: 'તમે કેવી રીતે પૈસા લેવા માંગો છો?',
    modes: {
      staticQr: 'મારો QR કોડ',
      staticQrBody: 'કોઈપણ રકમ માટે એક જ કોડ. બતાવો કે છપાવો.',
      dynamicQr: 'રકમ નાખો',
      dynamicQrBody: 'નક્કી રકમ માટે QR બનાવો.',
      paymentLink: 'પેમેન્ટ લિંક',
      paymentLinkBody: 'WhatsApp કે SMS પર લિંક મોકલો.',
    },
    staticQr: {
      title: 'મારો QR કોડ',
      instruction: 'ગ્રાહકને સ્કેન કરીને કોઈપણ રકમ ભરવા કહો.',
      vpaLabel: 'UPI ID',
      noQrTitle: 'QR હજી તૈયાર નથી',
      noQrBody: 'QR કોડ મેળવવા બેંક ચકાસણી પૂરી કરો.',
      noQrCta: 'ચકાસણી પૂરી કરો',
      offlineUsable: 'તમારો QR ઇન્ટરનેટ વગર પણ ચાલે છે.',
    },
    amount: {
      title: 'રકમ નાખો',
      generateQr: 'QR બનાવો',
      createLink: 'લિંક બનાવો',
      noteLabel: 'નોંધ',
      notePlaceholder: 'શા માટે? (વૈકલ્પિક)',
      tooLow: '{{min}} થી વધુ રકમ નાખો',
      limitExceeded: 'ચકાસણી પૂરી થાય ત્યાં સુધી રોજની મર્યાદા {{limit}} છે',
      upiCap: 'એક UPI પેમેન્ટમાં વધુમાં વધુ {{max}}',
    },
    dynamicQr: {
      title: 'પૈસા ભરવા સ્કેન કરો',
      waiting: 'પેમેન્ટની રાહ જોઈ રહ્યા છીએ…',
      waitingBody: 'ગ્રાહકને આ કોડ સ્કેન કરવા કહો.',
      expiresIn: '{{time}} માં સમાપ્ત',
      expiredTitle: 'QR સમાપ્ત થયો',
      expiredBody: 'આ કોડ હવે માન્ય નથી. નવો બનાવો.',
      newQr: 'નવો QR બનાવો',
      cancel: 'રદ કરો',
      checkingSlowly: 'હજી તપાસી રહ્યા છીએ. તમારું કનેક્શન ધીમું લાગે છે.',
      failedTitle: 'પેમેન્ટ નિષ્ફળ',
      failedBody: 'ગ્રાહકનું પેમેન્ટ થયું નથી. તેમને ફરી પ્રયાસ કરવા કહો.',
      offlineTitle: 'ઇન્ટરનેટ નથી',
      offlineBody: 'નક્કી રકમના QR માટે ઇન્ટરનેટ જરૂરી છે. તેના બદલે તમારો QR કોડ વાપરો.',
      useStaticQr: 'મારો QR કોડ વાપરો',
    },
    link: {
      title: 'પેમેન્ટ લિંક',
      createdTitle: 'લિંક તૈયાર',
      createdBody: 'આ ગ્રાહકને મોકલો. 24 કલાકમાં સમાપ્ત થશે.',
      copy: 'લિંક કોપી કરો',
      copied: 'લિંક કોપી થઈ',
      shareVia: 'લિંક શેર કરો',
      newLink: 'બીજી બનાવો',
      shareMessage: 'આ લિંક વાપરીને {{amount}} ભરો: {{url}}',
    },
    success: {
      title: 'પેમેન્ટ મળ્યું!',
      amountLabel: 'મળેલી રકમ',
      txnIdLabel: 'વ્યવહાર ID',
      timeLabel: 'સમય',
      payerLabel: 'ભરનાર',
      utrLabel: 'UPI સંદર્ભ',
      shareReceipt: 'રસીદ શેર કરો',
      newPayment: 'નવું પેમેન્ટ',
      done: 'થઈ ગયું',
      receiptMessage: 'પેમેન્ટ મળ્યું: {{time}} વાગ્યે {{amount}}. વ્યવહાર ID: {{id}}.',
    },
    audio: {
      received: '{{amount}} રૂપિયા મળ્યા',
      mutedHint: 'ઓડિયો પુષ્ટિ બંધ છે. સેટિંગમાં ચાલુ કરો.',
    },
  },
};

export default gu;
