import type { TranslationBundle } from './en';

/** Hindi (हिन्दी) — primary language for the Tier-2/3 merchant persona. */
export const hi: TranslationBundle = {
  common: {
    appName: 'MerchantOne',
    ok: 'ठीक है',
    cancel: 'रद्द करें',
    continue: 'आगे बढ़ें',
    back: 'पीछे',
    next: 'अगला',
    skip: 'छोड़ें',
    done: 'हो गया',
    retry: 'दोबारा कोशिश करें',
    save: 'सेव करें',
    close: 'बंद करें',
    share: 'शेयर करें',
    download: 'डाउनलोड करें',
    search: 'खोजें',
    viewAll: 'सभी देखें',
    today: 'आज',
    yesterday: 'कल',
    loading: 'लोड हो रहा है…',
    yes: 'हाँ',
    no: 'नहीं',
    optional: 'वैकल्पिक',
    verified: 'सत्यापित',
    verifying: 'सत्यापित हो रहा है…',
    edit: 'बदलें',
    remove: 'हटाएँ',
    confirm: 'पुष्टि करें',
    comingSoon: 'जल्द आ रहा है',
    comingSoonBody: 'यह हिस्सा तैयार किया जा रहा है।',
    months: {
      jan: 'जन',
      feb: 'फ़र',
      mar: 'मार्च',
      apr: 'अप्रैल',
      may: 'मई',
      jun: 'जून',
      jul: 'जुल',
      aug: 'अग',
      sep: 'सित',
      oct: 'अक्तू',
      nov: 'नव',
      dec: 'दिस',
    },
  },

  a11y: {
    back: 'पीछे जाएँ',
    close: 'बंद करें',
    notifications: 'सूचनाएँ',
    loading: 'सामग्री लोड हो रही है',
    amount: 'राशि {{amount}}',
    step: 'चरण {{current}} / {{total}}',
  },

  tabs: {
    home: 'होम',
    collect: 'पैसे लें',
    transactions: 'लेन-देन',
    settlements: 'सेटलमेंट',
    more: 'और',
  },

  network: {
    offlineTitle: 'आप ऑफ़लाइन हैं',
    offlineBanner: 'इंटरनेट नहीं है। सेव किया हुआ डेटा दिख रहा है।',
    offlineActionDisabled: 'इसके लिए इंटरनेट ज़रूरी है।',
    backOnline: 'इंटरनेट वापस आ गया',
  },

  errors: {
    title: 'कुछ गड़बड़ हो गई',
    network_error: 'सर्वर से संपर्क नहीं हो पा रहा। इंटरनेट जाँचकर दोबारा कोशिश करें।',
    timeout: 'बहुत समय लग रहा है। कृपया दोबारा कोशिश करें।',
    offline: 'आप ऑफ़लाइन हैं। इंटरनेट से जुड़कर दोबारा कोशिश करें।',
    unauthorized: 'आपका सेशन समाप्त हो गया। कृपया दोबारा लॉग इन करें।',
    forbidden: 'आपको यह करने की अनुमति नहीं है।',
    not_found: 'जो आप खोज रहे थे वह नहीं मिला।',
    validation_error: 'कृपया भरी गई जानकारी जाँच लें।',
    rate_limited: 'बहुत ज़्यादा कोशिशें। थोड़ी देर बाद प्रयास करें।',
    invalid_otp: 'यह OTP ग़लत है। जाँचकर दोबारा डालें।',
    otp_expired: 'यह OTP समाप्त हो गया। नया OTP मंगाएँ।',
    invalid_mobile: 'सही 10 अंकों का मोबाइल नंबर डालें।',
    kyc_incomplete: 'इस सुविधा के लिए अपना KYC पूरा करें।',
    kyc_rejected: 'आपका KYC स्वीकृत नहीं हुआ। कृपया जाँचकर दोबारा भेजें।',
    bank_verification_failed: 'यह बैंक खाता सत्यापित नहीं हो सका। जानकारी जाँचकर दोबारा कोशिश करें।',
    pan_verification_failed: 'यह PAN सत्यापित नहीं हो सका। नंबर जाँचकर दोबारा कोशिश करें।',
    already_refunded: 'इस लेन-देन का रिफ़ंड पहले ही हो चुका है।',
    refund_limit_exceeded: 'रिफ़ंड की राशि उपलब्ध राशि से ज़्यादा है।',
    payment_expired: 'यह पेमेंट रिक्वेस्ट समाप्त हो गई। नई बनाएँ।',
    server_error: 'हमारे सर्वर में दिक्कत है। कृपया थोड़ी देर में कोशिश करें।',
    unknown: 'कुछ गड़बड़ हो गई। कृपया दोबारा कोशिश करें।',
  },

  auth: {
    splash: {
      tagline: 'पेमेंट, अब आसान',
    },
    login: {
      title: 'स्वागत है',
      subtitle: 'अपना कारोबार चलाने के लिए मोबाइल नंबर से लॉग इन करें',
      mobileLabel: 'मोबाइल नंबर',
      mobilePlaceholder: '10 अंकों का मोबाइल नंबर',
      mobileRequired: 'अपना मोबाइल नंबर डालें',
      mobileInvalid: 'सही 10 अंकों का मोबाइल नंबर डालें',
      consent: 'मैं सेवा की शर्तें और गोपनीयता नीति स्वीकार करता/करती हूँ',
      consentRequired: 'आगे बढ़ने के लिए शर्तें स्वीकार करें',
      getOtp: 'OTP भेजें',
      secureNote: 'नंबर सत्यापित करने के लिए हम 6 अंकों का कोड भेजेंगे।',
    },
    otp: {
      title: 'अपना नंबर सत्यापित करें',
      subtitle: '{{mobile}} पर भेजा गया 6 अंकों का कोड डालें',
      otpRequired: '6 अंकों का कोड डालें',
      otpInvalid: 'कोड 6 अंकों का होना चाहिए',
      verify: 'सत्यापित करें',
      resend: 'कोड दोबारा भेजें',
      resendIn: '{{seconds}} सेकंड में दोबारा भेजें',
      changeNumber: 'नंबर बदलें',
      autoReadHint: 'अनुमति होने पर हम कोड अपने आप भर देंगे।',
      hintDev: 'डेमो मोड: {{otp}} डालें',
    },
  },

  kyc: {
    title: 'कारोबार का सत्यापन',
    stepOf: 'चरण {{current}} / {{total}}',
    saveAndExit: 'सेव करके बाहर निकलें',
    resumeTitle: 'सत्यापन जारी रखें',
    resumeBody: 'आप चरण {{step}} पर रुके थे। वहीं से आगे बढ़ें।',
    progress: {
      business: 'कारोबार',
      identity: 'पहचान',
      bank: 'बैंक',
      aadhaar: 'आधार',
    },
    business: {
      title: 'अपने कारोबार के बारे में बताएँ',
      subtitle: 'यही नाम आपके QR पर ग्राहकों को दिखेगा।',
      name: 'कारोबार का नाम',
      namePlaceholder: 'जैसे शर्मा जनरल स्टोर',
      nameRequired: 'कारोबार का नाम डालें',
      nameTooShort: 'नाम कम से कम 3 अक्षरों का हो',
      category: 'कारोबार की श्रेणी',
      categoryPlaceholder: 'श्रेणी चुनें',
      categoryRequired: 'अपने कारोबार की श्रेणी चुनें',
      categorySheetTitle: 'कारोबार की श्रेणी चुनें',
      addressLine1: 'दुकान / इमारत का पता',
      addressPlaceholder: 'दुकान नंबर, गली, इलाका',
      addressRequired: 'कारोबार का पता डालें',
      pincode: 'पिन कोड',
      pincodePlaceholder: '6 अंकों का पिन कोड',
      pincodeRequired: 'अपना पिन कोड डालें',
      pincodeInvalid: 'सही 6 अंकों का पिन कोड डालें',
      city: 'शहर',
      cityRequired: 'अपना शहर डालें',
      state: 'राज्य',
      stateRequired: 'अपना राज्य डालें',
      pincodeLookup: 'आपका इलाका खोज रहे हैं…',
    },
    identity: {
      title: 'पहचान की जानकारी',
      subtitle: 'पेमेंट लेने के लिए RBI द्वारा अनिवार्य।',
      pan: 'PAN नंबर',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'अपना PAN नंबर डालें',
      panInvalid: 'सही PAN डालें (जैसे ABCDE1234F)',
      panHelp: 'जैसा आपके PAN कार्ड पर छपा है।',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'सही 15 अक्षरों का GSTIN डालें',
      gstinHelp: 'GST वाले बिल चाहिए तो यह जोड़ें।',
    },
    bank: {
      title: 'पैसा कहाँ भेजें?',
      subtitle: 'आपकी कमाई यहीं आएगी, आम तौर पर अगले दिन।',
      accountNumber: 'खाता संख्या',
      accountNumberPlaceholder: 'बैंक खाता संख्या',
      accountNumberRequired: 'अपनी खाता संख्या डालें',
      accountNumberInvalid: 'खाता संख्या 9 से 18 अंकों की हो',
      confirmAccountNumber: 'खाता संख्या दोबारा डालें',
      accountMismatch: 'खाता संख्या मेल नहीं खा रही',
      ifsc: 'IFSC कोड',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'IFSC कोड डालें',
      ifscInvalid: 'सही IFSC डालें (जैसे HDFC0001234)',
      holderName: 'खाताधारक का नाम',
      holderNamePlaceholder: 'बैंक रिकॉर्ड के अनुसार नाम',
      holderNameRequired: 'खाताधारक का नाम डालें',
      verifyCta: 'खाता सत्यापित करें',
      verifying: 'आपका खाता सत्यापित हो रहा है…',
      verifyingBody: 'यह खाता आपका है, इसकी पुष्टि के लिए हम ₹1 भेज रहे हैं।',
      verifiedTitle: 'खाता सत्यापित हो गया',
      verifiedNameAtBank: 'बैंक में नाम: {{name}}',
      unlockNote: 'इस चरण के बाद आप सीमा के साथ पेमेंट लेना शुरू कर सकते हैं, जाँच पूरी होने तक।',
    },
    aadhaar: {
      title: 'आधार सत्यापन',
      subtitle: 'सभी सुविधाएँ खोलने का आख़िरी चरण।',
      numberLabel: 'आधार नंबर',
      numberPlaceholder: '12 अंकों का आधार नंबर',
      numberRequired: 'अपना आधार नंबर डालें',
      numberInvalid: 'आधार नंबर 12 अंकों का होना चाहिए',
      consent: 'मैं आधार eKYC से अपनी पहचान सत्यापित करने की सहमति देता/देती हूँ। मैं समझता/समझती हूँ कि मेरे आधार विवरण का उपयोग केवल इस सत्यापन के लिए होगा।',
      consentRequired: 'आगे बढ़ने के लिए आपकी सहमति ज़रूरी है',
      sendOtp: 'आधार OTP भेजें',
      otpLabel: 'आधार OTP',
      otpSentTo: 'आधार से जुड़े मोबाइल पर भेजा गया कोड डालें।',
      otpRequired: '6 अंकों का आधार OTP डालें',
      verifyCta: 'आधार सत्यापित करें',
      verifiedTitle: 'आधार सत्यापित हो गया',
      skipForNow: 'बाद में करें',
      privacyNote: 'हम आपका पूरा आधार नंबर कभी सेव नहीं करते।',
    },
    done: {
      title: 'सब तैयार है!',
      subtitle: 'आपकी जानकारी भेज दी गई है। आप अभी से पेमेंट लेना शुरू कर सकते हैं।',
      pendingTitle: 'सत्यापन चल रहा है',
      pendingSubtitle: 'हम आपकी जानकारी जाँच रहे हैं। इसमें आम तौर पर कुछ घंटे लगते हैं।',
      generateQr: 'मेरा QR बनाएँ',
      goHome: 'डैशबोर्ड पर जाएँ',
      vpaLabel: 'आपकी UPI ID',
      limitsNote: 'सत्यापन पूरा होने तक आप रोज़ {{limit}} तक ले सकते हैं।',
    },
    status: {
      not_started: 'KYC बाकी',
      in_progress: 'KYC अधूरा',
      pending_review: 'जाँच जारी',
      approved: 'सत्यापित',
      rejected: 'कार्रवाई ज़रूरी',
    },
    rejected: {
      title: 'हमें दोबारा देखना होगा',
      reasonLabel: 'कारण',
      retryCta: 'जानकारी अपडेट करें',
    },
    submitCta: 'सत्यापन के लिए भेजें',
    mcc: {
      grocery: 'किराना / जनरल स्टोर',
      restaurant: 'रेस्टोरेंट / कैफ़े',
      apparel: 'कपड़े और परिधान',
      electronics: 'इलेक्ट्रॉनिक्स और मोबाइल',
      pharmacy: 'दवा की दुकान / मेडिकल',
      salon: 'सैलून और ब्यूटी',
      hardware: 'हार्डवेयर और निर्माण सामग्री',
      services: 'पेशेवर सेवाएँ',
      education: 'शिक्षा और कोचिंग',
      transport: 'परिवहन और यात्रा',
      online: 'ऑनलाइन / D2C विक्रेता',
      other: 'अन्य',
    },
  },

  home: {
    greeting: 'नमस्ते',
    summary: {
      title: 'आज की कमाई',
      collected: 'आज मिला',
      txnCount: '{{count}} पेमेंट',
      txnCount_plural: '{{count}} पेमेंट',
      pendingSettlement: 'सेटलमेंट बाकी',
      settlementHint: 'आपके बैंक खाते में आएगा',
    },
    collectCta: 'पैसे लें',
    quickActions: {
      title: 'तुरंत करें',
      myQr: 'मेरा QR',
      paymentLink: 'पेमेंट लिंक',
      reports: 'रिपोर्ट',
      refund: 'रिफ़ंड',
    },
    recent: {
      title: 'हाल के पेमेंट',
      emptyTitle: 'अभी कोई पेमेंट नहीं',
      emptyBody: 'पहला पेमेंट पाने के लिए ग्राहक को अपना QR दिखाएँ।',
      emptyCta: 'मेरा QR दिखाएँ',
    },
    kycNudge: {
      title: 'सत्यापन पूरा करें',
      body: 'सीमा हटाने के लिए अपनी जानकारी पूरी करें।',
      cta: 'आगे बढ़ें',
    },
    error: {
      title: 'डैशबोर्ड लोड नहीं हो सका',
      body: 'इंटरनेट जाँचकर दोबारा कोशिश करें।',
    },
  },

  notifications: {
    title: 'सूचनाएँ',
    emptyTitle: 'कोई सूचना नहीं',
    emptyBody: 'पेमेंट और सेटलमेंट की जानकारी यहाँ दिखेगी।',
  },

  transactions: {
    title: 'लेन-देन',
    status: {
      success: 'मिल गया',
      pending: 'बाकी',
      failed: 'विफल',
      refunded: 'वापस किया',
      partially_refunded: 'आंशिक वापसी',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI ऐप',
      payment_link: 'पेमेंट लिंक',
      card: 'कार्ड',
      netbanking: 'नेट बैंकिंग',
      wallet: 'वॉलेट',
    },
    filters: {
      all: 'सभी',
      success: 'मिल गया',
      pending: 'बाकी',
      failed: 'विफल',
      refunded: 'वापस किया',
    },
    searchPlaceholder: 'रकम, UTR या भेजने वाला खोजें',
    emptyTitle: 'कोई लेन-देन नहीं',
    emptyBody: 'आपको मिलने वाले पेमेंट यहाँ दिखेंगे।',
    emptyFilteredTitle: 'कुछ नहीं मिला',
    emptyFilteredBody: 'दूसरा फ़िल्टर या तारीख़ चुनकर देखें।',
    clearFilters: 'फ़िल्टर हटाएँ',
    resultCount: '{{count}} लेन-देन',
    resultCount_plural: '{{count}} लेन-देन',
    loadingMore: 'और लोड हो रहा है…',
    endOfList: 'बस इतना ही',
    detail: {
      title: 'पेमेंट का विवरण',
      amountLabel: 'रकम',
      statusLabel: 'स्थिति',
      modeLabel: 'किससे मिला',
      txnIdLabel: 'लेन-देन ID',
      utrLabel: 'UTR / RRN',
      timeLabel: 'तारीख़ और समय',
      payerLabel: 'भेजने वाला',
      noteLabel: 'टिप्पणी',
      breakdownTitle: 'हिसाब',
      grossLabel: 'मिली रकम',
      feeLabel: 'शुल्क (MDR)',
      netLabel: 'आपको मिलेगा',
      noFee: 'कोई शुल्क नहीं',
      settlementTitle: 'सेटलमेंट',
      settlementPending: 'आपके बैंक खाते में भेजा जाएगा',
      settlementDone: 'आपके बैंक खाते में भेज दिया गया',
      viewSettlement: 'सेटलमेंट देखें',
      refundedLabel: 'अब तक वापस किया',
      actions: 'कार्रवाई',
      refund: 'रिफ़ंड',
      shareReceipt: 'रसीद शेयर करें',
      raiseDispute: 'शिकायत दर्ज करें',
      reportIssue: 'समस्या बताएँ',
      notRefundable: 'इस पेमेंट का रिफ़ंड नहीं हो सकता',
      receiptMessage: '{{time}} पर {{amount}} मिले। लेन-देन ID: {{id}}.',
    },
  },

  refund: {
    title: 'रिफ़ंड करें',
    originalLabel: 'मूल पेमेंट',
    refundableLabel: 'रिफ़ंड के लिए उपलब्ध',
    alreadyRefunded: '{{amount}} पहले ही वापस किया गया',
    typeFull: 'पूरा रिफ़ंड',
    typePartial: 'आंशिक रिफ़ंड',
    fullBody: 'पूरी रकम वापस करें',
    partialBody: 'रकम का कुछ हिस्सा वापस करें',
    amountLabel: 'रिफ़ंड की रकम',
    reasonLabel: 'कारण',
    reasonPlaceholder: 'रिफ़ंड क्यों? (वैकल्पिक)',
    exceedsRefundable: '{{max}} से ज़्यादा रिफ़ंड नहीं हो सकता',
    tooLow: '{{min}} से ज़्यादा रकम डालें',
    confirmCta: '{{amount}} रिफ़ंड करें',
    reauthReason: '{{amount}} के रिफ़ंड की पुष्टि करें',
    processingTitle: 'रिफ़ंड हो रहा है…',
    processingBody: 'कृपया ऐप खुला रखें।',
    successTitle: 'रिफ़ंड शुरू हो गया',
    successBody: '{{amount}} ग्राहक को वापस भेजा जा रहा है। आम तौर पर 3-5 कार्य दिवस लगते हैं।',
    successDone: 'हो गया',
    offlineTitle: 'इंटरनेट नहीं है',
    offlineBody: 'रिफ़ंड के लिए इंटरनेट ज़रूरी है।',
    notEligibleTitle: 'रिफ़ंड नहीं हो सकता',
    notEligibleBody: 'सिर्फ़ सफल पेमेंट का रिफ़ंड हो सकता है।',
  },

  appLock: {
    title: 'पुष्टि करें कि यह आप हैं',
    biometricPrompt: 'पुष्टि के लिए फ़िंगरप्रिंट या चेहरा इस्तेमाल करें',
    biometricFailed: 'पुष्टि नहीं हो सकी। इसके बजाय PIN डालें।',
    usePin: 'PIN इस्तेमाल करें',
    pinIncorrect: 'ग़लत PIN। {{count}} कोशिशें बची हैं।',
    lockedOut: 'बहुत ग़लत कोशिशें। ऐप बंद करके दोबारा खोलें।',
    setupTitle: 'ऐप PIN बनाएँ',
    setupBody: 'रिफ़ंड और अन्य ज़रूरी कामों की मंज़ूरी के लिए {{min}} अंकों का PIN चुनें।',
    confirmTitle: 'PIN दोबारा डालें',
    pinMismatch: 'PIN मेल नहीं खाए। दोबारा कोशिश करें।',
    pinTooShort: 'PIN कम से कम {{min}} अंकों का हो',
  },

  reports: {
    title: 'रिपोर्ट',
    chartTitle: 'बिक्री का रुझान',
    chartHint: 'किसी दिन का कुल देखने के लिए बार पर टैप करें',
    chartA11y: 'चुनी गई अवधि की बिक्री का चार्ट',
    statsTitle: 'सारांश',
    totalSales: 'कुल बिक्री',
    txnCount: 'पेमेंट',
    avgTicket: 'औसत बिक्री',
    topMode: 'सबसे ज़्यादा इस्तेमाल',
    bestDay: 'सबसे अच्छा दिन',
    tradingDays: 'बिक्री वाले दिन',
    avgPerTradingDay: 'बिक्री वाले दिन का औसत',
    emptyTitle: 'इस अवधि में कोई बिक्री नहीं',
    emptyBody: 'दूसरी तारीख़ चुनें, या पेमेंट लेना शुरू करें।',
    emptyCta: 'पैसे लें',
    errorTitle: 'रिपोर्ट लोड नहीं हो सकी',
    export: {
      cta: 'रिपोर्ट एक्सपोर्ट करें',
      preparing: 'एक्सपोर्ट तैयार हो रहा है…',
      failed: 'एक्सपोर्ट नहीं बन सका। कृपया दोबारा कोशिश करें।',
      fileName: 'बिक्री रिपोर्ट',
      formatNote: 'CSV फ़ाइल के रूप में सेव होती है, जो Excel और Google Sheets में खुलती है।',
      colDate: 'तारीख़',
      colSales: 'बिक्री (INR)',
      colCount: 'पेमेंट',
      totalsLabel: 'कुल',
      periodLabel: 'अवधि',
      generatedLabel: 'बनाया गया',
    },
    gst: {
      title: 'GST',
      summaryCta: 'GST सारांश एक्सपोर्ट करें',
      summaryBody: 'आपके GSTIN के साथ अवधि की बिक्री का सारांश, आपके अकाउंटेंट की GST फ़ाइलिंग के लिए।',
      noGstinTitle: 'GSTIN दर्ज नहीं है',
      noGstinBody: 'GST एक्सपोर्ट में शामिल करने के लिए अपनी प्रोफ़ाइल में GSTIN जोड़ें।',
      invoiceNote: 'हर पेमेंट के टैक्स इनवॉइस के लिए ग्राहक की जानकारी और आइटम की सूची ज़रूरी है, इसलिए वे इनवॉइसिंग सुविधा से बनते हैं, पेमेंट रिकॉर्ड से नहीं।',
      gstinLabel: 'GSTIN',
      fileName: 'GST सारांश',
      colField: 'विवरण',
      colValue: 'मान',
      rowBusiness: 'कारोबार का नाम',
      rowGstin: 'GSTIN',
      rowPeriodFrom: 'अवधि से',
      rowPeriodTo: 'अवधि तक',
      rowTotalSales: 'कुल बिक्री (INR)',
      rowTxnCount: 'पेमेंट की संख्या',
      rowNote: 'टिप्पणी',
      noteValue: 'मिले पेमेंट का सारांश। यह टैक्स इनवॉइस नहीं है।',
    },
  },

  more: {
    title: 'और',
    reports: 'रिपोर्ट',
    reportsBody: 'बिक्री के रुझान और एक्सपोर्ट',
    profile: 'कारोबार प्रोफ़ाइल',
    profileBody: 'आपकी जानकारी, बैंक खाता और KYC',
    staff: 'स्टाफ़',
    staffBody: 'पेमेंट लेने वाले लोग जोड़ें',
    support: 'मदद और सहायता',
    supportBody: 'सवाल-जवाब, टिकट बनाएँ, संपर्क करें',
    settings: 'सेटिंग',
    settingsBody: 'भाषा, आवाज़, सूचनाएँ, ऐप लॉक',
  },

  profile: {
    title: 'कारोबार प्रोफ़ाइल',
    businessTitle: 'कारोबार की जानकारी',
    nameLabel: 'कारोबार का नाम',
    categoryLabel: 'कारोबार की श्रेणी',
    addressLabel: 'पता',
    gstinLabel: 'GSTIN',
    gstinEmpty: 'नहीं जोड़ा',
    panLabel: 'PAN',
    mobileLabel: 'मोबाइल नंबर',
    vpaLabel: 'आपकी UPI ID',
    kycTitle: 'सत्यापन',
    kycPendingBody: 'हम आपकी जानकारी जाँच रहे हैं।',
    kycRejectedBody: 'आपके सत्यापन पर ध्यान देना ज़रूरी है। कृपया जानकारी अपडेट करें।',
    bankTitle: 'सेटलमेंट खाता',
    bankAccountLabel: 'खाता',
    bankIfscLabel: 'IFSC',
    bankHolderLabel: 'खाताधारक',
    bankChangeCta: 'सेटलमेंट खाता बदलें',
    bankChangeWarning: 'आगे का सारा सेटलमेंट नए खाते में जाएगा। हम ₹1 भेजकर उसकी पुष्टि करते हैं।',
    editCta: 'जानकारी बदलें',
    editTitle: 'कारोबार की जानकारी बदलें',
    saveCta: 'बदलाव सेव करें',
    saved: 'बदलाव सेव हो गए',
    bankEditTitle: 'सेटलमेंट खाता बदलें',
    bankReauthReason: 'सेटलमेंट खाता बदलने की पुष्टि करें',
    bankSubmitCta: 'सत्यापित करके सेव करें',
    bankVerifying: 'आपका खाता सत्यापित हो रहा है…',
    bankSaved: 'सेटलमेंट खाता अपडेट हो गया',
    readOnlyNote: 'PAN और मोबाइल नंबर यहाँ नहीं बदले जा सकते। ग़लत हों तो सहायता से संपर्क करें।',
    offlineNote: 'प्रोफ़ाइल बदलने के लिए इंटरनेट ज़रूरी है।',
  },

  staff: {
    title: 'स्टाफ़',
    subtitle: 'वे लोग जो आपके कारोबार के लिए पैसे ले सकते हैं',
    addCta: 'स्टाफ़ जोड़ें',
    emptyTitle: 'कोई स्टाफ़ नहीं',
    emptyBody: 'मैनेजर या कैशियर जोड़ें ताकि वे आपकी ओर से पैसे ले सकें।',
    errorTitle: 'स्टाफ़ लोड नहीं हो सका',
    countLabel: '{{count}} व्यक्ति',
    countLabel_plural: '{{count}} लोग',
    roles: {
      manager: 'मैनेजर',
      cashier: 'कैशियर',
    },
    roleHelp: {
      manager: 'पैसे ले सकते हैं, रिपोर्ट देख सकते हैं और रिफ़ंड कर सकते हैं',
      cashier: 'सिर्फ़ पैसे ले सकते हैं',
    },
    addTitle: 'स्टाफ़ जोड़ें',
    nameLabel: 'पूरा नाम',
    namePlaceholder: 'जिस नाम से जाने जाते हैं',
    nameRequired: 'उनका नाम डालें',
    mobileLabel: 'मोबाइल नंबर',
    mobileRequired: 'उनका मोबाइल नंबर डालें',
    mobileInvalid: 'सही 10 अंकों का मोबाइल नंबर डालें',
    mobileDuplicate: 'यह मोबाइल नंबर पहले ही जोड़ा गया है',
    roleLabel: 'भूमिका',
    addSubmit: 'जोड़ें',
    added: '{{name}} जोड़ लिया',
    editRoleTitle: '{{name}} की भूमिका बदलें',
    roleSaved: 'भूमिका अपडेट हो गई',
    removeCta: 'हटाएँ',
    removeConfirmTitle: '{{name}} को हटाएँ?',
    removeConfirmBody: 'वे आपके लिए पैसे नहीं ले पाएँगे।',
    removed: '{{name}} हटा दिया',
    offlineNote: 'स्टाफ़ जोड़ने या हटाने के लिए इंटरनेट ज़रूरी है।',
  },

  settings: {
    title: 'सेटिंग',
    languageTitle: 'भाषा',
    languageBody: 'ऐप के लिए और पेमेंट की घोषणा के लिए',
    audioTitle: 'पेमेंट की घोषणा',
    audioEnabledLabel: 'पेमेंट की आवाज़ में घोषणा करें',
    audioEnabledBody: 'पेमेंट आने पर रकम सुनें, स्क्रीन देखने की ज़रूरत नहीं',
    audioLanguageLabel: 'घोषणा की भाषा',
    audioVolumeNote: 'घोषणा की आवाज़ आपके फ़ोन के मीडिया वॉल्यूम के अनुसार होती है।',
    notificationsTitle: 'सूचनाएँ',
    pushLabel: 'ऐप सूचनाएँ',
    smsLabel: 'SMS',
    whatsappLabel: 'WhatsApp',
    securityTitle: 'सुरक्षा',
    pinLabel: 'ऐप PIN',
    pinSetBody: 'रिफ़ंड और अन्य ज़रूरी कामों की मंज़ूरी के लिए',
    pinNotSetBody: 'अभी सेट नहीं है',
    pinSetCta: 'PIN सेट करें',
    pinChangeCta: 'बदलें',
    pinChanged: 'PIN अपडेट हो गया',
    pinReauthReason: 'PIN बदलने से पहले पुष्टि करें कि यह आप हैं',
    biometricLabel: 'फ़िंगरप्रिंट या चेहरा',
    biometricAvailableBody: 'जहाँ संभव हो, PIN के बजाय इस्तेमाल होता है',
    biometricUnavailableBody: 'इस फ़ोन में सेट नहीं है',
    themeTitle: 'रूप',
    themeLightOnly: 'ऐप अभी सिर्फ़ हल्की थीम इस्तेमाल करता है।',
    aboutTitle: 'ऐप के बारे में',
    versionLabel: 'ऐप वर्शन',
    logoutCta: 'लॉग आउट',
    logoutConfirmTitle: 'लॉग आउट करें?',
    logoutConfirmBody: 'दोबारा लॉग इन करने के लिए मोबाइल नंबर और OTP लगेगा।',
    saveFailed: 'यह बदलाव सेव नहीं हो सका। कृपया दोबारा कोशिश करें।',
  },

  support: {
    title: 'मदद और सहायता',
    searchPlaceholder: 'मदद खोजें',
    faqTitle: 'आम सवाल',
    faqEmptyTitle: 'कोई मिलता सवाल नहीं',
    faqEmptyBody: 'दूसरे शब्द आज़माएँ, या टिकट बनाएँ और हम मदद करेंगे।',
    contactTitle: 'हमसे संपर्क करें',
    callCta: 'सहायता को कॉल करें',
    callBody: 'रोज़, सुबह 9 से रात 9 बजे',
    whatsappCta: 'WhatsApp पर बात करें',
    whatsappBody: 'आम तौर पर एक घंटे में जवाब',
    ticketsTitle: 'आपके टिकट',
    ticketsEmptyTitle: 'अभी कोई टिकट नहीं',
    ticketsEmptyBody: 'टिकट बनाएँ और हम आपसे संपर्क करेंगे।',
    raiseCta: 'टिकट बनाएँ',
    ticketStatus: {
      open: 'खुला',
      in_progress: 'चल रहा है',
      resolved: 'हल हो गया',
      closed: 'बंद',
    },
    raiseTitle: 'टिकट बनाएँ',
    subjectLabel: 'यह किस बारे में है?',
    subjectPlaceholder: 'छोटा सारांश',
    subjectRequired: 'छोटा सारांश डालें',
    bodyLabel: 'और बताएँ',
    bodyPlaceholder: 'क्या हुआ? हो सके तो रकम या लेन-देन ID भी लिखें।',
    bodyRequired: 'कृपया समस्या बताएँ',
    raiseSubmit: 'भेजें',
    raised: 'टिकट बन गया। हम आपसे संपर्क करेंगे।',
    offlineNote: 'टिकट बनाने के लिए इंटरनेट ज़रूरी है।',
    contactFailed: 'यह आपके फ़ोन पर खुल नहीं सका। आप {{value}} पर कॉल कर सकते हैं।',
    grievance: {
      title: 'शिकायत आगे बढ़ाएँ',
      body: 'अगर आपकी समस्या हल न हो तो आप उसे आगे बढ़ा सकते हैं। हर स्तर की जवाब देने की समय-सीमा है।',
      level1Title: 'स्तर 1 — ग्राहक सहायता',
      level1Body: 'ऊपर टिकट बनाएँ। हम 24 घंटे में जवाब देते हैं।',
      level2Title: 'स्तर 2 — नोडल अधिकारी',
      level2Body: '7 दिन में हल न हो तो हमारे नोडल अधिकारी को लिखें।',
      level3Title: 'स्तर 3 — RBI ओम्बड्समैन',
      level3Body: '30 दिन में हल न हो तो आप डिजिटल लेन-देन के लिए RBI ओम्बड्समैन से संपर्क कर सकते हैं।',
      officerLabel: 'शिकायत अधिकारी',
      emailLabel: 'ईमेल',
      phoneLabel: 'फ़ोन',
      rbiPortalCta: 'RBI शिकायत पोर्टल खोलें',
      placeholderNote: 'ये संपर्क विवरण अस्थायी हैं। रिलीज़ से पहले अपने पंजीकृत शिकायत अधिकारी की जानकारी डालें।',
    },
    faq: {
      q1: 'मेरा पैसा कब मिलेगा?',
      a1: 'आज मिले पेमेंट अगले कार्य दिवस आपके बैंक खाते में भेजे जाते हैं। आप उन्हें सेटलमेंट में देख सकते हैं। पैसा जल्दी चाहिए तो बाकी बैच पर "अभी सेटल करें" इस्तेमाल करें — इसका छोटा शुल्क लगता है।',
      q2: 'ग्राहक ने पैसे भेजे पर मुझे घोषणा नहीं सुनाई दी। क्या करूँ?',
      a2: 'लेन-देन खोलकर देखें कि पेमेंट सूची में है या नहीं। अगर है, तो पैसा आपका है, चाहे घोषणा न बजी हो। सेटिंग में घोषणा चालू है और फ़ोन साइलेंट पर नहीं है, यह जाँच लें।',
      q3: 'ग्राहक को पैसे कैसे वापस करूँ?',
      a3: 'लेन-देन खोलें, पेमेंट पर टैप करें, फिर रिफ़ंड पर टैप करें। आप पूरी रकम या उसका हिस्सा वापस कर सकते हैं। पुष्टि के लिए ऐप PIN या फ़िंगरप्रिंट माँगा जाएगा।',
      q4: 'मैं कितना ले सकता हूँ, इस पर सीमा क्यों है?',
      a4: 'सत्यापन पूरा होने तक आप रोज़ एक सीमा तक ले सकते हैं। सीमा हटाने के लिए कारोबार प्रोफ़ाइल से KYC पूरा करें।',
      q5: 'क्या कोई और मेरे लिए पैसे ले सकता है?',
      a5: 'हाँ। उन्हें स्टाफ़ में जोड़ें। कैशियर सिर्फ़ पैसे ले सकता है; मैनेजर रिपोर्ट भी देख सकता है और रिफ़ंड भी कर सकता है।',
      q6: 'जिस बैंक खाते में पैसा आता है, उसे कैसे बदलूँ?',
      a6: 'कारोबार प्रोफ़ाइल में जाकर "सेटलमेंट खाता बदलें" पर टैप करें। सुरक्षा के लिए आपका PIN या फ़िंगरप्रिंट लगेगा, और हम नए खाते की पुष्टि ₹1 भेजकर करते हैं।',
    },
  },

  dateRange: {
    label: 'तारीख़ की अवधि',
    all: 'सारा समय',
    today: 'आज',
    yesterday: 'कल',
    last7: 'पिछले 7 दिन',
    last30: 'पिछले 30 दिन',
    thisMonth: 'इस महीने',
    custom: 'अपनी अवधि',
    from: 'से',
    to: 'तक',
  },

  settlements: {
    title: 'सेटलमेंट',
    status: {
      pending: 'बाकी',
      processing: 'चल रहा है',
      settled: 'जमा हो गया',
      failed: 'विफल',
    },
    tabs: {
      pending: 'बाकी',
      settled: 'जमा हो गया',
    },
    batchLabel: '{{count}} पेमेंट का बैच',
    batchLabel_plural: '{{count}} पेमेंट का बैच',
    utrLabel: 'UTR',
    expectedLabel: 'आपके बैंक खाते में आने वाला',
    creditedLabel: 'आपके बैंक खाते में जमा',
    emptyPendingTitle: 'कुछ बाकी नहीं',
    emptyPendingBody: 'आज मिले पेमेंट कल आपके बैंक खाते में भेजे जाएँगे।',
    emptySettledTitle: 'अभी कोई सेटलमेंट नहीं',
    emptySettledBody: 'पैसा बैंक खाते में पहुँचने पर UTR के साथ यहाँ दिखेगा।',
    errorTitle: 'सेटलमेंट लोड नहीं हो सके',
    t1Note: 'पैसा अगले कार्य दिवस आपके बैंक खाते में पहुँचता है।',
    detail: {
      title: 'सेटलमेंट का विवरण',
      breakdownTitle: 'हिसाब',
      grossLabel: 'कुल मिला',
      feeLabel: 'शुल्क',
      netLabel: 'बैंक में जमा',
      bankTitle: 'बैंक खाता',
      accountLabel: 'खाता',
      ifscLabel: 'IFSC',
      utrLabel: 'UTR / रेफ़रेंस',
      createdLabel: 'बैच बना',
      settledLabel: 'जमा हुआ',
      txnTitle: 'इस बैच के पेमेंट',
      txnCount: '{{count}} पेमेंट',
      txnCount_plural: '{{count}} पेमेंट',
      reconcileNote: 'नीचे के सभी पेमेंट मिलाकर कुल रकम बनती है।',
      noTxnTitle: 'कोई पेमेंट सूची नहीं',
      noTxnBody: 'इस बैच के अलग-अलग पेमेंट उपलब्ध नहीं हैं।',
    },
    statement: {
      download: 'स्टेटमेंट डाउनलोड करें',
      preparing: 'स्टेटमेंट तैयार हो रहा है…',
      failed: 'स्टेटमेंट नहीं बन सका। कृपया दोबारा कोशिश करें।',
      fileName: 'सेटलमेंट स्टेटमेंट',
      colDate: 'तारीख़',
      colTime: 'समय',
      colTxnId: 'लेन-देन ID',
      colUtr: 'UTR',
      colMode: 'माध्यम',
      colStatus: 'स्थिति',
      colGross: 'रकम (INR)',
      colFee: 'शुल्क (INR)',
      colNet: 'शुद्ध (INR)',
      totalsLabel: 'कुल',
      formatNote: 'CSV फ़ाइल के रूप में सेव होता है, जो Excel और Google Sheets में खुलती है।',
    },
    instant: {
      cta: 'अभी सेटल करें',
      sheetTitle: 'तुरंत सेटल करें',
      sheetBody: 'कल का इंतज़ार किए बिना यह पैसा कुछ मिनटों में अपने बैंक खाते में पाएँ।',
      netLabel: 'सेटलमेंट की रकम',
      feeLabel: 'तुरंत सेटलमेंट शुल्क ({{percent}}%)',
      gstLabel: 'शुल्क पर GST',
      payoutLabel: 'आपको मिलेगा',
      confirmCta: '{{amount}} अभी सेटल करें',
      processing: 'सेटल हो रहा है…',
      successTitle: 'पैसा भेजा जा रहा है',
      successBody: '{{amount}} आपके बैंक खाते में जमा हो रहा है। आम तौर पर कुछ मिनटों में पहुँच जाता है।',
      ineligible: {
        already_settled: 'यह बैच पहले ही सेटल हो चुका है।',
        below_minimum: 'तुरंत सेटलमेंट के लिए कम से कम {{min}} चाहिए।',
        failed_batch: 'यह बैच विफल हुआ, इसे तुरंत सेटल नहीं किया जा सकता।',
      },
      offlineBody: 'तुरंत सेटलमेंट के लिए इंटरनेट ज़रूरी है।',
    },
  },

  collect: {
    title: 'पैसे लें',
    subtitle: 'आप पैसे कैसे लेना चाहते हैं?',
    modes: {
      staticQr: 'मेरा QR कोड',
      staticQrBody: 'किसी भी रकम के लिए एक कोड। दिखाएँ या छपवाएँ।',
      dynamicQr: 'रकम डालें',
      dynamicQrBody: 'तय रकम के लिए QR बनाएँ।',
      paymentLink: 'पेमेंट लिंक',
      paymentLinkBody: 'WhatsApp या SMS पर लिंक भेजें।',
    },
    staticQr: {
      title: 'मेरा QR कोड',
      instruction: 'ग्राहक से कहें कि स्कैन करके कोई भी रकम भेजें।',
      vpaLabel: 'UPI ID',
      noQrTitle: 'QR अभी तैयार नहीं',
      noQrBody: 'QR कोड पाने के लिए बैंक सत्यापन पूरा करें।',
      noQrCta: 'सत्यापन पूरा करें',
      offlineUsable: 'आपका QR बिना इंटरनेट भी चलता है।',
    },
    amount: {
      title: 'रकम डालें',
      generateQr: 'QR बनाएँ',
      createLink: 'लिंक बनाएँ',
      noteLabel: 'टिप्पणी',
      notePlaceholder: 'किस लिए? (वैकल्पिक)',
      tooLow: '{{min}} से ज़्यादा रकम डालें',
      limitExceeded: 'सत्यापन पूरा होने तक रोज़ की सीमा {{limit}} है',
      upiCap: 'एक UPI पेमेंट में अधिकतम {{max}}',
    },
    dynamicQr: {
      title: 'भुगतान के लिए स्कैन करें',
      waiting: 'पेमेंट का इंतज़ार…',
      waitingBody: 'ग्राहक से यह कोड स्कैन करने को कहें।',
      expiresIn: '{{time}} में समाप्त',
      expiredTitle: 'QR समाप्त हो गया',
      expiredBody: 'यह कोड अब मान्य नहीं है। नया बनाएँ।',
      newQr: 'नया QR बनाएँ',
      cancel: 'रद्द करें',
      checkingSlowly: 'जाँच जारी है। आपका इंटरनेट धीमा लग रहा है।',
      failedTitle: 'पेमेंट विफल',
      failedBody: 'ग्राहक का पेमेंट नहीं हुआ। उनसे दोबारा कोशिश करने को कहें।',
      offlineTitle: 'इंटरनेट नहीं है',
      offlineBody: 'तय रकम वाले QR के लिए इंटरनेट ज़रूरी है। इसके बजाय अपना QR कोड दिखाएँ।',
      useStaticQr: 'मेरा QR कोड दिखाएँ',
    },
    link: {
      title: 'पेमेंट लिंक',
      createdTitle: 'लिंक तैयार है',
      createdBody: 'यह ग्राहक को भेजें। यह 24 घंटे में समाप्त हो जाएगा।',
      copy: 'लिंक कॉपी करें',
      copied: 'लिंक कॉपी हो गया',
      shareVia: 'लिंक शेयर करें',
      newLink: 'एक और बनाएँ',
      shareMessage: 'कृपया इस लिंक से {{amount}} का भुगतान करें: {{url}}',
    },
    success: {
      title: 'पेमेंट मिल गया!',
      amountLabel: 'मिली रकम',
      txnIdLabel: 'लेन-देन ID',
      timeLabel: 'समय',
      payerLabel: 'भेजने वाला',
      utrLabel: 'UPI रेफ़रेंस',
      shareReceipt: 'रसीद शेयर करें',
      newPayment: 'नया पेमेंट',
      done: 'हो गया',
      receiptMessage: 'पेमेंट मिला: {{time}} पर {{amount}}. लेन-देन ID: {{id}}.',
    },
    audio: {
      received: '{{amount}} रुपये मिले',
      mutedHint: 'आवाज़ की पुष्टि बंद है। सेटिंग में चालू करें।',
    },
  },
};

export default hi;
