import type { TranslationBundle } from './en';

/** Hindi (हिन्दी) — primary language for the Tier-2/3 merchant persona. */
export const hi: TranslationBundle = {
  common: {
    appName: 'MerchantOne',
    ok: 'ठीक है',
    cancel: 'रद्द करें',
    continue: 'आगे बढ़ें',
    back: 'पीछे',
    next: 'अगला',
    skip: 'छोड़ें',
    done: 'हो गया',
    retry: 'दोबारा कोशिश करें',
    save: 'सेव करें',
    close: 'बंद करें',
    share: 'शेयर करें',
    download: 'डाउनलोड करें',
    search: 'खोजें',
    viewAll: 'सभी देखें',
    today: 'आज',
    yesterday: 'कल',
    loading: 'लोड हो रहा है…',
    yes: 'हाँ',
    no: 'नहीं',
    optional: 'वैकल्पिक',
    verified: 'सत्यापित',
    verifying: 'सत्यापित हो रहा है…',
    edit: 'बदलें',
    remove: 'हटाएँ',
    confirm: 'पुष्टि करें',
    comingSoon: 'जल्द आ रहा है',
    comingSoonBody: 'यह हिस्सा तैयार किया जा रहा है।',
    months: {
      jan: 'जन',
      feb: 'फ़र',
      mar: 'मार्च',
      apr: 'अप्रैल',
      may: 'मई',
      jun: 'जून',
      jul: 'जुल',
      aug: 'अग',
      sep: 'सित',
      oct: 'अक्तू',
      nov: 'नव',
      dec: 'दिस',
    },
  },

  a11y: {
    back: 'पीछे जाएँ',
    close: 'बंद करें',
    notifications: 'सूचनाएँ',
    loading: 'सामग्री लोड हो रही है',
    amount: 'राशि {{amount}}',
    step: 'चरण {{current}} / {{total}}',
  },

  tabs: {
    home: 'होम',
    collect: 'पैसे लें',
    transactions: 'लेन-देन',
    settlements: 'सेटलमेंट',
    more: 'और',
  },

  network: {
    offlineTitle: 'आप ऑफ़लाइन हैं',
    offlineBanner: 'इंटरनेट नहीं है। सेव किया हुआ डेटा दिख रहा है।',
    offlineActionDisabled: 'इसके लिए इंटरनेट ज़रूरी है।',
    backOnline: 'इंटरनेट वापस आ गया',
  },

  errors: {
    title: 'कुछ गड़बड़ हो गई',
    network_error: 'सर्वर से संपर्क नहीं हो पा रहा। इंटरनेट जाँचकर दोबारा कोशिश करें।',
    timeout: 'बहुत समय लग रहा है। कृपया दोबारा कोशिश करें।',
    offline: 'आप ऑफ़लाइन हैं। इंटरनेट से जुड़कर दोबारा कोशिश करें।',
    unauthorized: 'आपका सेशन समाप्त हो गया। कृपया दोबारा लॉग इन करें।',
    forbidden: 'आपको यह करने की अनुमति नहीं है।',
    not_found: 'जो आप खोज रहे थे वह नहीं मिला।',
    validation_error: 'कृपया भरी गई जानकारी जाँच लें।',
    rate_limited: 'बहुत ज़्यादा कोशिशें। थोड़ी देर बाद प्रयास करें।',
    invalid_otp: 'यह OTP ग़लत है। जाँचकर दोबारा डालें।',
    otp_expired: 'यह OTP समाप्त हो गया। नया OTP मंगाएँ।',
    invalid_mobile: 'सही 10 अंकों का मोबाइल नंबर डालें।',
    kyc_incomplete: 'इस सुविधा के लिए अपना KYC पूरा करें।',
    kyc_rejected: 'आपका KYC स्वीकृत नहीं हुआ। कृपया जाँचकर दोबारा भेजें।',
    bank_verification_failed: 'यह बैंक खाता सत्यापित नहीं हो सका। जानकारी जाँचकर दोबारा कोशिश करें।',
    pan_verification_failed: 'यह PAN सत्यापित नहीं हो सका। नंबर जाँचकर दोबारा कोशिश करें।',
    already_refunded: 'इस लेन-देन का रिफ़ंड पहले ही हो चुका है।',
    refund_limit_exceeded: 'रिफ़ंड की राशि उपलब्ध राशि से ज़्यादा है।',
    payment_expired: 'यह पेमेंट रिक्वेस्ट समाप्त हो गई। नई बनाएँ।',
    server_error: 'हमारे सर्वर में दिक्कत है। कृपया थोड़ी देर में कोशिश करें।',
    unknown: 'कुछ गड़बड़ हो गई। कृपया दोबारा कोशिश करें।',
  },

  auth: {
    splash: {
      tagline: 'पेमेंट, अब आसान',
    },
    login: {
      title: 'स्वागत है',
      subtitle: 'अपना कारोबार चलाने के लिए मोबाइल नंबर से लॉग इन करें',
      mobileLabel: 'मोबाइल नंबर',
      mobilePlaceholder: '10 अंकों का मोबाइल नंबर',
      mobileRequired: 'अपना मोबाइल नंबर डालें',
      mobileInvalid: 'सही 10 अंकों का मोबाइल नंबर डालें',
      consent: 'मैं सेवा की शर्तें और गोपनीयता नीति स्वीकार करता/करती हूँ',
      consentRequired: 'आगे बढ़ने के लिए शर्तें स्वीकार करें',
      getOtp: 'OTP भेजें',
      secureNote: 'नंबर सत्यापित करने के लिए हम 6 अंकों का कोड भेजेंगे।',
    },
    otp: {
      title: 'अपना नंबर सत्यापित करें',
      subtitle: '{{mobile}} पर भेजा गया 6 अंकों का कोड डालें',
      otpRequired: '6 अंकों का कोड डालें',
      otpInvalid: 'कोड 6 अंकों का होना चाहिए',
      verify: 'सत्यापित करें',
      resend: 'कोड दोबारा भेजें',
      resendIn: '{{seconds}} सेकंड में दोबारा भेजें',
      changeNumber: 'नंबर बदलें',
      autoReadHint: 'अनुमति होने पर हम कोड अपने आप भर देंगे।',
      hintDev: 'डेमो मोड: {{otp}} डालें',
    },
  },

  kyc: {
    title: 'कारोबार का सत्यापन',
    stepOf: 'चरण {{current}} / {{total}}',
    saveAndExit: 'सेव करके बाहर निकलें',
    resumeTitle: 'सत्यापन जारी रखें',
    resumeBody: 'आप चरण {{step}} पर रुके थे। वहीं से आगे बढ़ें।',
    progress: {
      business: 'कारोबार',
      identity: 'पहचान',
      bank: 'बैंक',
      aadhaar: 'आधार',
    },
    business: {
      title: 'अपने कारोबार के बारे में बताएँ',
      subtitle: 'यही नाम आपके QR पर ग्राहकों को दिखेगा।',
      name: 'कारोबार का नाम',
      namePlaceholder: 'जैसे शर्मा जनरल स्टोर',
      nameRequired: 'कारोबार का नाम डालें',
      nameTooShort: 'नाम कम से कम 3 अक्षरों का हो',
      category: 'कारोबार की श्रेणी',
      categoryPlaceholder: 'श्रेणी चुनें',
      categoryRequired: 'अपने कारोबार की श्रेणी चुनें',
      categorySheetTitle: 'कारोबार की श्रेणी चुनें',
      addressLine1: 'दुकान / इमारत का पता',
      addressPlaceholder: 'दुकान नंबर, गली, इलाका',
      addressRequired: 'कारोबार का पता डालें',
      pincode: 'पिन कोड',
      pincodePlaceholder: '6 अंकों का पिन कोड',
      pincodeRequired: 'अपना पिन कोड डालें',
      pincodeInvalid: 'सही 6 अंकों का पिन कोड डालें',
      city: 'शहर',
      cityRequired: 'अपना शहर डालें',
      state: 'राज्य',
      stateRequired: 'अपना राज्य डालें',
      pincodeLookup: 'आपका इलाका खोज रहे हैं…',
    },
    identity: {
      title: 'पहचान की जानकारी',
      subtitle: 'पेमेंट लेने के लिए RBI द्वारा अनिवार्य।',
      pan: 'PAN नंबर',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'अपना PAN नंबर डालें',
      panInvalid: 'सही PAN डालें (जैसे ABCDE1234F)',
      panHelp: 'जैसा आपके PAN कार्ड पर छपा है।',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'सही 15 अक्षरों का GSTIN डालें',
      gstinHelp: 'GST वाले बिल चाहिए तो यह जोड़ें।',
    },
    bank: {
      title: 'पैसा कहाँ भेजें?',
      subtitle: 'आपकी कमाई यहीं आएगी, आम तौर पर अगले दिन।',
      accountNumber: 'खाता संख्या',
      accountNumberPlaceholder: 'बैंक खाता संख्या',
      accountNumberRequired: 'अपनी खाता संख्या डालें',
      accountNumberInvalid: 'खाता संख्या 9 से 18 अंकों की हो',
      confirmAccountNumber: 'खाता संख्या दोबारा डालें',
      accountMismatch: 'खाता संख्या मेल नहीं खा रही',
      ifsc: 'IFSC कोड',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'IFSC कोड डालें',
      ifscInvalid: 'सही IFSC डालें (जैसे HDFC0001234)',
      holderName: 'खाताधारक का नाम',
      holderNamePlaceholder: 'बैंक रिकॉर्ड के अनुसार नाम',
      holderNameRequired: 'खाताधारक का नाम डालें',
      verifyCta: 'खाता सत्यापित करें',
      verifying: 'आपका खाता सत्यापित हो रहा है…',
      verifyingBody: 'यह खाता आपका है, इसकी पुष्टि के लिए हम ₹1 भेज रहे हैं।',
      verifiedTitle: 'खाता सत्यापित हो गया',
      verifiedNameAtBank: 'बैंक में नाम: {{name}}',
      unlockNote: 'इस चरण के बाद आप सीमा के साथ पेमेंट लेना शुरू कर सकते हैं, जाँच पूरी होने तक।',
    },
    aadhaar: {
      title: 'आधार सत्यापन',
      subtitle: 'सभी सुविधाएँ खोलने का आख़िरी चरण।',
      numberLabel: 'आधार नंबर',
      numberPlaceholder: '12 अंकों का आधार नंबर',
      numberRequired: 'अपना आधार नंबर डालें',
      numberInvalid: 'आधार नंबर 12 अंकों का होना चाहिए',
      consent: 'मैं आधार eKYC से अपनी पहचान सत्यापित करने की सहमति देता/देती हूँ। मैं समझता/समझती हूँ कि मेरे आधार विवरण का उपयोग केवल इस सत्यापन के लिए होगा।',
      consentRequired: 'आगे बढ़ने के लिए आपकी सहमति ज़रूरी है',
      sendOtp: 'आधार OTP भेजें',
      otpLabel: 'आधार OTP',
      otpSentTo: 'आधार से जुड़े मोबाइल पर भेजा गया कोड डालें।',
      otpRequired: '6 अंकों का आधार OTP डालें',
      verifyCta: 'आधार सत्यापित करें',
      verifiedTitle: 'आधार सत्यापित हो गया',
      skipForNow: 'बाद में करें',
      privacyNote: 'हम आपका पूरा आधार नंबर कभी सेव नहीं करते।',
    },
    done: {
      title: 'सब तैयार है!',
      subtitle: 'आपकी जानकारी भेज दी गई है। आप अभी से पेमेंट लेना शुरू कर सकते हैं।',
      pendingTitle: 'सत्यापन चल रहा है',
      pendingSubtitle: 'हम आपकी जानकारी जाँच रहे हैं। इसमें आम तौर पर कुछ घंटे लगते हैं।',
      generateQr: 'मेरा QR बनाएँ',
      goHome: 'डैशबोर्ड पर जाएँ',
      vpaLabel: 'आपकी UPI ID',
      limitsNote: 'सत्यापन पूरा होने तक आप रोज़ {{limit}} तक ले सकते हैं।',
    },
    status: {
      not_started: 'KYC बाकी',
      in_progress: 'KYC अधूरा',
      pending_review: 'जाँच जारी',
      approved: 'सत्यापित',
      rejected: 'कार्रवाई ज़रूरी',
    },
    rejected: {
      title: 'हमें दोबारा देखना होगा',
      reasonLabel: 'कारण',
      retryCta: 'जानकारी अपडेट करें',
    },
    submitCta: 'सत्यापन के लिए भेजें',
    mcc: {
      grocery: 'किराना / जनरल स्टोर',
      restaurant: 'रेस्टोरेंट / कैफ़े',
      apparel: 'कपड़े और परिधान',
      electronics: 'इलेक्ट्रॉनिक्स और मोबाइल',
      pharmacy: 'दवा की दुकान / मेडिकल',
      salon: 'सैलून और ब्यूटी',
      hardware: 'हार्डवेयर और निर्माण सामग्री',
      services: 'पेशेवर सेवाएँ',
      education: 'शिक्षा और कोचिंग',
      transport: 'परिवहन और यात्रा',
      online: 'ऑनलाइन / D2C विक्रेता',
      other: 'अन्य',
    },
  },

  home: {
    greeting: 'नमस्ते',
    summary: {
      title: 'आज की कमाई',
      collected: 'आज मिला',
      txnCount: '{{count}} पेमेंट',
      txnCount_plural: '{{count}} पेमेंट',
      pendingSettlement: 'सेटलमेंट बाकी',
      settlementHint: 'आपके बैंक खाते में आएगा',
    },
    collectCta: 'पैसे लें',
    quickActions: {
      title: 'तुरंत करें',
      myQr: 'मेरा QR',
      paymentLink: 'पेमेंट लिंक',
      reports: 'रिपोर्ट',
      refund: 'रिफ़ंड',
    },
    recent: {
      title: 'हाल के पेमेंट',
      emptyTitle: 'अभी कोई पेमेंट नहीं',
      emptyBody: 'पहला पेमेंट पाने के लिए ग्राहक को अपना QR दिखाएँ।',
      emptyCta: 'मेरा QR दिखाएँ',
    },
    kycNudge: {
      title: 'सत्यापन पूरा करें',
      body: 'सीमा हटाने के लिए अपनी जानकारी पूरी करें।',
      cta: 'आगे बढ़ें',
    },
    error: {
      title: 'डैशबोर्ड लोड नहीं हो सका',
      body: 'इंटरनेट जाँचकर दोबारा कोशिश करें।',
    },
  },

  notifications: {
    title: 'सूचनाएँ',
    emptyTitle: 'कोई सूचना नहीं',
    emptyBody: 'पेमेंट और सेटलमेंट की जानकारी यहाँ दिखेगी।',
  },

  transactions: {
    title: 'लेन-देन',
    status: {
      success: 'मिल गया',
      pending: 'बाकी',
      failed: 'विफल',
      refunded: 'वापस किया',
      partially_refunded: 'आंशिक वापसी',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI ऐप',
      payment_link: 'पेमेंट लिंक',
      card: 'कार्ड',
      netbanking: 'नेट बैंकिंग',
      wallet: 'वॉलेट',
    },
  },

  settlements: {
    title: 'सेटलमेंट',
    status: {
      pending: 'बाकी',
      processing: 'चल रहा है',
      settled: 'जमा हो गया',
      failed: 'विफल',
    },
  },

  collect: {
    title: 'पैसे लें',
    subtitle: 'आप पैसे कैसे लेना चाहते हैं?',
    modes: {
      staticQr: 'मेरा QR कोड',
      staticQrBody: 'किसी भी रकम के लिए एक कोड। दिखाएँ या छपवाएँ।',
      dynamicQr: 'रकम डालें',
      dynamicQrBody: 'तय रकम के लिए QR बनाएँ।',
      paymentLink: 'पेमेंट लिंक',
      paymentLinkBody: 'WhatsApp या SMS पर लिंक भेजें।',
    },
    staticQr: {
      title: 'मेरा QR कोड',
      instruction: 'ग्राहक से कहें कि स्कैन करके कोई भी रकम भेजें।',
      vpaLabel: 'UPI ID',
      noQrTitle: 'QR अभी तैयार नहीं',
      noQrBody: 'QR कोड पाने के लिए बैंक सत्यापन पूरा करें।',
      noQrCta: 'सत्यापन पूरा करें',
      offlineUsable: 'आपका QR बिना इंटरनेट भी चलता है।',
    },
    amount: {
      title: 'रकम डालें',
      generateQr: 'QR बनाएँ',
      createLink: 'लिंक बनाएँ',
      noteLabel: 'टिप्पणी',
      notePlaceholder: 'किस लिए? (वैकल्पिक)',
      tooLow: '{{min}} से ज़्यादा रकम डालें',
      limitExceeded: 'सत्यापन पूरा होने तक रोज़ की सीमा {{limit}} है',
      upiCap: 'एक UPI पेमेंट में अधिकतम {{max}}',
    },
    dynamicQr: {
      title: 'भुगतान के लिए स्कैन करें',
      waiting: 'पेमेंट का इंतज़ार…',
      waitingBody: 'ग्राहक से यह कोड स्कैन करने को कहें।',
      expiresIn: '{{time}} में समाप्त',
      expiredTitle: 'QR समाप्त हो गया',
      expiredBody: 'यह कोड अब मान्य नहीं है। नया बनाएँ।',
      newQr: 'नया QR बनाएँ',
      cancel: 'रद्द करें',
      checkingSlowly: 'जाँच जारी है। आपका इंटरनेट धीमा लग रहा है।',
      failedTitle: 'पेमेंट विफल',
      failedBody: 'ग्राहक का पेमेंट नहीं हुआ। उनसे दोबारा कोशिश करने को कहें।',
      offlineTitle: 'इंटरनेट नहीं है',
      offlineBody: 'तय रकम वाले QR के लिए इंटरनेट ज़रूरी है। इसके बजाय अपना QR कोड दिखाएँ।',
      useStaticQr: 'मेरा QR कोड दिखाएँ',
    },
    link: {
      title: 'पेमेंट लिंक',
      createdTitle: 'लिंक तैयार है',
      createdBody: 'यह ग्राहक को भेजें। यह 24 घंटे में समाप्त हो जाएगा।',
      copy: 'लिंक कॉपी करें',
      copied: 'लिंक कॉपी हो गया',
      shareVia: 'लिंक शेयर करें',
      newLink: 'एक और बनाएँ',
      shareMessage: 'कृपया इस लिंक से {{amount}} का भुगतान करें: {{url}}',
    },
    success: {
      title: 'पेमेंट मिल गया!',
      amountLabel: 'मिली रकम',
      txnIdLabel: 'लेन-देन ID',
      timeLabel: 'समय',
      payerLabel: 'भेजने वाला',
      utrLabel: 'UPI रेफ़रेंस',
      shareReceipt: 'रसीद शेयर करें',
      newPayment: 'नया पेमेंट',
      done: 'हो गया',
      receiptMessage: 'पेमेंट मिला: {{time}} पर {{amount}}. लेन-देन ID: {{id}}.',
    },
    audio: {
      received: '{{amount}} रुपये मिले',
      mutedHint: 'आवाज़ की पुष्टि बंद है। सेटिंग में चालू करें।',
    },
  },
};

export default hi;
