import type { TranslationBundle } from './en';

/** Kannada (ಕನ್ನಡ) */
export const kn: TranslationBundle = {
  common: {
    appName: 'MerchantOne',
    ok: 'ಸರಿ',
    cancel: 'ರದ್ದು',
    continue: 'ಮುಂದುವರಿಸು',
    back: 'ಹಿಂದೆ',
    next: 'ಮುಂದೆ',
    skip: 'ಬಿಟ್ಟುಬಿಡು',
    done: 'ಮುಗಿದಿದೆ',
    retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    save: 'ಉಳಿಸು',
    close: 'ಮುಚ್ಚು',
    share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    download: 'ಡೌನ್‌ಲೋಡ್',
    search: 'ಹುಡುಕು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡು',
    today: 'ಇಂದು',
    yesterday: 'ನಿನ್ನೆ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
    yes: 'ಹೌದು',
    no: 'ಇಲ್ಲ',
    optional: 'ಐಚ್ಛಿಕ',
    verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    verifying: 'ಪರಿಶೀಲಿಸುತ್ತಿದೆ…',
    edit: 'ಬದಲಾಯಿಸು',
    remove: 'ತೆಗೆದುಹಾಕು',
    confirm: 'ದೃಢೀಕರಿಸು',
    comingSoon: 'ಶೀಘ್ರದಲ್ಲೇ',
    comingSoonBody: 'ಈ ವಿಭಾಗ ಸಿದ್ಧವಾಗುತ್ತಿದೆ.',
    months: {
      jan: 'ಜನ',
      feb: 'ಫೆಬ್ರ',
      mar: 'ಮಾರ್ಚ್',
      apr: 'ಏಪ್ರಿ',
      may: 'ಮೇ',
      jun: 'ಜೂನ್',
      jul: 'ಜುಲೈ',
      aug: 'ಆಗ',
      sep: 'ಸೆಪ್',
      oct: 'ಅಕ್ಟೋ',
      nov: 'ನವೆಂ',
      dec: 'ಡಿಸೆಂ',
    },
  },

  a11y: {
    back: 'ಹಿಂದೆ ಹೋಗು',
    close: 'ಮುಚ್ಚು',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    loading: 'ವಿಷಯ ಲೋಡ್ ಆಗುತ್ತಿದೆ',
    amount: 'ಮೊತ್ತ {{amount}}',
    step: 'ಹಂತ {{current}} / {{total}}',
  },

  tabs: {
    home: 'ಮುಖಪುಟ',
    collect: 'ಹಣ ಪಡೆಯಿರಿ',
    transactions: 'ವಹಿವಾಟುಗಳು',
    settlements: 'ಸೆಟಲ್‌ಮೆಂಟ್',
    more: 'ಇನ್ನಷ್ಟು',
  },

  network: {
    offlineTitle: 'ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ',
    offlineBanner: 'ಇಂಟರ್ನೆಟ್ ಇಲ್ಲ. ಉಳಿಸಿದ ಮಾಹಿತಿ ತೋರಿಸುತ್ತಿದೆ.',
    offlineActionDisabled: 'ಇದಕ್ಕೆ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಬೇಕು.',
    backOnline: 'ಸಂಪರ್ಕ ಮರಳಿದೆ',
  },

  errors: {
    title: 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
    network_error: 'ಸರ್ವರ್ ಸಂಪರ್ಕಿಸಲು ಆಗುತ್ತಿಲ್ಲ. ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    timeout: 'ಬಹಳ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    offline: 'ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ. ಇಂಟರ್ನೆಟ್‌ಗೆ ಸಂಪರ್ಕಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    unauthorized: 'ನಿಮ್ಮ ಸೆಷನ್ ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಲಾಗಿನ್ ಆಗಿ.',
    forbidden: 'ಇದನ್ನು ಮಾಡಲು ನಿಮಗೆ ಅನುಮತಿ ಇಲ್ಲ.',
    not_found: 'ನೀವು ಹುಡುಕುತ್ತಿದ್ದದ್ದು ಸಿಗಲಿಲ್ಲ.',
    validation_error: 'ನೀವು ನಮೂದಿಸಿದ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    rate_limited: 'ಹಲವು ಪ್ರಯತ್ನಗಳು. ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.',
    invalid_otp: 'ಈ OTP ತಪ್ಪಾಗಿದೆ. ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ನಮೂದಿಸಿ.',
    otp_expired: 'ಈ OTP ಅವಧಿ ಮುಗಿದಿದೆ. ಹೊಸದನ್ನು ಕೇಳಿ.',
    invalid_mobile: 'ಸರಿಯಾದ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.',
    kyc_incomplete: 'ಈ ಸೌಲಭ್ಯಕ್ಕಾಗಿ ನಿಮ್ಮ KYC ಪೂರ್ಣಗೊಳಿಸಿ.',
    kyc_rejected: 'ನಿಮ್ಮ KYC ಅನುಮೋದನೆಯಾಗಿಲ್ಲ. ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಸಲ್ಲಿಸಿ.',
    bank_verification_failed: 'ಈ ಬ್ಯಾಂಕ್ ಖಾತೆ ಪರಿಶೀಲಿಸಲು ಆಗಲಿಲ್ಲ. ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    pan_verification_failed: 'ಈ PAN ಪರಿಶೀಲಿಸಲು ಆಗಲಿಲ್ಲ. ಸಂಖ್ಯೆ ಪರಿಶೀಲಿಸಿ.',
    already_refunded: 'ಈ ವಹಿವಾಟಿಗೆ ಈಗಾಗಲೇ ಹಣ ಮರುಪಾವತಿಯಾಗಿದೆ.',
    refund_limit_exceeded: 'ಮರುಪಾವತಿ ಮೊತ್ತ ಲಭ್ಯ ಮೊತ್ತಕ್ಕಿಂತ ಹೆಚ್ಚಾಗಿದೆ.',
    payment_expired: 'ಈ ಪಾವತಿ ವಿನಂತಿಯ ಅವಧಿ ಮುಗಿದಿದೆ. ಹೊಸದನ್ನು ರಚಿಸಿ.',
    server_error: 'ನಮ್ಮ ಸರ್ವರ್‌ನಲ್ಲಿ ಸಮಸ್ಯೆ. ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.',
    unknown: 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  },

  auth: {
    splash: {
      tagline: 'ಪಾವತಿ ಈಗ ಸುಲಭ',
    },
    login: {
      title: 'ಸ್ವಾಗತ',
      subtitle: 'ನಿಮ್ಮ ವ್ಯಾಪಾರ ನಿರ್ವಹಿಸಲು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯಿಂದ ಲಾಗಿನ್ ಆಗಿ',
      mobileLabel: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      mobilePlaceholder: '10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      mobileRequired: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      mobileInvalid: 'ಸರಿಯಾದ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      consent: 'ನಾನು ಸೇವಾ ನಿಯಮಗಳು ಮತ್ತು ಗೋಪ್ಯತಾ ನೀತಿಯನ್ನು ಒಪ್ಪುತ್ತೇನೆ',
      consentRequired: 'ಮುಂದುವರಿಯಲು ನಿಯಮಗಳನ್ನು ಒಪ್ಪಿಕೊಳ್ಳಿ',
      getOtp: 'OTP ಪಡೆಯಿರಿ',
      secureNote: 'ನಿಮ್ಮ ಸಂಖ್ಯೆ ಪರಿಶೀಲಿಸಲು 6 ಅಂಕಿಯ ಕೋಡ್ ಕಳುಹಿಸುತ್ತೇವೆ.',
    },
    otp: {
      title: 'ನಿಮ್ಮ ಸಂಖ್ಯೆ ಪರಿಶೀಲಿಸಿ',
      subtitle: '{{mobile}} ಗೆ ಕಳುಹಿಸಿದ 6 ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ',
      otpRequired: '6 ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ',
      otpInvalid: 'ಕೋಡ್ 6 ಅಂಕಿ ಇರಬೇಕು',
      verify: 'ಪರಿಶೀಲಿಸು',
      resend: 'ಕೋಡ್ ಮತ್ತೆ ಕಳುಹಿಸು',
      resendIn: '{{seconds}} ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಮತ್ತೆ ಕಳುಹಿಸು',
      changeNumber: 'ಸಂಖ್ಯೆ ಬದಲಾಯಿಸು',
      autoReadHint: 'ಅನುಮತಿ ಇದ್ದರೆ ಕೋಡ್ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಓದುತ್ತೇವೆ.',
      hintDev: 'ಡೆಮೋ ಮೋಡ್: {{otp}} ಬಳಸಿ',
    },
  },

  kyc: {
    title: 'ವ್ಯಾಪಾರ ಪರಿಶೀಲನೆ',
    stepOf: 'ಹಂತ {{current}} / {{total}}',
    saveAndExit: 'ಉಳಿಸಿ ನಿರ್ಗಮಿಸಿ',
    resumeTitle: 'ಪರಿಶೀಲನೆ ಮುಂದುವರಿಸಿ',
    resumeBody: 'ನೀವು ಹಂತ {{step}} ನಲ್ಲಿ ನಿಂತಿದ್ದೀರಿ. ಅಲ್ಲಿಂದ ಮುಂದುವರಿಸಿ.',
    progress: {
      business: 'ವ್ಯಾಪಾರ',
      identity: 'ಗುರುತು',
      bank: 'ಬ್ಯಾಂಕ್',
      aadhaar: 'ಆಧಾರ್',
    },
    business: {
      title: 'ನಿಮ್ಮ ವ್ಯಾಪಾರದ ಬಗ್ಗೆ ತಿಳಿಸಿ',
      subtitle: 'ಗ್ರಾಹಕರು ಸ್ಕ್ಯಾನ್ ಮಾಡುವ QR ನಲ್ಲಿ ಇದು ಕಾಣುತ್ತದೆ.',
      name: 'ವ್ಯಾಪಾರದ ಹೆಸರು',
      namePlaceholder: 'ಉದಾ. ಶರ್ಮಾ ಜನರಲ್ ಸ್ಟೋರ್',
      nameRequired: 'ನಿಮ್ಮ ವ್ಯಾಪಾರದ ಹೆಸರು ನಮೂದಿಸಿ',
      nameTooShort: 'ಹೆಸರು ಕನಿಷ್ಠ 3 ಅಕ್ಷರಗಳಿರಬೇಕು',
      category: 'ವ್ಯಾಪಾರ ವಿಭಾಗ',
      categoryPlaceholder: 'ಒಂದು ವಿಭಾಗ ಆಯ್ಕೆಮಾಡಿ',
      categoryRequired: 'ನಿಮ್ಮ ವ್ಯಾಪಾರ ವಿಭಾಗ ಆಯ್ಕೆಮಾಡಿ',
      categorySheetTitle: 'ವ್ಯಾಪಾರ ವಿಭಾಗ ಆಯ್ಕೆಮಾಡಿ',
      addressLine1: 'ಅಂಗಡಿ / ಕಟ್ಟಡದ ವಿಳಾಸ',
      addressPlaceholder: 'ಅಂಗಡಿ ಸಂಖ್ಯೆ, ರಸ್ತೆ, ಪ್ರದೇಶ',
      addressRequired: 'ನಿಮ್ಮ ವ್ಯಾಪಾರದ ವಿಳಾಸ ನಮೂದಿಸಿ',
      pincode: 'ಪಿನ್ ಕೋಡ್',
      pincodePlaceholder: '6 ಅಂಕಿಯ ಪಿನ್ ಕೋಡ್',
      pincodeRequired: 'ನಿಮ್ಮ ಪಿನ್ ಕೋಡ್ ನಮೂದಿಸಿ',
      pincodeInvalid: 'ಸರಿಯಾದ 6 ಅಂಕಿಯ ಪಿನ್ ಕೋಡ್ ನಮೂದಿಸಿ',
      city: 'ನಗರ',
      cityRequired: 'ನಿಮ್ಮ ನಗರ ನಮೂದಿಸಿ',
      state: 'ರಾಜ್ಯ',
      stateRequired: 'ನಿಮ್ಮ ರಾಜ್ಯ ನಮೂದಿಸಿ',
      pincodeLookup: 'ನಿಮ್ಮ ಪ್ರದೇಶ ಹುಡುಕುತ್ತಿದೆ…',
    },
    identity: {
      title: 'ಗುರುತಿನ ವಿವರಗಳು',
      subtitle: 'ಪಾವತಿ ಸ್ವೀಕರಿಸಲು RBI ಕಡ್ಡಾಯಗೊಳಿಸಿದೆ.',
      pan: 'PAN ಸಂಖ್ಯೆ',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'ನಿಮ್ಮ PAN ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      panInvalid: 'ಸರಿಯಾದ PAN ನಮೂದಿಸಿ (ಉದಾ. ABCDE1234F)',
      panHelp: 'ನಿಮ್ಮ PAN ಕಾರ್ಡ್‌ನಲ್ಲಿ ಮುದ್ರಿತವಾಗಿರುವಂತೆ.',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'ಸರಿಯಾದ 15 ಅಕ್ಷರಗಳ GSTIN ನಮೂದಿಸಿ',
      gstinHelp: 'GST ಬಿಲ್ ಬೇಕಿದ್ದರೆ ಇದನ್ನು ಸೇರಿಸಿ.',
    },
    bank: {
      title: 'ನಿಮ್ಮ ಹಣ ಎಲ್ಲಿಗೆ ಕಳುಹಿಸಬೇಕು?',
      subtitle: 'ನಿಮ್ಮ ಸಂಗ್ರಹ ಇಲ್ಲಿಗೆ ಜಮೆಯಾಗುತ್ತದೆ, ಸಾಮಾನ್ಯವಾಗಿ ಮರುದಿನ.',
      accountNumber: 'ಖಾತೆ ಸಂಖ್ಯೆ',
      accountNumberPlaceholder: 'ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ',
      accountNumberRequired: 'ನಿಮ್ಮ ಖಾತೆ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      accountNumberInvalid: 'ಖಾತೆ ಸಂಖ್ಯೆ 9 ರಿಂದ 18 ಅಂಕಿ ಇರಬೇಕು',
      confirmAccountNumber: 'ಖಾತೆ ಸಂಖ್ಯೆ ಮತ್ತೆ ನಮೂದಿಸಿ',
      accountMismatch: 'ಖಾತೆ ಸಂಖ್ಯೆಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
      ifsc: 'IFSC ಕೋಡ್',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'IFSC ಕೋಡ್ ನಮೂದಿಸಿ',
      ifscInvalid: 'ಸರಿಯಾದ IFSC ನಮೂದಿಸಿ (ಉದಾ. HDFC0001234)',
      holderName: 'ಖಾತೆದಾರರ ಹೆಸರು',
      holderNamePlaceholder: 'ಬ್ಯಾಂಕ್ ದಾಖಲೆಯ ಪ್ರಕಾರ ಹೆಸರು',
      holderNameRequired: 'ಖಾತೆದಾರರ ಹೆಸರು ನಮೂದಿಸಿ',
      verifyCta: 'ಖಾತೆ ಪರಿಶೀಲಿಸು',
      verifying: 'ನಿಮ್ಮ ಖಾತೆ ಪರಿಶೀಲಿಸುತ್ತಿದೆ…',
      verifyingBody: 'ಈ ಖಾತೆ ನಿಮ್ಮದೆಂದು ಖಚಿತಪಡಿಸಲು ₹1 ಕಳುಹಿಸುತ್ತಿದ್ದೇವೆ.',
      verifiedTitle: 'ಖಾತೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      verifiedNameAtBank: 'ಬ್ಯಾಂಕ್‌ನಲ್ಲಿ ಹೆಸರು: {{name}}',
      unlockNote: 'ಈ ಹಂತದ ನಂತರ ಮಿತಿಗಳೊಂದಿಗೆ ಪಾವತಿ ಸ್ವೀಕರಿಸಲು ಆರಂಭಿಸಬಹುದು, ಪರಿಶೀಲನೆ ಮುಗಿಯುವವರೆಗೆ.',
    },
    aadhaar: {
      title: 'ಆಧಾರ್ ಪರಿಶೀಲನೆ',
      subtitle: 'ಎಲ್ಲ ಸೌಲಭ್ಯ ತೆರೆಯಲು ಕೊನೆಯ ಹಂತ.',
      numberLabel: 'ಆಧಾರ್ ಸಂಖ್ಯೆ',
      numberPlaceholder: '12 ಅಂಕಿಯ ಆಧಾರ್ ಸಂಖ್ಯೆ',
      numberRequired: 'ನಿಮ್ಮ ಆಧಾರ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      numberInvalid: 'ಆಧಾರ್ ಸಂಖ್ಯೆ 12 ಅಂಕಿ ಇರಬೇಕು',
      consent: 'ಆಧಾರ್ eKYC ಮೂಲಕ ನನ್ನ ಗುರುತು ಪರಿಶೀಲಿಸಲು ನಾನು ಸಮ್ಮತಿಸುತ್ತೇನೆ. ನನ್ನ ಆಧಾರ್ ವಿವರಗಳು ಈ ಪರಿಶೀಲನೆಗೆ ಮಾತ್ರ ಬಳಕೆಯಾಗುತ್ತವೆ ಎಂದು ನಾನು ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೇನೆ.',
      consentRequired: 'ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಸಮ್ಮತಿ ಅಗತ್ಯ',
      sendOtp: 'ಆಧಾರ್ OTP ಕಳುಹಿಸು',
      otpLabel: 'ಆಧಾರ್ OTP',
      otpSentTo: 'ಆಧಾರ್‌ಗೆ ಲಿಂಕ್ ಆದ ಮೊಬೈಲ್‌ಗೆ ಕಳುಹಿಸಿದ ಕೋಡ್ ನಮೂದಿಸಿ.',
      otpRequired: '6 ಅಂಕಿಯ ಆಧಾರ್ OTP ನಮೂದಿಸಿ',
      verifyCta: 'ಆಧಾರ್ ಪರಿಶೀಲಿಸು',
      verifiedTitle: 'ಆಧಾರ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      skipForNow: 'ನಂತರ ಮಾಡು',
      privacyNote: 'ನಿಮ್ಮ ಪೂರ್ಣ ಆಧಾರ್ ಸಂಖ್ಯೆಯನ್ನು ನಾವು ಎಂದಿಗೂ ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ.',
    },
    done: {
      title: 'ಎಲ್ಲ ಸಿದ್ಧ!',
      subtitle: 'ನಿಮ್ಮ ವಿವರಗಳು ಸಲ್ಲಿಕೆಯಾಗಿವೆ. ಈಗಲೇ ಪಾವತಿ ಸ್ವೀಕರಿಸಲು ಆರಂಭಿಸಬಹುದು.',
      pendingTitle: 'ಪರಿಶೀಲನೆ ನಡೆಯುತ್ತಿದೆ',
      pendingSubtitle: 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸುತ್ತಿದ್ದೇವೆ. ಸಾಮಾನ್ಯವಾಗಿ ಕೆಲವು ಗಂಟೆ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ.',
      generateQr: 'ನನ್ನ QR ರಚಿಸು',
      goHome: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗು',
      vpaLabel: 'ನಿಮ್ಮ UPI ID',
      limitsNote: 'ಪರಿಶೀಲನೆ ಮುಗಿಯುವವರೆಗೆ ದಿನಕ್ಕೆ {{limit}} ವರೆಗೆ ಪಡೆಯಬಹುದು.',
    },
    status: {
      not_started: 'KYC ಬಾಕಿ',
      in_progress: 'KYC ಅಪೂರ್ಣ',
      pending_review: 'ಪರಿಶೀಲನೆಯಲ್ಲಿ',
      approved: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      rejected: 'ಕ್ರಮ ಅಗತ್ಯ',
    },
    rejected: {
      title: 'ಮತ್ತೊಮ್ಮೆ ನೋಡಬೇಕು',
      reasonLabel: 'ಕಾರಣ',
      retryCta: 'ವಿವರಗಳನ್ನು ನವೀಕರಿಸು',
    },
    submitCta: 'ಪರಿಶೀಲನೆಗೆ ಸಲ್ಲಿಸು',
    mcc: {
      grocery: 'ಕಿರಾಣಿ / ಜನರಲ್ ಸ್ಟೋರ್',
      restaurant: 'ರೆಸ್ಟೋರೆಂಟ್ / ಕೆಫೆ',
      apparel: 'ಬಟ್ಟೆ ಮತ್ತು ಉಡುಪು',
      electronics: 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಮತ್ತು ಮೊಬೈಲ್',
      pharmacy: 'ಔಷಧಿ ಅಂಗಡಿ / ಮೆಡಿಕಲ್',
      salon: 'ಸೆಲೂನ್ ಮತ್ತು ಸೌಂದರ್ಯ',
      hardware: 'ಹಾರ್ಡ್‌ವೇರ್ ಮತ್ತು ಕಟ್ಟಡ ಸಾಮಗ್ರಿ',
      services: 'ವೃತ್ತಿಪರ ಸೇವೆಗಳು',
      education: 'ಶಿಕ್ಷಣ ಮತ್ತು ತರಬೇತಿ',
      transport: 'ಸಾರಿಗೆ ಮತ್ತು ಪ್ರಯಾಣ',
      online: 'ಆನ್‌ಲೈನ್ / D2C ಮಾರಾಟಗಾರ',
      other: 'ಇತರೆ',
    },
  },

  home: {
    greeting: 'ನಮಸ್ತೆ',
    summary: {
      title: 'ಇಂದಿನ ಸಂಗ್ರಹ',
      collected: 'ಇಂದು ಬಂದದ್ದು',
      txnCount: '{{count}} ಪಾವತಿ',
      txnCount_plural: '{{count}} ಪಾವತಿಗಳು',
      pendingSettlement: 'ಸೆಟಲ್‌ಮೆಂಟ್ ಬಾಕಿ',
      settlementHint: 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆಯಾಗುತ್ತದೆ',
    },
    collectCta: 'ಹಣ ಪಡೆಯಿರಿ',
    quickActions: {
      title: 'ತ್ವರಿತ ಕ್ರಮಗಳು',
      myQr: 'ನನ್ನ QR',
      paymentLink: 'ಪಾವತಿ ಲಿಂಕ್',
      reports: 'ವರದಿಗಳು',
      refund: 'ಮರುಪಾವತಿ',
    },
    recent: {
      title: 'ಇತ್ತೀಚಿನ ಪಾವತಿಗಳು',
      emptyTitle: 'ಇನ್ನೂ ಪಾವತಿ ಇಲ್ಲ',
      emptyBody: 'ಮೊದಲ ಪಾವತಿ ಪಡೆಯಲು ಗ್ರಾಹಕರಿಗೆ ನಿಮ್ಮ QR ತೋರಿಸಿ.',
      emptyCta: 'ನನ್ನ QR ತೋರಿಸು',
    },
    kycNudge: {
      title: 'ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಳಿಸಿ',
      body: 'ಮಿತಿಗಳನ್ನು ತೆಗೆಯಲು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ.',
      cta: 'ಮುಂದುವರಿಸು',
    },
    error: {
      title: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಲೋಡ್ ಆಗಲಿಲ್ಲ',
      body: 'ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    },
  },

  notifications: {
    title: 'ಅಧಿಸೂಚನೆಗಳು',
    emptyTitle: 'ಅಧಿಸೂಚನೆ ಇಲ್ಲ',
    emptyBody: 'ಪಾವತಿ ಮತ್ತು ಸೆಟಲ್‌ಮೆಂಟ್ ಮಾಹಿತಿ ಇಲ್ಲಿ ಕಾಣುತ್ತದೆ.',
  },

  transactions: {
    title: 'ವಹಿವಾಟುಗಳು',
    status: {
      success: 'ಬಂದಿದೆ',
      pending: 'ಬಾಕಿ',
      failed: 'ವಿಫಲ',
      refunded: 'ಮರುಪಾವತಿಸಲಾಗಿದೆ',
      partially_refunded: 'ಭಾಗಶಃ ಮರುಪಾವತಿ',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI ಆ್ಯಪ್',
      payment_link: 'ಪಾವತಿ ಲಿಂಕ್',
      card: 'ಕಾರ್ಡ್',
      netbanking: 'ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್',
      wallet: 'ವಾಲೆಟ್',
    },
  },

  settlements: {
    title: 'ಸೆಟಲ್‌ಮೆಂಟ್',
    status: {
      pending: 'ಬಾಕಿ',
      processing: 'ನಡೆಯುತ್ತಿದೆ',
      settled: 'ಜಮೆಯಾಗಿದೆ',
      failed: 'ವಿಫಲ',
    },
  },
};

export default kn;
