import type { TranslationBundle } from './en';

/** Kannada (ಕನ್ನಡ) */
export const kn: TranslationBundle = {
  common: {
    appName: 'MerchantOne',
    ok: 'ಸರಿ',
    cancel: 'ರದ್ದು',
    continue: 'ಮುಂದುವರಿಸು',
    back: 'ಹಿಂದೆ',
    next: 'ಮುಂದೆ',
    skip: 'ಬಿಟ್ಟುಬಿಡು',
    done: 'ಮುಗಿದಿದೆ',
    retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    save: 'ಉಳಿಸು',
    close: 'ಮುಚ್ಚು',
    share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    download: 'ಡೌನ್‌ಲೋಡ್',
    search: 'ಹುಡುಕು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡು',
    today: 'ಇಂದು',
    yesterday: 'ನಿನ್ನೆ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
    yes: 'ಹೌದು',
    no: 'ಇಲ್ಲ',
    optional: 'ಐಚ್ಛಿಕ',
    verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    verifying: 'ಪರಿಶೀಲಿಸುತ್ತಿದೆ…',
    edit: 'ಬದಲಾಯಿಸು',
    remove: 'ತೆಗೆದುಹಾಕು',
    confirm: 'ದೃಢೀಕರಿಸು',
    comingSoon: 'ಶೀಘ್ರದಲ್ಲೇ',
    comingSoonBody: 'ಈ ವಿಭಾಗ ಸಿದ್ಧವಾಗುತ್ತಿದೆ.',
    months: {
      jan: 'ಜನ',
      feb: 'ಫೆಬ್ರ',
      mar: 'ಮಾರ್ಚ್',
      apr: 'ಏಪ್ರಿ',
      may: 'ಮೇ',
      jun: 'ಜೂನ್',
      jul: 'ಜುಲೈ',
      aug: 'ಆಗ',
      sep: 'ಸೆಪ್',
      oct: 'ಅಕ್ಟೋ',
      nov: 'ನವೆಂ',
      dec: 'ಡಿಸೆಂ',
    },
  },

  a11y: {
    back: 'ಹಿಂದೆ ಹೋಗು',
    close: 'ಮುಚ್ಚು',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    loading: 'ವಿಷಯ ಲೋಡ್ ಆಗುತ್ತಿದೆ',
    amount: 'ಮೊತ್ತ {{amount}}',
    step: 'ಹಂತ {{current}} / {{total}}',
  },

  tabs: {
    home: 'ಮುಖಪುಟ',
    collect: 'ಹಣ ಪಡೆಯಿರಿ',
    transactions: 'ವಹಿವಾಟುಗಳು',
    settlements: 'ಸೆಟಲ್‌ಮೆಂಟ್',
    more: 'ಇನ್ನಷ್ಟು',
  },

  network: {
    offlineTitle: 'ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ',
    offlineBanner: 'ಇಂಟರ್ನೆಟ್ ಇಲ್ಲ. ಉಳಿಸಿದ ಮಾಹಿತಿ ತೋರಿಸುತ್ತಿದೆ.',
    offlineActionDisabled: 'ಇದಕ್ಕೆ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಬೇಕು.',
    backOnline: 'ಸಂಪರ್ಕ ಮರಳಿದೆ',
  },

  errors: {
    title: 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
    network_error: 'ಸರ್ವರ್ ಸಂಪರ್ಕಿಸಲು ಆಗುತ್ತಿಲ್ಲ. ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    timeout: 'ಬಹಳ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    offline: 'ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ. ಇಂಟರ್ನೆಟ್‌ಗೆ ಸಂಪರ್ಕಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    unauthorized: 'ನಿಮ್ಮ ಸೆಷನ್ ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಲಾಗಿನ್ ಆಗಿ.',
    forbidden: 'ಇದನ್ನು ಮಾಡಲು ನಿಮಗೆ ಅನುಮತಿ ಇಲ್ಲ.',
    not_found: 'ನೀವು ಹುಡುಕುತ್ತಿದ್ದದ್ದು ಸಿಗಲಿಲ್ಲ.',
    validation_error: 'ನೀವು ನಮೂದಿಸಿದ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    rate_limited: 'ಹಲವು ಪ್ರಯತ್ನಗಳು. ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.',
    invalid_otp: 'ಈ OTP ತಪ್ಪಾಗಿದೆ. ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ನಮೂದಿಸಿ.',
    otp_expired: 'ಈ OTP ಅವಧಿ ಮುಗಿದಿದೆ. ಹೊಸದನ್ನು ಕೇಳಿ.',
    invalid_mobile: 'ಸರಿಯಾದ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.',
    kyc_incomplete: 'ಈ ಸೌಲಭ್ಯಕ್ಕಾಗಿ ನಿಮ್ಮ KYC ಪೂರ್ಣಗೊಳಿಸಿ.',
    kyc_rejected: 'ನಿಮ್ಮ KYC ಅನುಮೋದನೆಯಾಗಿಲ್ಲ. ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಸಲ್ಲಿಸಿ.',
    bank_verification_failed: 'ಈ ಬ್ಯಾಂಕ್ ಖಾತೆ ಪರಿಶೀಲಿಸಲು ಆಗಲಿಲ್ಲ. ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
    pan_verification_failed: 'ಈ PAN ಪರಿಶೀಲಿಸಲು ಆಗಲಿಲ್ಲ. ಸಂಖ್ಯೆ ಪರಿಶೀಲಿಸಿ.',
    already_refunded: 'ಈ ವಹಿವಾಟಿಗೆ ಈಗಾಗಲೇ ಹಣ ಮರುಪಾವತಿಯಾಗಿದೆ.',
    refund_limit_exceeded: 'ಮರುಪಾವತಿ ಮೊತ್ತ ಲಭ್ಯ ಮೊತ್ತಕ್ಕಿಂತ ಹೆಚ್ಚಾಗಿದೆ.',
    payment_expired: 'ಈ ಪಾವತಿ ವಿನಂತಿಯ ಅವಧಿ ಮುಗಿದಿದೆ. ಹೊಸದನ್ನು ರಚಿಸಿ.',
    server_error: 'ನಮ್ಮ ಸರ್ವರ್‌ನಲ್ಲಿ ಸಮಸ್ಯೆ. ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.',
    unknown: 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  },

  auth: {
    splash: {
      tagline: 'ಪಾವತಿ ಈಗ ಸುಲಭ',
    },
    login: {
      title: 'ಸ್ವಾಗತ',
      subtitle: 'ನಿಮ್ಮ ವ್ಯಾಪಾರ ನಿರ್ವಹಿಸಲು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯಿಂದ ಲಾಗಿನ್ ಆಗಿ',
      mobileLabel: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      mobilePlaceholder: '10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      mobileRequired: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      mobileInvalid: 'ಸರಿಯಾದ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      consent: 'ನಾನು ಸೇವಾ ನಿಯಮಗಳು ಮತ್ತು ಗೋಪ್ಯತಾ ನೀತಿಯನ್ನು ಒಪ್ಪುತ್ತೇನೆ',
      consentRequired: 'ಮುಂದುವರಿಯಲು ನಿಯಮಗಳನ್ನು ಒಪ್ಪಿಕೊಳ್ಳಿ',
      getOtp: 'OTP ಪಡೆಯಿರಿ',
      secureNote: 'ನಿಮ್ಮ ಸಂಖ್ಯೆ ಪರಿಶೀಲಿಸಲು 6 ಅಂಕಿಯ ಕೋಡ್ ಕಳುಹಿಸುತ್ತೇವೆ.',
    },
    otp: {
      title: 'ನಿಮ್ಮ ಸಂಖ್ಯೆ ಪರಿಶೀಲಿಸಿ',
      subtitle: '{{mobile}} ಗೆ ಕಳುಹಿಸಿದ 6 ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ',
      otpRequired: '6 ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ',
      otpInvalid: 'ಕೋಡ್ 6 ಅಂಕಿ ಇರಬೇಕು',
      verify: 'ಪರಿಶೀಲಿಸು',
      resend: 'ಕೋಡ್ ಮತ್ತೆ ಕಳುಹಿಸು',
      resendIn: '{{seconds}} ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಮತ್ತೆ ಕಳುಹಿಸು',
      changeNumber: 'ಸಂಖ್ಯೆ ಬದಲಾಯಿಸು',
      autoReadHint: 'ಅನುಮತಿ ಇದ್ದರೆ ಕೋಡ್ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಓದುತ್ತೇವೆ.',
      hintDev: 'ಡೆಮೋ ಮೋಡ್: {{otp}} ಬಳಸಿ',
    },
  },

  kyc: {
    title: 'ವ್ಯಾಪಾರ ಪರಿಶೀಲನೆ',
    stepOf: 'ಹಂತ {{current}} / {{total}}',
    saveAndExit: 'ಉಳಿಸಿ ನಿರ್ಗಮಿಸಿ',
    resumeTitle: 'ಪರಿಶೀಲನೆ ಮುಂದುವರಿಸಿ',
    resumeBody: 'ನೀವು ಹಂತ {{step}} ನಲ್ಲಿ ನಿಂತಿದ್ದೀರಿ. ಅಲ್ಲಿಂದ ಮುಂದುವರಿಸಿ.',
    progress: {
      business: 'ವ್ಯಾಪಾರ',
      identity: 'ಗುರುತು',
      bank: 'ಬ್ಯಾಂಕ್',
      aadhaar: 'ಆಧಾರ್',
    },
    business: {
      title: 'ನಿಮ್ಮ ವ್ಯಾಪಾರದ ಬಗ್ಗೆ ತಿಳಿಸಿ',
      subtitle: 'ಗ್ರಾಹಕರು ಸ್ಕ್ಯಾನ್ ಮಾಡುವ QR ನಲ್ಲಿ ಇದು ಕಾಣುತ್ತದೆ.',
      name: 'ವ್ಯಾಪಾರದ ಹೆಸರು',
      namePlaceholder: 'ಉದಾ. ಶರ್ಮಾ ಜನರಲ್ ಸ್ಟೋರ್',
      nameRequired: 'ನಿಮ್ಮ ವ್ಯಾಪಾರದ ಹೆಸರು ನಮೂದಿಸಿ',
      nameTooShort: 'ಹೆಸರು ಕನಿಷ್ಠ 3 ಅಕ್ಷರಗಳಿರಬೇಕು',
      category: 'ವ್ಯಾಪಾರ ವಿಭಾಗ',
      categoryPlaceholder: 'ಒಂದು ವಿಭಾಗ ಆಯ್ಕೆಮಾಡಿ',
      categoryRequired: 'ನಿಮ್ಮ ವ್ಯಾಪಾರ ವಿಭಾಗ ಆಯ್ಕೆಮಾಡಿ',
      categorySheetTitle: 'ವ್ಯಾಪಾರ ವಿಭಾಗ ಆಯ್ಕೆಮಾಡಿ',
      addressLine1: 'ಅಂಗಡಿ / ಕಟ್ಟಡದ ವಿಳಾಸ',
      addressPlaceholder: 'ಅಂಗಡಿ ಸಂಖ್ಯೆ, ರಸ್ತೆ, ಪ್ರದೇಶ',
      addressRequired: 'ನಿಮ್ಮ ವ್ಯಾಪಾರದ ವಿಳಾಸ ನಮೂದಿಸಿ',
      pincode: 'ಪಿನ್ ಕೋಡ್',
      pincodePlaceholder: '6 ಅಂಕಿಯ ಪಿನ್ ಕೋಡ್',
      pincodeRequired: 'ನಿಮ್ಮ ಪಿನ್ ಕೋಡ್ ನಮೂದಿಸಿ',
      pincodeInvalid: 'ಸರಿಯಾದ 6 ಅಂಕಿಯ ಪಿನ್ ಕೋಡ್ ನಮೂದಿಸಿ',
      city: 'ನಗರ',
      cityRequired: 'ನಿಮ್ಮ ನಗರ ನಮೂದಿಸಿ',
      state: 'ರಾಜ್ಯ',
      stateRequired: 'ನಿಮ್ಮ ರಾಜ್ಯ ನಮೂದಿಸಿ',
      pincodeLookup: 'ನಿಮ್ಮ ಪ್ರದೇಶ ಹುಡುಕುತ್ತಿದೆ…',
    },
    identity: {
      title: 'ಗುರುತಿನ ವಿವರಗಳು',
      subtitle: 'ಪಾವತಿ ಸ್ವೀಕರಿಸಲು RBI ಕಡ್ಡಾಯಗೊಳಿಸಿದೆ.',
      pan: 'PAN ಸಂಖ್ಯೆ',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'ನಿಮ್ಮ PAN ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      panInvalid: 'ಸರಿಯಾದ PAN ನಮೂದಿಸಿ (ಉದಾ. ABCDE1234F)',
      panHelp: 'ನಿಮ್ಮ PAN ಕಾರ್ಡ್‌ನಲ್ಲಿ ಮುದ್ರಿತವಾಗಿರುವಂತೆ.',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'ಸರಿಯಾದ 15 ಅಕ್ಷರಗಳ GSTIN ನಮೂದಿಸಿ',
      gstinHelp: 'GST ಬಿಲ್ ಬೇಕಿದ್ದರೆ ಇದನ್ನು ಸೇರಿಸಿ.',
    },
    bank: {
      title: 'ನಿಮ್ಮ ಹಣ ಎಲ್ಲಿಗೆ ಕಳುಹಿಸಬೇಕು?',
      subtitle: 'ನಿಮ್ಮ ಸಂಗ್ರಹ ಇಲ್ಲಿಗೆ ಜಮೆಯಾಗುತ್ತದೆ, ಸಾಮಾನ್ಯವಾಗಿ ಮರುದಿನ.',
      accountNumber: 'ಖಾತೆ ಸಂಖ್ಯೆ',
      accountNumberPlaceholder: 'ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ',
      accountNumberRequired: 'ನಿಮ್ಮ ಖಾತೆ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      accountNumberInvalid: 'ಖಾತೆ ಸಂಖ್ಯೆ 9 ರಿಂದ 18 ಅಂಕಿ ಇರಬೇಕು',
      confirmAccountNumber: 'ಖಾತೆ ಸಂಖ್ಯೆ ಮತ್ತೆ ನಮೂದಿಸಿ',
      accountMismatch: 'ಖಾತೆ ಸಂಖ್ಯೆಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
      ifsc: 'IFSC ಕೋಡ್',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'IFSC ಕೋಡ್ ನಮೂದಿಸಿ',
      ifscInvalid: 'ಸರಿಯಾದ IFSC ನಮೂದಿಸಿ (ಉದಾ. HDFC0001234)',
      holderName: 'ಖಾತೆದಾರರ ಹೆಸರು',
      holderNamePlaceholder: 'ಬ್ಯಾಂಕ್ ದಾಖಲೆಯ ಪ್ರಕಾರ ಹೆಸರು',
      holderNameRequired: 'ಖಾತೆದಾರರ ಹೆಸರು ನಮೂದಿಸಿ',
      verifyCta: 'ಖಾತೆ ಪರಿಶೀಲಿಸು',
      verifying: 'ನಿಮ್ಮ ಖಾತೆ ಪರಿಶೀಲಿಸುತ್ತಿದೆ…',
      verifyingBody: 'ಈ ಖಾತೆ ನಿಮ್ಮದೆಂದು ಖಚಿತಪಡಿಸಲು ₹1 ಕಳುಹಿಸುತ್ತಿದ್ದೇವೆ.',
      verifiedTitle: 'ಖಾತೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      verifiedNameAtBank: 'ಬ್ಯಾಂಕ್‌ನಲ್ಲಿ ಹೆಸರು: {{name}}',
      unlockNote: 'ಈ ಹಂತದ ನಂತರ ಮಿತಿಗಳೊಂದಿಗೆ ಪಾವತಿ ಸ್ವೀಕರಿಸಲು ಆರಂಭಿಸಬಹುದು, ಪರಿಶೀಲನೆ ಮುಗಿಯುವವರೆಗೆ.',
    },
    aadhaar: {
      title: 'ಆಧಾರ್ ಪರಿಶೀಲನೆ',
      subtitle: 'ಎಲ್ಲ ಸೌಲಭ್ಯ ತೆರೆಯಲು ಕೊನೆಯ ಹಂತ.',
      numberLabel: 'ಆಧಾರ್ ಸಂಖ್ಯೆ',
      numberPlaceholder: '12 ಅಂಕಿಯ ಆಧಾರ್ ಸಂಖ್ಯೆ',
      numberRequired: 'ನಿಮ್ಮ ಆಧಾರ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      numberInvalid: 'ಆಧಾರ್ ಸಂಖ್ಯೆ 12 ಅಂಕಿ ಇರಬೇಕು',
      consent: 'ಆಧಾರ್ eKYC ಮೂಲಕ ನನ್ನ ಗುರುತು ಪರಿಶೀಲಿಸಲು ನಾನು ಸಮ್ಮತಿಸುತ್ತೇನೆ. ನನ್ನ ಆಧಾರ್ ವಿವರಗಳು ಈ ಪರಿಶೀಲನೆಗೆ ಮಾತ್ರ ಬಳಕೆಯಾಗುತ್ತವೆ ಎಂದು ನಾನು ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೇನೆ.',
      consentRequired: 'ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಸಮ್ಮತಿ ಅಗತ್ಯ',
      sendOtp: 'ಆಧಾರ್ OTP ಕಳುಹಿಸು',
      otpLabel: 'ಆಧಾರ್ OTP',
      otpSentTo: 'ಆಧಾರ್‌ಗೆ ಲಿಂಕ್ ಆದ ಮೊಬೈಲ್‌ಗೆ ಕಳುಹಿಸಿದ ಕೋಡ್ ನಮೂದಿಸಿ.',
      otpRequired: '6 ಅಂಕಿಯ ಆಧಾರ್ OTP ನಮೂದಿಸಿ',
      verifyCta: 'ಆಧಾರ್ ಪರಿಶೀಲಿಸು',
      verifiedTitle: 'ಆಧಾರ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      skipForNow: 'ನಂತರ ಮಾಡು',
      privacyNote: 'ನಿಮ್ಮ ಪೂರ್ಣ ಆಧಾರ್ ಸಂಖ್ಯೆಯನ್ನು ನಾವು ಎಂದಿಗೂ ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ.',
    },
    done: {
      title: 'ಎಲ್ಲ ಸಿದ್ಧ!',
      subtitle: 'ನಿಮ್ಮ ವಿವರಗಳು ಸಲ್ಲಿಕೆಯಾಗಿವೆ. ಈಗಲೇ ಪಾವತಿ ಸ್ವೀಕರಿಸಲು ಆರಂಭಿಸಬಹುದು.',
      pendingTitle: 'ಪರಿಶೀಲನೆ ನಡೆಯುತ್ತಿದೆ',
      pendingSubtitle: 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸುತ್ತಿದ್ದೇವೆ. ಸಾಮಾನ್ಯವಾಗಿ ಕೆಲವು ಗಂಟೆ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ.',
      generateQr: 'ನನ್ನ QR ರಚಿಸು',
      goHome: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗು',
      vpaLabel: 'ನಿಮ್ಮ UPI ID',
      limitsNote: 'ಪರಿಶೀಲನೆ ಮುಗಿಯುವವರೆಗೆ ದಿನಕ್ಕೆ {{limit}} ವರೆಗೆ ಪಡೆಯಬಹುದು.',
    },
    status: {
      not_started: 'KYC ಬಾಕಿ',
      in_progress: 'KYC ಅಪೂರ್ಣ',
      pending_review: 'ಪರಿಶೀಲನೆಯಲ್ಲಿ',
      approved: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      rejected: 'ಕ್ರಮ ಅಗತ್ಯ',
    },
    rejected: {
      title: 'ಮತ್ತೊಮ್ಮೆ ನೋಡಬೇಕು',
      reasonLabel: 'ಕಾರಣ',
      retryCta: 'ವಿವರಗಳನ್ನು ನವೀಕರಿಸು',
    },
    submitCta: 'ಪರಿಶೀಲನೆಗೆ ಸಲ್ಲಿಸು',
    mcc: {
      grocery: 'ಕಿರಾಣಿ / ಜನರಲ್ ಸ್ಟೋರ್',
      restaurant: 'ರೆಸ್ಟೋರೆಂಟ್ / ಕೆಫೆ',
      apparel: 'ಬಟ್ಟೆ ಮತ್ತು ಉಡುಪು',
      electronics: 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಮತ್ತು ಮೊಬೈಲ್',
      pharmacy: 'ಔಷಧಿ ಅಂಗಡಿ / ಮೆಡಿಕಲ್',
      salon: 'ಸೆಲೂನ್ ಮತ್ತು ಸೌಂದರ್ಯ',
      hardware: 'ಹಾರ್ಡ್‌ವೇರ್ ಮತ್ತು ಕಟ್ಟಡ ಸಾಮಗ್ರಿ',
      services: 'ವೃತ್ತಿಪರ ಸೇವೆಗಳು',
      education: 'ಶಿಕ್ಷಣ ಮತ್ತು ತರಬೇತಿ',
      transport: 'ಸಾರಿಗೆ ಮತ್ತು ಪ್ರಯಾಣ',
      online: 'ಆನ್‌ಲೈನ್ / D2C ಮಾರಾಟಗಾರ',
      other: 'ಇತರೆ',
    },
  },

  home: {
    greeting: 'ನಮಸ್ತೆ',
    summary: {
      title: 'ಇಂದಿನ ಸಂಗ್ರಹ',
      collected: 'ಇಂದು ಬಂದದ್ದು',
      txnCount: '{{count}} ಪಾವತಿ',
      txnCount_plural: '{{count}} ಪಾವತಿಗಳು',
      pendingSettlement: 'ಸೆಟಲ್‌ಮೆಂಟ್ ಬಾಕಿ',
      settlementHint: 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆಯಾಗುತ್ತದೆ',
    },
    collectCta: 'ಹಣ ಪಡೆಯಿರಿ',
    quickActions: {
      title: 'ತ್ವರಿತ ಕ್ರಮಗಳು',
      myQr: 'ನನ್ನ QR',
      paymentLink: 'ಪಾವತಿ ಲಿಂಕ್',
      reports: 'ವರದಿಗಳು',
      refund: 'ಮರುಪಾವತಿ',
    },
    recent: {
      title: 'ಇತ್ತೀಚಿನ ಪಾವತಿಗಳು',
      emptyTitle: 'ಇನ್ನೂ ಪಾವತಿ ಇಲ್ಲ',
      emptyBody: 'ಮೊದಲ ಪಾವತಿ ಪಡೆಯಲು ಗ್ರಾಹಕರಿಗೆ ನಿಮ್ಮ QR ತೋರಿಸಿ.',
      emptyCta: 'ನನ್ನ QR ತೋರಿಸು',
    },
    kycNudge: {
      title: 'ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಳಿಸಿ',
      body: 'ಮಿತಿಗಳನ್ನು ತೆಗೆಯಲು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ.',
      cta: 'ಮುಂದುವರಿಸು',
    },
    error: {
      title: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಲೋಡ್ ಆಗಲಿಲ್ಲ',
      body: 'ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    },
  },

  notifications: {
    title: 'ಅಧಿಸೂಚನೆಗಳು',
    emptyTitle: 'ಅಧಿಸೂಚನೆ ಇಲ್ಲ',
    emptyBody: 'ಪಾವತಿ ಮತ್ತು ಸೆಟಲ್‌ಮೆಂಟ್ ಮಾಹಿತಿ ಇಲ್ಲಿ ಕಾಣುತ್ತದೆ.',
  },

  transactions: {
    title: 'ವಹಿವಾಟುಗಳು',
    status: {
      success: 'ಬಂದಿದೆ',
      pending: 'ಬಾಕಿ',
      failed: 'ವಿಫಲ',
      refunded: 'ಮರುಪಾವತಿಸಲಾಗಿದೆ',
      partially_refunded: 'ಭಾಗಶಃ ಮರುಪಾವತಿ',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI ಆ್ಯಪ್',
      payment_link: 'ಪಾವತಿ ಲಿಂಕ್',
      card: 'ಕಾರ್ಡ್',
      netbanking: 'ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್',
      wallet: 'ವಾಲೆಟ್',
    },
    filters: {
      all: 'ಎಲ್ಲಾ',
      success: 'ಬಂದಿದೆ',
      pending: 'ಬಾಕಿ',
      failed: 'ವಿಫಲ',
      refunded: 'ಮರುಪಾವತಿಸಲಾಗಿದೆ',
    },
    searchPlaceholder: 'ಮೊತ್ತ, UTR ಅಥವಾ ಪಾವತಿಸಿದವರನ್ನು ಹುಡುಕಿ',
    emptyTitle: 'ವಹಿವಾಟುಗಳಿಲ್ಲ',
    emptyBody: 'ನಿಮಗೆ ಬರುವ ಪಾವತಿಗಳು ಇಲ್ಲಿ ಕಾಣುತ್ತವೆ.',
    emptyFilteredTitle: 'ಏನೂ ಹೊಂದಿಕೆಯಾಗಿಲ್ಲ',
    emptyFilteredBody: 'ಬೇರೆ ಫಿಲ್ಟರ್ ಅಥವಾ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ ನೋಡಿ.',
    clearFilters: 'ಫಿಲ್ಟರ್ ತೆಗೆಯಿರಿ',
    resultCount: '{{count}} ವಹಿವಾಟು',
    resultCount_plural: '{{count}} ವಹಿವಾಟುಗಳು',
    loadingMore: 'ಇನ್ನಷ್ಟು ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
    endOfList: 'ಇಷ್ಟೇ ಇದೆ',
    detail: {
      title: 'ಪಾವತಿ ವಿವರ',
      amountLabel: 'ಮೊತ್ತ',
      statusLabel: 'ಸ್ಥಿತಿ',
      modeLabel: 'ಯಾವುದರಿಂದ ಬಂದಿದೆ',
      txnIdLabel: 'ವಹಿವಾಟು ID',
      utrLabel: 'UTR / RRN',
      timeLabel: 'ದಿನಾಂಕ ಮತ್ತು ಸಮಯ',
      payerLabel: 'ಪಾವತಿಸಿದವರು',
      noteLabel: 'ಟಿಪ್ಪಣಿ',
      breakdownTitle: 'ವಿವರಣೆ',
      grossLabel: 'ಬಂದ ಮೊತ್ತ',
      feeLabel: 'ಶುಲ್ಕ (MDR)',
      netLabel: 'ನಿಮಗೆ ಸಿಗುತ್ತದೆ',
      noFee: 'ಶುಲ್ಕವಿಲ್ಲ',
      settlementTitle: 'ಸೆಟಲ್‌ಮೆಂಟ್',
      settlementPending: 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ',
      settlementDone: 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಕಳುಹಿಸಲಾಗಿದೆ',
      viewSettlement: 'ಸೆಟಲ್‌ಮೆಂಟ್ ನೋಡಿ',
      refundedLabel: 'ಇಲ್ಲಿಯವರೆಗೆ ಮರುಪಾವತಿ',
      actions: 'ಕ್ರಮಗಳು',
      refund: 'ಮರುಪಾವತಿ',
      shareReceipt: 'ರಸೀದಿ ಹಂಚಿಕೊಳ್ಳಿ',
      raiseDispute: 'ದೂರು ದಾಖಲಿಸಿ',
      reportIssue: 'ಸಮಸ್ಯೆ ತಿಳಿಸಿ',
      notRefundable: 'ಈ ಪಾವತಿಯನ್ನು ಮರುಪಾವತಿಸಲು ಆಗುವುದಿಲ್ಲ',
      receiptMessage: '{{time}} ಕ್ಕೆ {{amount}} ಬಂದಿದೆ. ವಹಿವಾಟು ID: {{id}}.',
    },
  },

  refund: {
    title: 'ಮರುಪಾವತಿ ಮಾಡಿ',
    originalLabel: 'ಮೂಲ ಪಾವತಿ',
    refundableLabel: 'ಮರುಪಾವತಿಗೆ ಲಭ್ಯ',
    alreadyRefunded: '{{amount}} ಈಗಾಗಲೇ ಮರುಪಾವತಿಸಲಾಗಿದೆ',
    typeFull: 'ಪೂರ್ಣ ಮರುಪಾವತಿ',
    typePartial: 'ಭಾಗಶಃ ಮರುಪಾವತಿ',
    fullBody: 'ಪೂರ್ಣ ಮೊತ್ತ ಹಿಂತಿರುಗಿಸಿ',
    partialBody: 'ಮೊತ್ತದ ಒಂದು ಭಾಗ ಹಿಂತಿರುಗಿಸಿ',
    amountLabel: 'ಮರುಪಾವತಿ ಮೊತ್ತ',
    reasonLabel: 'ಕಾರಣ',
    reasonPlaceholder: 'ಮರುಪಾವತಿ ಏಕೆ? (ಐಚ್ಛಿಕ)',
    exceedsRefundable: '{{max}} ಗಿಂತ ಹೆಚ್ಚು ಮರುಪಾವತಿಸಲು ಆಗುವುದಿಲ್ಲ',
    tooLow: '{{min}} ಗಿಂತ ಹೆಚ್ಚಿನ ಮೊತ್ತ ನಮೂದಿಸಿ',
    confirmCta: '{{amount}} ಮರುಪಾವತಿಸಿ',
    reauthReason: '{{amount}} ಮರುಪಾವತಿಯನ್ನು ದೃಢೀಕರಿಸಿ',
    processingTitle: 'ಮರುಪಾವತಿ ನಡೆಯುತ್ತಿದೆ…',
    processingBody: 'ದಯವಿಟ್ಟು ಆ್ಯಪ್ ತೆರೆದಿರಲಿ.',
    successTitle: 'ಮರುಪಾವತಿ ಆರಂಭವಾಗಿದೆ',
    successBody: '{{amount}} ಗ್ರಾಹಕರಿಗೆ ಹಿಂತಿರುಗಿಸಲಾಗುತ್ತಿದೆ. ಸಾಮಾನ್ಯವಾಗಿ 3-5 ಕೆಲಸದ ದಿನ ಬೇಕಾಗುತ್ತದೆ.',
    successDone: 'ಮುಗಿದಿದೆ',
    offlineTitle: 'ಇಂಟರ್ನೆಟ್ ಇಲ್ಲ',
    offlineBody: 'ಮರುಪಾವತಿಗೆ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಬೇಕು.',
    notEligibleTitle: 'ಮರುಪಾವತಿಸಲು ಆಗುವುದಿಲ್ಲ',
    notEligibleBody: 'ಯಶಸ್ವಿ ಪಾವತಿಗಳನ್ನು ಮಾತ್ರ ಮರುಪಾವತಿಸಬಹುದು.',
  },

  appLock: {
    title: 'ನೀವೇ ಎಂದು ದೃಢೀಕರಿಸಿ',
    biometricPrompt: 'ದೃಢೀಕರಿಸಲು ಬೆರಳಚ್ಚು ಅಥವಾ ಮುಖ ಬಳಸಿ',
    biometricFailed: 'ಪರಿಶೀಲಿಸಲು ಆಗಲಿಲ್ಲ. ಬದಲಿಗೆ PIN ನಮೂದಿಸಿ.',
    usePin: 'PIN ಬಳಸಿ',
    pinIncorrect: 'ತಪ್ಪು PIN. {{count}} ಪ್ರಯತ್ನ ಉಳಿದಿದೆ.',
    lockedOut: 'ಹಲವು ಬಾರಿ ತಪ್ಪು PIN. ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.',
    setupTitle: 'ಆ್ಯಪ್ PIN ರಚಿಸಿ',
    setupBody: 'ಮರುಪಾವತಿಯಂತಹ ಮುಖ್ಯ ಕ್ರಮಗಳಿಗೆ ಅನುಮತಿ ನೀಡಲು {{min}} ಅಂಕಿಯ PIN ಆಯ್ಕೆಮಾಡಿ.',
    confirmTitle: 'PIN ಮತ್ತೆ ನಮೂದಿಸಿ',
    pinMismatch: 'PIN ಹೊಂದಿಕೆಯಾಗಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    pinTooShort: 'PIN ಕನಿಷ್ಠ {{min}} ಅಂಕಿ ಇರಬೇಕು',
    lockedOutSeconds: 'ಹಲವು ಬಾರಿ ತಪ್ಪು PIN. {{count}} ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಪ್ರಯತ್ನಿಸಿ.',
    lockedOutMinutes: 'ಹಲವು ಬಾರಿ ತಪ್ಪು PIN. {{count}} ನಿಮಿಷಗಳಲ್ಲಿ ಪ್ರಯತ್ನಿಸಿ.',
    screenTitle: 'ನಿಮ್ಮ PIN ನಮೂದಿಸಿ',
    screenBody: 'ನಿಮ್ಮ ವ್ಯಾಪಾರ ಮಾಹಿತಿ ನೋಡಲು ಆ್ಯಪ್ ಅನ್‌ಲಾಕ್ ಮಾಡಿ.',
    forgotPinCta: 'PIN ಮರೆತಿರಾ?',
    forgotPinConfirmTitle: 'PIN ಬದಲಿಸಲು ಲಾಗ್ ಔಟ್ ಮಾಡುವುದೇ?',
    forgotPinConfirmBody: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯಿಂದ ಮತ್ತೆ ಲಾಗಿನ್ ಆಗಿ ಹೊಸ PIN ಇಡಬಹುದು.',
    requireLabel: 'ತೆರೆಯುವಾಗ PIN ಕೇಳಿ',
    requireBody: 'ಕೆಲವು ನಿಮಿಷಗಳ ನಂತರ ಆ್ಯಪ್ ತೆರೆದಾಗ PIN ಕೇಳುತ್ತದೆ.',
  },

  reports: {
    title: 'ವರದಿಗಳು',
    chartTitle: 'ಮಾರಾಟದ ಪ್ರವೃತ್ತಿ',
    chartHint: 'ಆ ದಿನದ ಒಟ್ಟು ನೋಡಲು ಬಾರ್ ಒತ್ತಿ',
    chartA11y: 'ಆಯ್ಕೆಮಾಡಿದ ಅವಧಿಯ ಮಾರಾಟ ಚಾರ್ಟ್',
    statsTitle: 'ಸಾರಾಂಶ',
    totalSales: 'ಒಟ್ಟು ಮಾರಾಟ',
    txnCount: 'ಪಾವತಿಗಳು',
    avgTicket: 'ಸರಾಸರಿ ಮಾರಾಟ',
    topMode: 'ಹೆಚ್ಚು ಬಳಸಿದ್ದು',
    bestDay: 'ಅತ್ಯುತ್ತಮ ದಿನ',
    tradingDays: 'ಮಾರಾಟವಾದ ದಿನಗಳು',
    avgPerTradingDay: 'ಮಾರಾಟವಾದ ದಿನದ ಸರಾಸರಿ',
    emptyTitle: 'ಈ ಅವಧಿಯಲ್ಲಿ ಮಾರಾಟ ಇಲ್ಲ',
    emptyBody: 'ಬೇರೆ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ, ಅಥವಾ ಪಾವತಿ ಸ್ವೀಕರಿಸಲು ಆರಂಭಿಸಿ.',
    emptyCta: 'ಹಣ ಪಡೆಯಿರಿ',
    errorTitle: 'ವರದಿ ಲೋಡ್ ಆಗಲಿಲ್ಲ',
    export: {
      cta: 'ವರದಿ ಎಕ್ಸ್‌ಪೋರ್ಟ್ ಮಾಡಿ',
      preparing: 'ಎಕ್ಸ್‌ಪೋರ್ಟ್ ಸಿದ್ಧವಾಗುತ್ತಿದೆ…',
      failed: 'ಎಕ್ಸ್‌ಪೋರ್ಟ್ ರಚಿಸಲು ಆಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      fileName: 'ಮಾರಾಟ ವರದಿ',
      formatNote: 'CSV ಫೈಲ್ ಆಗಿ ಉಳಿಸಲಾಗುತ್ತದೆ, ಇದು Excel ಮತ್ತು Google Sheets ನಲ್ಲಿ ತೆರೆಯುತ್ತದೆ.',
      colDate: 'ದಿನಾಂಕ',
      colSales: 'ಮಾರಾಟ (INR)',
      colCount: 'ಪಾವತಿಗಳು',
      totalsLabel: 'ಒಟ್ಟು',
      periodLabel: 'ಅವಧಿ',
      generatedLabel: 'ರಚಿಸಿದ ಸಮಯ',
    },
    gst: {
      title: 'GST',
      summaryCta: 'GST ಸಾರಾಂಶ ಎಕ್ಸ್‌ಪೋರ್ಟ್ ಮಾಡಿ',
      summaryBody: 'ನಿಮ್ಮ GSTIN ಜೊತೆ ಅವಧಿಯ ಮಾರಾಟ ಸಾರಾಂಶ, ನಿಮ್ಮ ಅಕೌಂಟೆಂಟ್‌ನ GST ಫೈಲಿಂಗ್‌ಗಾಗಿ.',
      noGstinTitle: 'GSTIN ದಾಖಲಾಗಿಲ್ಲ',
      noGstinBody: 'GST ಎಕ್ಸ್‌ಪೋರ್ಟ್‌ನಲ್ಲಿ ಸೇರಿಸಲು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ GSTIN ಸೇರಿಸಿ.',
      invoiceNote: 'ಪ್ರತಿ ಪಾವತಿಯ ತೆರಿಗೆ ಸರಕುಪಟ್ಟಿಗೆ ಗ್ರಾಹಕರ ವಿವರ ಮತ್ತು ವಸ್ತುಗಳ ಪಟ್ಟಿ ಬೇಕು, ಆದ್ದರಿಂದ ಅವು ಸರಕುಪಟ್ಟಿ ಸೌಲಭ್ಯದಿಂದ ನೀಡಲಾಗುತ್ತವೆ, ಪಾವತಿ ದಾಖಲೆಗಳಿಂದ ಅಲ್ಲ.',
      gstinLabel: 'GSTIN',
      fileName: 'GST ಸಾರಾಂಶ',
      colField: 'ವಿವರ',
      colValue: 'ಮೌಲ್ಯ',
      rowBusiness: 'ವ್ಯಾಪಾರದ ಹೆಸರು',
      rowGstin: 'GSTIN',
      rowPeriodFrom: 'ಅವಧಿ ಇಂದ',
      rowPeriodTo: 'ಅವಧಿ ವರೆಗೆ',
      rowTotalSales: 'ಒಟ್ಟು ಮಾರಾಟ (INR)',
      rowTxnCount: 'ಪಾವತಿಗಳ ಸಂಖ್ಯೆ',
      rowNote: 'ಟಿಪ್ಪಣಿ',
      noteValue: 'ಬಂದ ಪಾವತಿಗಳ ಸಾರಾಂಶ. ಇದು ತೆರಿಗೆ ಸರಕುಪಟ್ಟಿ ಅಲ್ಲ.',
    },
  },

  more: {
    title: 'ಇನ್ನಷ್ಟು',
    reports: 'ವರದಿಗಳು',
    reportsBody: 'ಮಾರಾಟದ ಪ್ರವೃತ್ತಿ ಮತ್ತು ಎಕ್ಸ್‌ಪೋರ್ಟ್',
    profile: 'ವ್ಯಾಪಾರ ಪ್ರೊಫೈಲ್',
    profileBody: 'ನಿಮ್ಮ ವಿವರ, ಬ್ಯಾಂಕ್ ಖಾತೆ ಮತ್ತು KYC',
    staff: 'ಸಿಬ್ಬಂದಿ',
    staffBody: 'ಪಾವತಿ ಸ್ವೀಕರಿಸಬಲ್ಲ ಜನರನ್ನು ಸೇರಿಸಿ',
    support: 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    supportBody: 'ಪ್ರಶ್ನೋತ್ತರ, ದೂರು ದಾಖಲಿಸಿ, ಸಂಪರ್ಕಿಸಿ',
    settings: 'ಸೆಟ್ಟಿಂಗ್',
    settingsBody: 'ಭಾಷೆ, ಧ್ವನಿ, ಅಧಿಸೂಚನೆ, ಆ್ಯಪ್ ಲಾಕ್',
  },

  profile: {
    title: 'ವ್ಯಾಪಾರ ಪ್ರೊಫೈಲ್',
    businessTitle: 'ವ್ಯಾಪಾರದ ವಿವರ',
    nameLabel: 'ವ್ಯಾಪಾರದ ಹೆಸರು',
    categoryLabel: 'ವ್ಯಾಪಾರ ವಿಭಾಗ',
    addressLabel: 'ವಿಳಾಸ',
    gstinLabel: 'GSTIN',
    gstinEmpty: 'ಸೇರಿಸಿಲ್ಲ',
    panLabel: 'PAN',
    mobileLabel: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    vpaLabel: 'ನಿಮ್ಮ UPI ID',
    kycTitle: 'ಪರಿಶೀಲನೆ',
    kycPendingBody: 'ನಾವು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸುತ್ತಿದ್ದೇವೆ.',
    kycRejectedBody: 'ನಿಮ್ಮ ಪರಿಶೀಲನೆಗೆ ಗಮನ ಬೇಕು. ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ.',
    bankTitle: 'ಸೆಟಲ್‌ಮೆಂಟ್ ಖಾತೆ',
    bankAccountLabel: 'ಖಾತೆ',
    bankIfscLabel: 'IFSC',
    bankHolderLabel: 'ಖಾತೆದಾರ',
    bankChangeCta: 'ಸೆಟಲ್‌ಮೆಂಟ್ ಖಾತೆ ಬದಲಾಯಿಸಿ',
    bankChangeWarning: 'ಮುಂದಿನ ಎಲ್ಲಾ ಸೆಟಲ್‌ಮೆಂಟ್ ಹೊಸ ಖಾತೆಗೆ ಹೋಗುತ್ತದೆ. ₹1 ಕಳುಹಿಸಿ ಅದನ್ನು ಪರಿಶೀಲಿಸುತ್ತೇವೆ.',
    editCta: 'ವಿವರ ಬದಲಾಯಿಸಿ',
    editTitle: 'ವ್ಯಾಪಾರದ ವಿವರ ಬದಲಾಯಿಸಿ',
    saveCta: 'ಬದಲಾವಣೆ ಉಳಿಸಿ',
    saved: 'ಬದಲಾವಣೆ ಉಳಿಸಲಾಗಿದೆ',
    bankEditTitle: 'ಸೆಟಲ್‌ಮೆಂಟ್ ಖಾತೆ ಬದಲಾಯಿಸಿ',
    bankReauthReason: 'ಸೆಟಲ್‌ಮೆಂಟ್ ಖಾತೆ ಬದಲಾವಣೆಯನ್ನು ದೃಢೀಕರಿಸಿ',
    bankSubmitCta: 'ಪರಿಶೀಲಿಸಿ ಉಳಿಸಿ',
    bankVerifying: 'ನಿಮ್ಮ ಖಾತೆ ಪರಿಶೀಲಿಸುತ್ತಿದೆ…',
    bankSaved: 'ಸೆಟಲ್‌ಮೆಂಟ್ ಖಾತೆ ನವೀಕರಿಸಲಾಗಿದೆ',
    readOnlyNote: 'PAN ಮತ್ತು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಇಲ್ಲಿ ಬದಲಾಯಿಸಲು ಆಗುವುದಿಲ್ಲ. ತಪ್ಪಿದ್ದರೆ ಬೆಂಬಲ ಸಂಪರ್ಕಿಸಿ.',
    offlineNote: 'ಪ್ರೊಫೈಲ್ ಬದಲಾಯಿಸಲು ಇಂಟರ್ನೆಟ್ ಬೇಕು.',
  },

  staff: {
    title: 'ಸಿಬ್ಬಂದಿ',
    subtitle: 'ನಿಮ್ಮ ವ್ಯಾಪಾರಕ್ಕೆ ಹಣ ಪಡೆಯಬಲ್ಲ ಜನರು',
    addCta: 'ಸಿಬ್ಬಂದಿ ಸೇರಿಸಿ',
    emptyTitle: 'ಸಿಬ್ಬಂದಿ ಸೇರಿಸಿಲ್ಲ',
    emptyBody: 'ನಿಮ್ಮ ಪರವಾಗಿ ಹಣ ಪಡೆಯಲು ಮ್ಯಾನೇಜರ್ ಅಥವಾ ಕ್ಯಾಷಿಯರ್ ಸೇರಿಸಿ.',
    errorTitle: 'ಸಿಬ್ಬಂದಿ ಲೋಡ್ ಆಗಲಿಲ್ಲ',
    countLabel: '{{count}} ವ್ಯಕ್ತಿ',
    countLabel_plural: '{{count}} ಜನ',
    roles: {
      manager: 'ಮ್ಯಾನೇಜರ್',
      cashier: 'ಕ್ಯಾಷಿಯರ್',
    },
    roleHelp: {
      manager: 'ಹಣ ಪಡೆಯಬಹುದು, ವರದಿ ನೋಡಬಹುದು, ಮರುಪಾವತಿ ಮಾಡಬಹುದು',
      cashier: 'ಹಣ ಮಾತ್ರ ಪಡೆಯಬಹುದು',
    },
    addTitle: 'ಸಿಬ್ಬಂದಿ ಸೇರಿಸಿ',
    nameLabel: 'ಪೂರ್ಣ ಹೆಸರು',
    namePlaceholder: 'ಯಾವ ಹೆಸರಿನಿಂದ ಕರೆಯುತ್ತಾರೆ',
    nameRequired: 'ಅವರ ಹೆಸರು ನಮೂದಿಸಿ',
    mobileLabel: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    mobileRequired: 'ಅವರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    mobileInvalid: 'ಸರಿಯಾದ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    mobileDuplicate: 'ಈ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಈಗಾಗಲೇ ಸೇರಿಸಲಾಗಿದೆ',
    roleLabel: 'ಪಾತ್ರ',
    addSubmit: 'ಸೇರಿಸಿ',
    added: '{{name}} ಸೇರಿಸಲಾಗಿದೆ',
    editRoleTitle: '{{name}} ಪಾತ್ರ ಬದಲಾಯಿಸಿ',
    roleSaved: 'ಪಾತ್ರ ನವೀಕರಿಸಲಾಗಿದೆ',
    removeCta: 'ತೆಗೆದುಹಾಕಿ',
    removeConfirmTitle: '{{name}} ತೆಗೆದುಹಾಕುವುದೇ?',
    removeConfirmBody: 'ಅವರು ಇನ್ನು ನಿಮ್ಮ ಪರವಾಗಿ ಹಣ ಪಡೆಯಲು ಆಗುವುದಿಲ್ಲ.',
    removed: '{{name}} ತೆಗೆದುಹಾಕಲಾಗಿದೆ',
    offlineNote: 'ಸಿಬ್ಬಂದಿ ಸೇರಿಸಲು ಅಥವಾ ತೆಗೆಯಲು ಇಂಟರ್ನೆಟ್ ಬೇಕು.',
  },

  settings: {
    title: 'ಸೆಟ್ಟಿಂಗ್',
    languageTitle: 'ಭಾಷೆ',
    languageBody: 'ಆ್ಯಪ್‌ಗೆ ಮತ್ತು ಪಾವತಿ ಪ್ರಕಟಣೆಗೆ',
    audioTitle: 'ಪಾವತಿ ಪ್ರಕಟಣೆ',
    audioEnabledLabel: 'ಪಾವತಿಯನ್ನು ಗಟ್ಟಿಯಾಗಿ ಪ್ರಕಟಿಸಿ',
    audioEnabledBody: 'ಪಾವತಿ ಬಂದಾಗ ಮೊತ್ತ ಕೇಳಿ, ಪರದೆ ನೋಡುವ ಅಗತ್ಯವಿಲ್ಲ',
    audioLanguageLabel: 'ಪ್ರಕಟಣೆಯ ಭಾಷೆ',
    audioVolumeNote: 'ಪ್ರಕಟಣೆಯ ಶಬ್ದ ನಿಮ್ಮ ಫೋನಿನ ಮೀಡಿಯಾ ವಾಲ್ಯೂಮ್ ಅನುಸರಿಸುತ್ತದೆ.',
    notificationsTitle: 'ಅಧಿಸೂಚನೆಗಳು',
    pushLabel: 'ಆ್ಯಪ್ ಅಧಿಸೂಚನೆ',
    smsLabel: 'SMS',
    whatsappLabel: 'WhatsApp',
    securityTitle: 'ಸುರಕ್ಷತೆ',
    pinLabel: 'ಆ್ಯಪ್ PIN',
    pinSetBody: 'ಮರುಪಾವತಿಯಂತಹ ಮುಖ್ಯ ಕ್ರಮಗಳಿಗೆ ಅನುಮತಿ ನೀಡಲು',
    pinNotSetBody: 'ಇನ್ನೂ ಸೆಟ್ ಮಾಡಿಲ್ಲ',
    pinSetCta: 'PIN ಸೆಟ್ ಮಾಡಿ',
    pinChangeCta: 'ಬದಲಾಯಿಸಿ',
    pinChanged: 'PIN ನವೀಕರಿಸಲಾಗಿದೆ',
    pinReauthReason: 'PIN ಬದಲಾಯಿಸುವ ಮೊದಲು ನೀವೇ ಎಂದು ದೃಢೀಕರಿಸಿ',
    biometricLabel: 'ಬೆರಳಚ್ಚು ಅಥವಾ ಮುಖ',
    biometricAvailableBody: 'ಸಾಧ್ಯವಾದಲ್ಲಿ PIN ಬದಲಿಗೆ ಬಳಸಲಾಗುತ್ತದೆ',
    biometricUnavailableBody: 'ಈ ಫೋನಿನಲ್ಲಿ ಸೆಟ್ ಮಾಡಿಲ್ಲ',
    themeTitle: 'ಕಾಣಿಸುವಿಕೆ',
    themeLightOnly: 'ಆ್ಯಪ್ ಸದ್ಯಕ್ಕೆ ತಿಳಿ ಥೀಮ್ ಮಾತ್ರ ಬಳಸುತ್ತದೆ.',
    aboutTitle: 'ಆ್ಯಪ್ ಬಗ್ಗೆ',
    versionLabel: 'ಆ್ಯಪ್ ಆವೃತ್ತಿ',
    logoutCta: 'ಲಾಗ್ ಔಟ್',
    logoutConfirmTitle: 'ಲಾಗ್ ಔಟ್ ಮಾಡುವುದೇ?',
    logoutConfirmBody: 'ಮತ್ತೆ ಲಾಗಿನ್ ಆಗಲು ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಮತ್ತು OTP ಬೇಕು.',
    saveFailed: 'ಈ ಬದಲಾವಣೆ ಉಳಿಸಲು ಆಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  },

  support: {
    title: 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    searchPlaceholder: 'ಸಹಾಯ ಹುಡುಕಿ',
    faqTitle: 'ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು',
    faqEmptyTitle: 'ಹೊಂದುವ ಪ್ರಶ್ನೆ ಇಲ್ಲ',
    faqEmptyBody: 'ಬೇರೆ ಪದ ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ ದೂರು ದಾಖಲಿಸಿ ನಾವು ಸಹಾಯ ಮಾಡುತ್ತೇವೆ.',
    contactTitle: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    callCta: 'ಬೆಂಬಲಕ್ಕೆ ಕರೆ ಮಾಡಿ',
    callBody: 'ಪ್ರತಿದಿನ, ಬೆಳಿಗ್ಗೆ 9 ರಿಂದ ರಾತ್ರಿ 9',
    whatsappCta: 'WhatsApp ನಲ್ಲಿ ಮಾತನಾಡಿ',
    whatsappBody: 'ಸಾಮಾನ್ಯವಾಗಿ ಒಂದು ಗಂಟೆಯಲ್ಲಿ ಉತ್ತರ',
    ticketsTitle: 'ನಿಮ್ಮ ದೂರುಗಳು',
    ticketsEmptyTitle: 'ಇನ್ನೂ ದೂರು ಇಲ್ಲ',
    ticketsEmptyBody: 'ದೂರು ದಾಖಲಿಸಿ, ನಾವು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.',
    raiseCta: 'ದೂರು ದಾಖಲಿಸಿ',
    ticketStatus: {
      open: 'ತೆರೆದಿದೆ',
      in_progress: 'ನಡೆಯುತ್ತಿದೆ',
      resolved: 'ಪರಿಹಾರವಾಗಿದೆ',
      closed: 'ಮುಚ್ಚಲಾಗಿದೆ',
    },
    raiseTitle: 'ದೂರು ದಾಖಲಿಸಿ',
    subjectLabel: 'ಇದು ಯಾವುದರ ಬಗ್ಗೆ?',
    subjectPlaceholder: 'ಚಿಕ್ಕ ಸಾರಾಂಶ',
    subjectRequired: 'ಚಿಕ್ಕ ಸಾರಾಂಶ ನಮೂದಿಸಿ',
    bodyLabel: 'ಇನ್ನಷ್ಟು ಹೇಳಿ',
    bodyPlaceholder: 'ಏನಾಯಿತು? ಸಾಧ್ಯವಾದರೆ ಮೊತ್ತ ಅಥವಾ ವಹಿವಾಟು ID ಬರೆಯಿರಿ.',
    bodyRequired: 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ',
    raiseSubmit: 'ಕಳುಹಿಸಿ',
    raised: 'ದೂರು ದಾಖಲಾಗಿದೆ. ನಾವು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.',
    offlineNote: 'ದೂರು ದಾಖಲಿಸಲು ಇಂಟರ್ನೆಟ್ ಬೇಕು.',
    contactFailed: 'ಇದನ್ನು ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲಿ ತೆರೆಯಲು ಆಗಲಿಲ್ಲ. ನೀವು {{value}} ಗೆ ಕರೆ ಮಾಡಬಹುದು.',
    grievance: {
      title: 'ದೂರನ್ನು ಮೇಲಕ್ಕೆ ಕಳುಹಿಸಿ',
      body: 'ನಿಮ್ಮ ಸಮಸ್ಯೆ ಪರಿಹಾರವಾಗದಿದ್ದರೆ ಅದನ್ನು ಮೇಲಕ್ಕೆ ಕಳುಹಿಸಬಹುದು. ಪ್ರತಿ ಹಂತಕ್ಕೆ ಉತ್ತರಿಸುವ ಸಮಯ ಇದೆ.',
      level1Title: 'ಹಂತ 1 — ಗ್ರಾಹಕ ಬೆಂಬಲ',
      level1Body: 'ಮೇಲೆ ದೂರು ದಾಖಲಿಸಿ. 24 ಗಂಟೆಯಲ್ಲಿ ಉತ್ತರಿಸುತ್ತೇವೆ.',
      level2Title: 'ಹಂತ 2 — ನೋಡಲ್ ಅಧಿಕಾರಿ',
      level2Body: '7 ದಿನದಲ್ಲಿ ಪರಿಹಾರವಾಗದಿದ್ದರೆ ನಮ್ಮ ನೋಡಲ್ ಅಧಿಕಾರಿಗೆ ಬರೆಯಿರಿ.',
      level3Title: 'ಹಂತ 3 — RBI ಒಂಬುಡ್ಸ್‌ಮನ್',
      level3Body: '30 ದಿನದಲ್ಲಿ ಪರಿಹಾರವಾಗದಿದ್ದರೆ ಡಿಜಿಟಲ್ ವಹಿವಾಟುಗಳ RBI ಒಂಬುಡ್ಸ್‌ಮನ್ ಸಂಪರ್ಕಿಸಬಹುದು.',
      officerLabel: 'ದೂರು ಅಧಿಕಾರಿ',
      emailLabel: 'ಇಮೇಲ್',
      phoneLabel: 'ಫೋನ್',
      rbiPortalCta: 'RBI ದೂರು ಪೋರ್ಟಲ್ ತೆರೆಯಿರಿ',
      placeholderNote: 'ಈ ಸಂಪರ್ಕ ವಿವರ ತಾತ್ಕಾಲಿಕ. ಬಿಡುಗಡೆಗೂ ಮುನ್ನ ನಿಮ್ಮ ನೋಂದಾಯಿತ ದೂರು ಅಧಿಕಾರಿಯ ವಿವರ ಹಾಕಿ.',
    },
    faq: {
      q1: 'ನನಗೆ ಹಣ ಯಾವಾಗ ಸಿಗುತ್ತದೆ?',
      a1: 'ಇಂದು ಬಂದ ಪಾವತಿಗಳು ಮುಂದಿನ ಕೆಲಸದ ದಿನ ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ. ಸೆಟಲ್‌ಮೆಂಟ್‌ನಲ್ಲಿ ನೋಡಬಹುದು. ಹಣ ಬೇಗ ಬೇಕಿದ್ದರೆ ಬಾಕಿ ಬ್ಯಾಚ್‌ನಲ್ಲಿ "ಈಗಲೇ ಸೆಟಲ್ ಮಾಡಿ" ಬಳಸಿ — ಸಣ್ಣ ಶುಲ್ಕ ಇರುತ್ತದೆ.',
      q2: 'ಗ್ರಾಹಕರು ಪಾವತಿಸಿದರು ಆದರೆ ಪ್ರಕಟಣೆ ಕೇಳಿಸಲಿಲ್ಲ. ಏನು ಮಾಡಬೇಕು?',
      a2: 'ವಹಿವಾಟು ತೆರೆದು ಪಾವತಿ ಪಟ್ಟಿಯಲ್ಲಿದೆಯೇ ನೋಡಿ. ಇದ್ದರೆ ಹಣ ನಿಮ್ಮದೇ, ಪ್ರಕಟಣೆ ಕೇಳಿಸದಿದ್ದರೂ. ಸೆಟ್ಟಿಂಗ್‌ನಲ್ಲಿ ಪ್ರಕಟಣೆ ಆನ್ ಇದೆಯೇ, ಫೋನ್ ಸೈಲೆಂಟ್‌ನಲ್ಲಿಲ್ಲವೇ ನೋಡಿ.',
      q3: 'ಗ್ರಾಹಕರಿಗೆ ಹಣ ಹಿಂತಿರುಗಿಸುವುದು ಹೇಗೆ?',
      a3: 'ವಹಿವಾಟು ತೆರೆದು, ಪಾವತಿಯನ್ನು ಒತ್ತಿ, ನಂತರ ಮರುಪಾವತಿ ಒತ್ತಿ. ಪೂರ್ಣ ಅಥವಾ ಭಾಗಶಃ ಹಿಂತಿರುಗಿಸಬಹುದು. ದೃಢೀಕರಣಕ್ಕೆ ಆ್ಯಪ್ PIN ಅಥವಾ ಬೆರಳಚ್ಚು ಕೇಳುತ್ತೇವೆ.',
      q4: 'ನಾನು ಎಷ್ಟು ಪಡೆಯಬಹುದು ಎಂಬುದಕ್ಕೆ ಮಿತಿ ಏಕೆ?',
      a4: 'ಪರಿಶೀಲನೆ ಮುಗಿಯುವವರೆಗೆ ದಿನಕ್ಕೆ ಒಂದು ಮಿತಿಯವರೆಗೆ ಪಡೆಯಬಹುದು. ಮಿತಿ ತೆಗೆಯಲು ವ್ಯಾಪಾರ ಪ್ರೊಫೈಲ್‌ನಿಂದ KYC ಪೂರ್ಣಗೊಳಿಸಿ.',
      q5: 'ಬೇರೆಯವರು ನನ್ನ ಪರವಾಗಿ ಹಣ ಪಡೆಯಬಹುದೇ?',
      a5: 'ಹೌದು. ಅವರನ್ನು ಸಿಬ್ಬಂದಿಯಲ್ಲಿ ಸೇರಿಸಿ. ಕ್ಯಾಷಿಯರ್ ಹಣ ಮಾತ್ರ ಪಡೆಯಬಹುದು; ಮ್ಯಾನೇಜರ್ ವರದಿಯನ್ನೂ ನೋಡಬಹುದು, ಮರುಪಾವತಿಯನ್ನೂ ಮಾಡಬಹುದು.',
      q6: 'ಹಣ ಬರುವ ಬ್ಯಾಂಕ್ ಖಾತೆ ಬದಲಾಯಿಸುವುದು ಹೇಗೆ?',
      a6: 'ವ್ಯಾಪಾರ ಪ್ರೊಫೈಲ್‌ಗೆ ಹೋಗಿ "ಸೆಟಲ್‌ಮೆಂಟ್ ಖಾತೆ ಬದಲಾಯಿಸಿ" ಒತ್ತಿ. ಸುರಕ್ಷತೆಗಾಗಿ ನಿಮ್ಮ PIN ಅಥವಾ ಬೆರಳಚ್ಚು ಬೇಕು, ಮತ್ತು ಹೊಸ ಖಾತೆಯನ್ನು ₹1 ಕಳುಹಿಸಿ ಪರಿಶೀಲಿಸುತ್ತೇವೆ.',
    },
  },

  dateRange: {
    label: 'ದಿನಾಂಕ ವ್ಯಾಪ್ತಿ',
    all: 'ಎಲ್ಲಾ ಸಮಯ',
    today: 'ಇಂದು',
    yesterday: 'ನಿನ್ನೆ',
    last7: 'ಕಳೆದ 7 ದಿನ',
    last30: 'ಕಳೆದ 30 ದಿನ',
    thisMonth: 'ಈ ತಿಂಗಳು',
    custom: 'ನಿಮ್ಮ ವ್ಯಾಪ್ತಿ',
    from: 'ಇಂದ',
    to: 'ವರೆಗೆ',
  },

  settlements: {
    title: 'ಸೆಟಲ್‌ಮೆಂಟ್',
    status: {
      pending: 'ಬಾಕಿ',
      processing: 'ನಡೆಯುತ್ತಿದೆ',
      settled: 'ಜಮೆಯಾಗಿದೆ',
      failed: 'ವಿಫಲ',
    },
    tabs: {
      pending: 'ಬಾಕಿ',
      settled: 'ಜಮೆಯಾಗಿದೆ',
    },
    batchLabel: '{{count}} ಪಾವತಿಯ ಬ್ಯಾಚ್',
    batchLabel_plural: '{{count}} ಪಾವತಿಗಳ ಬ್ಯಾಚ್',
    utrLabel: 'UTR',
    expectedLabel: 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಬರಬೇಕಿರುವುದು',
    creditedLabel: 'ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆ',
    emptyPendingTitle: 'ಬಾಕಿ ಏನೂ ಇಲ್ಲ',
    emptyPendingBody: 'ಇಂದು ಬಂದ ಪಾವತಿಗಳು ನಾಳೆ ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ.',
    emptySettledTitle: 'ಇನ್ನೂ ಸೆಟಲ್‌ಮೆಂಟ್ ಇಲ್ಲ',
    emptySettledBody: 'ಹಣ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ತಲುಪಿದ ನಂತರ UTR ಜೊತೆ ಇಲ್ಲಿ ಕಾಣುತ್ತದೆ.',
    errorTitle: 'ಸೆಟಲ್‌ಮೆಂಟ್ ಲೋಡ್ ಆಗಲಿಲ್ಲ',
    t1Note: 'ಮುಂದಿನ ಕೆಲಸದ ದಿನ ಹಣ ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ತಲುಪುತ್ತದೆ.',
    detail: {
      title: 'ಸೆಟಲ್‌ಮೆಂಟ್ ವಿವರ',
      breakdownTitle: 'ವಿವರಣೆ',
      grossLabel: 'ಒಟ್ಟು ಬಂದಿದೆ',
      feeLabel: 'ಶುಲ್ಕಗಳು',
      netLabel: 'ಬ್ಯಾಂಕಿಗೆ ಜಮೆ',
      bankTitle: 'ಬ್ಯಾಂಕ್ ಖಾತೆ',
      accountLabel: 'ಖಾತೆ',
      ifscLabel: 'IFSC',
      utrLabel: 'UTR / ಉಲ್ಲೇಖ',
      createdLabel: 'ಬ್ಯಾಚ್ ರಚನೆಯಾಯಿತು',
      settledLabel: 'ಜಮೆಯಾದ ದಿನ',
      txnTitle: 'ಈ ಬ್ಯಾಚ್‌ನ ಪಾವತಿಗಳು',
      txnCount: '{{count}} ಪಾವತಿ',
      txnCount_plural: '{{count}} ಪಾವತಿಗಳು',
      reconcileNote: 'ಕೆಳಗಿನ ಎಲ್ಲಾ ಪಾವತಿಗಳು ಸೇರಿ ಒಟ್ಟು ಮೊತ್ತವಾಗುತ್ತದೆ.',
      noTxnTitle: 'ಪಾವತಿ ಪಟ್ಟಿ ಇಲ್ಲ',
      noTxnBody: 'ಈ ಬ್ಯಾಚ್‌ನ ಪ್ರತ್ಯೇಕ ಪಾವತಿಗಳು ಲಭ್ಯವಿಲ್ಲ.',
    },
    statement: {
      download: 'ಸ್ಟೇಟ್‌ಮೆಂಟ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
      preparing: 'ಸ್ಟೇಟ್‌ಮೆಂಟ್ ಸಿದ್ಧವಾಗುತ್ತಿದೆ…',
      failed: 'ಸ್ಟೇಟ್‌ಮೆಂಟ್ ರಚಿಸಲು ಆಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      fileName: 'ಸೆಟಲ್‌ಮೆಂಟ್ ಸ್ಟೇಟ್‌ಮೆಂಟ್',
      colDate: 'ದಿನಾಂಕ',
      colTime: 'ಸಮಯ',
      colTxnId: 'ವಹಿವಾಟು ID',
      colUtr: 'UTR',
      colMode: 'ವಿಧಾನ',
      colStatus: 'ಸ್ಥಿತಿ',
      colGross: 'ಮೊತ್ತ (INR)',
      colFee: 'ಶುಲ್ಕ (INR)',
      colNet: 'ನಿವ್ವಳ (INR)',
      totalsLabel: 'ಒಟ್ಟು',
      formatNote: 'CSV ಫೈಲ್ ಆಗಿ ಉಳಿಸಲಾಗುತ್ತದೆ, ಇದು Excel ಮತ್ತು Google Sheets ನಲ್ಲಿ ತೆರೆಯುತ್ತದೆ.',
    },
    instant: {
      cta: 'ಈಗಲೇ ಸೆಟಲ್ ಮಾಡಿ',
      sheetTitle: 'ತಕ್ಷಣ ಸೆಟಲ್ ಮಾಡಿ',
      sheetBody: 'ನಾಳೆಯವರೆಗೆ ಕಾಯದೆ ಈ ಹಣವನ್ನು ಕೆಲವೇ ನಿಮಿಷಗಳಲ್ಲಿ ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಪಡೆಯಿರಿ.',
      netLabel: 'ಸೆಟಲ್‌ಮೆಂಟ್ ಮೊತ್ತ',
      feeLabel: 'ತಕ್ಷಣ ಸೆಟಲ್‌ಮೆಂಟ್ ಶುಲ್ಕ ({{percent}}%)',
      gstLabel: 'ಶುಲ್ಕದ ಮೇಲಿನ GST',
      payoutLabel: 'ನಿಮಗೆ ಸಿಗುತ್ತದೆ',
      confirmCta: '{{amount}} ಈಗಲೇ ಸೆಟಲ್ ಮಾಡಿ',
      processing: 'ಸೆಟಲ್ ಆಗುತ್ತಿದೆ…',
      successTitle: 'ಹಣ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ',
      successBody: '{{amount}} ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆಯಾಗುತ್ತಿದೆ. ಸಾಮಾನ್ಯವಾಗಿ ಕೆಲವೇ ನಿಮಿಷಗಳಲ್ಲಿ ತಲುಪುತ್ತದೆ.',
      ineligible: {
        already_settled: 'ಈ ಬ್ಯಾಚ್ ಈಗಾಗಲೇ ಸೆಟಲ್ ಆಗಿದೆ.',
        below_minimum: 'ತಕ್ಷಣ ಸೆಟಲ್‌ಮೆಂಟ್‌ಗೆ ಕನಿಷ್ಠ {{min}} ಬೇಕು.',
        failed_batch: 'ಈ ಬ್ಯಾಚ್ ವಿಫಲವಾಗಿದೆ, ತಕ್ಷಣ ಸೆಟಲ್ ಮಾಡಲು ಆಗುವುದಿಲ್ಲ.',
      },
      offlineBody: 'ತಕ್ಷಣ ಸೆಟಲ್‌ಮೆಂಟ್‌ಗೆ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಬೇಕು.',
    },
  },

  collect: {
    title: 'ಹಣ ಪಡೆಯಿರಿ',
    subtitle: 'ನೀವು ಹೇಗೆ ಹಣ ಪಡೆಯಲು ಬಯಸುತ್ತೀರಿ?',
    modes: {
      staticQr: 'ನನ್ನ QR ಕೋಡ್',
      staticQrBody: 'ಯಾವುದೇ ಮೊತ್ತಕ್ಕೆ ಒಂದೇ ಕೋಡ್. ತೋರಿಸಿ ಅಥವಾ ಮುದ್ರಿಸಿ.',
      dynamicQr: 'ಮೊತ್ತ ನಮೂದಿಸಿ',
      dynamicQrBody: 'ನಿರ್ದಿಷ್ಟ ಮೊತ್ತಕ್ಕೆ QR ರಚಿಸಿ.',
      paymentLink: 'ಪಾವತಿ ಲಿಂಕ್',
      paymentLinkBody: 'WhatsApp ಅಥವಾ SMS ನಲ್ಲಿ ಲಿಂಕ್ ಕಳುಹಿಸಿ.',
    },
    staticQr: {
      title: 'ನನ್ನ QR ಕೋಡ್',
      instruction: 'ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಯಾವುದೇ ಮೊತ್ತ ಪಾವತಿಸಲು ಗ್ರಾಹಕರಿಗೆ ಹೇಳಿ.',
      vpaLabel: 'UPI ID',
      noQrTitle: 'QR ಇನ್ನೂ ಸಿದ್ಧವಿಲ್ಲ',
      noQrBody: 'QR ಕೋಡ್ ಪಡೆಯಲು ಬ್ಯಾಂಕ್ ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಳಿಸಿ.',
      noQrCta: 'ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಳಿಸಿ',
      offlineUsable: 'ನಿಮ್ಮ QR ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆಯೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ.',
    },
    amount: {
      title: 'ಮೊತ್ತ ನಮೂದಿಸಿ',
      generateQr: 'QR ರಚಿಸಿ',
      createLink: 'ಲಿಂಕ್ ರಚಿಸಿ',
      noteLabel: 'ಟಿಪ್ಪಣಿ',
      notePlaceholder: 'ಯಾವುದಕ್ಕಾಗಿ? (ಐಚ್ಛಿಕ)',
      tooLow: '{{min}} ಗಿಂತ ಹೆಚ್ಚಿನ ಮೊತ್ತ ನಮೂದಿಸಿ',
      limitExceeded: 'ಪರಿಶೀಲನೆ ಮುಗಿಯುವವರೆಗೆ ದಿನದ ಮಿತಿ {{limit}}',
      upiCap: 'ಒಂದು UPI ಪಾವತಿಗೆ ಗರಿಷ್ಠ {{max}}',
    },
    dynamicQr: {
      title: 'ಪಾವತಿಸಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      waiting: 'ಪಾವತಿಗಾಗಿ ಕಾಯುತ್ತಿದೆ…',
      waitingBody: 'ಈ ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಗ್ರಾಹಕರಿಗೆ ಹೇಳಿ.',
      expiresIn: '{{time}} ನಲ್ಲಿ ಅವಧಿ ಮುಗಿಯುತ್ತದೆ',
      expiredTitle: 'QR ಅವಧಿ ಮುಗಿದಿದೆ',
      expiredBody: 'ಈ ಕೋಡ್ ಇನ್ನು ಮಾನ್ಯವಿಲ್ಲ. ಹೊಸದನ್ನು ರಚಿಸಿ.',
      newQr: 'ಹೊಸ QR ರಚಿಸಿ',
      cancel: 'ರದ್ದು',
      checkingSlowly: 'ಇನ್ನೂ ಪರಿಶೀಲಿಸುತ್ತಿದೆ. ನಿಮ್ಮ ಸಂಪರ್ಕ ನಿಧಾನವಾಗಿದೆ.',
      failedTitle: 'ಪಾವತಿ ವಿಫಲ',
      failedBody: 'ಗ್ರಾಹಕರ ಪಾವತಿ ಆಗಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಲು ಹೇಳಿ.',
      offlineTitle: 'ಇಂಟರ್ನೆಟ್ ಇಲ್ಲ',
      offlineBody: 'ನಿಗದಿತ ಮೊತ್ತದ QR ಗೆ ಇಂಟರ್ನೆಟ್ ಬೇಕು. ಬದಲಿಗೆ ನಿಮ್ಮ QR ಕೋಡ್ ಬಳಸಿ.',
      useStaticQr: 'ನನ್ನ QR ಕೋಡ್ ಬಳಸಿ',
    },
    link: {
      title: 'ಪಾವತಿ ಲಿಂಕ್',
      createdTitle: 'ಲಿಂಕ್ ಸಿದ್ಧ',
      createdBody: 'ಇದನ್ನು ಗ್ರಾಹಕರಿಗೆ ಕಳುಹಿಸಿ. 24 ಗಂಟೆಯಲ್ಲಿ ಅವಧಿ ಮುಗಿಯುತ್ತದೆ.',
      copy: 'ಲಿಂಕ್ ನಕಲಿಸಿ',
      copied: 'ಲಿಂಕ್ ನಕಲಾಗಿದೆ',
      shareVia: 'ಲಿಂಕ್ ಹಂಚಿಕೊಳ್ಳಿ',
      newLink: 'ಇನ್ನೊಂದು ರಚಿಸಿ',
      shareMessage: 'ಈ ಲಿಂಕ್ ಬಳಸಿ {{amount}} ಪಾವತಿಸಿ: {{url}}',
    },
    success: {
      title: 'ಪಾವತಿ ಬಂದಿದೆ!',
      amountLabel: 'ಬಂದ ಮೊತ್ತ',
      txnIdLabel: 'ವಹಿವಾಟು ID',
      timeLabel: 'ಸಮಯ',
      payerLabel: 'ಪಾವತಿಸಿದವರು',
      utrLabel: 'UPI ಉಲ್ಲೇಖ',
      shareReceipt: 'ರಸೀದಿ ಹಂಚಿಕೊಳ್ಳಿ',
      newPayment: 'ಹೊಸ ಪಾವತಿ',
      done: 'ಮುಗಿದಿದೆ',
      receiptMessage: 'ಪಾವತಿ ಬಂದಿದೆ: {{time}} ಕ್ಕೆ {{amount}}. ವಹಿವಾಟು ID: {{id}}.',
    },
    audio: {
      received: '{{amount}} ರೂಪಾಯಿ ಬಂದಿದೆ',
      mutedHint: 'ಧ್ವನಿ ದೃಢೀಕರಣ ಆಫ್ ಆಗಿದೆ. ಸೆಟ್ಟಿಂಗ್‌ನಲ್ಲಿ ಆನ್ ಮಾಡಿ.',
    },
  },
};

export default kn;
