import type { TranslationBundle } from './en';

/** Marathi (मराठी) */
export const mr: TranslationBundle = {
  common: {
    appName: 'MerchantOne',
    ok: 'ठीक',
    cancel: 'रद्द करा',
    continue: 'पुढे जा',
    back: 'मागे',
    next: 'पुढील',
    skip: 'वगळा',
    done: 'झाले',
    retry: 'पुन्हा प्रयत्न करा',
    save: 'सेव्ह करा',
    close: 'बंद करा',
    share: 'शेअर करा',
    download: 'डाउनलोड करा',
    search: 'शोधा',
    viewAll: 'सर्व पहा',
    today: 'आज',
    yesterday: 'काल',
    loading: 'लोड होत आहे…',
    yes: 'होय',
    no: 'नाही',
    optional: 'ऐच्छिक',
    verified: 'पडताळणी झाली',
    verifying: 'पडताळणी सुरू…',
    edit: 'बदला',
    remove: 'काढा',
    confirm: 'खात्री करा',
    comingSoon: 'लवकरच',
    comingSoonBody: 'हा भाग तयार होत आहे.',
    months: {
      jan: 'जान',
      feb: 'फेब्रु',
      mar: 'मार्च',
      apr: 'एप्रि',
      may: 'मे',
      jun: 'जून',
      jul: 'जुल',
      aug: 'ऑग',
      sep: 'सप्टें',
      oct: 'ऑक्टो',
      nov: 'नोव्हें',
      dec: 'डिसें',
    },
  },

  a11y: {
    back: 'मागे जा',
    close: 'बंद करा',
    notifications: 'सूचना',
    loading: 'मजकूर लोड होत आहे',
    amount: 'रक्कम {{amount}}',
    step: 'पायरी {{current}} / {{total}}',
  },

  tabs: {
    home: 'होम',
    collect: 'पैसे घ्या',
    transactions: 'व्यवहार',
    settlements: 'सेटलमेंट',
    more: 'अधिक',
  },

  network: {
    offlineTitle: 'तुम्ही ऑफलाइन आहात',
    offlineBanner: 'इंटरनेट नाही. सेव्ह केलेली माहिती दाखवत आहे.',
    offlineActionDisabled: 'यासाठी इंटरनेट जोडणी आवश्यक आहे.',
    backOnline: 'इंटरनेट परत आले',
  },

  errors: {
    title: 'काहीतरी चूक झाली',
    network_error: 'सर्व्हरशी संपर्क होत नाही. जोडणी तपासून पुन्हा प्रयत्न करा.',
    timeout: 'खूप वेळ लागत आहे. पुन्हा प्रयत्न करा.',
    offline: 'तुम्ही ऑफलाइन आहात. इंटरनेटला जोडून पुन्हा प्रयत्न करा.',
    unauthorized: 'तुमचे सेशन संपले. कृपया पुन्हा लॉग इन करा.',
    forbidden: 'हे करण्याची तुम्हाला परवानगी नाही.',
    not_found: 'तुम्ही शोधत असलेले सापडले नाही.',
    validation_error: 'कृपया भरलेली माहिती तपासा.',
    rate_limited: 'खूप प्रयत्न झाले. थोड्या वेळाने प्रयत्न करा.',
    invalid_otp: 'हा OTP चुकीचा आहे. तपासून पुन्हा टाका.',
    otp_expired: 'हा OTP कालबाह्य झाला. नवीन मागवा.',
    invalid_mobile: 'योग्य 10 अंकी मोबाइल क्रमांक टाका.',
    kyc_incomplete: 'या सुविधेसाठी तुमचे KYC पूर्ण करा.',
    kyc_rejected: 'तुमचे KYC मंजूर झाले नाही. तपासून पुन्हा पाठवा.',
    bank_verification_failed: 'हे बँक खाते पडताळता आले नाही. माहिती तपासा.',
    pan_verification_failed: 'हा PAN पडताळता आला नाही. क्रमांक तपासा.',
    already_refunded: 'या व्यवहाराचा परतावा आधीच झाला आहे.',
    refund_limit_exceeded: 'परताव्याची रक्कम उपलब्ध रकमेपेक्षा जास्त आहे.',
    payment_expired: 'ही पेमेंट विनंती कालबाह्य झाली. नवीन तयार करा.',
    server_error: 'आमच्या सर्व्हरमध्ये अडचण आहे. थोड्या वेळाने प्रयत्न करा.',
    unknown: 'काहीतरी चूक झाली. पुन्हा प्रयत्न करा.',
  },

  auth: {
    splash: {
      tagline: 'पेमेंट आता सोपे',
    },
    login: {
      title: 'स्वागत आहे',
      subtitle: 'तुमचा व्यवसाय सांभाळण्यासाठी मोबाइल क्रमांकाने लॉग इन करा',
      mobileLabel: 'मोबाइल क्रमांक',
      mobilePlaceholder: '10 अंकी मोबाइल क्रमांक',
      mobileRequired: 'तुमचा मोबाइल क्रमांक टाका',
      mobileInvalid: 'योग्य 10 अंकी मोबाइल क्रमांक टाका',
      consent: 'मी सेवा अटी आणि गोपनीयता धोरण स्वीकारतो/स्वीकारते',
      consentRequired: 'पुढे जाण्यासाठी अटी स्वीकारा',
      getOtp: 'OTP मिळवा',
      secureNote: 'क्रमांक पडताळण्यासाठी आम्ही 6 अंकी कोड पाठवू.',
    },
    otp: {
      title: 'तुमचा क्रमांक पडताळा',
      subtitle: '{{mobile}} वर पाठवलेला 6 अंकी कोड टाका',
      otpRequired: '6 अंकी कोड टाका',
      otpInvalid: 'कोड 6 अंकी असावा',
      verify: 'पडताळा',
      resend: 'कोड पुन्हा पाठवा',
      resendIn: '{{seconds}} सेकंदात पुन्हा पाठवा',
      changeNumber: 'क्रमांक बदला',
      autoReadHint: 'परवानगी असल्यास कोड आम्ही स्वतः भरू.',
      hintDev: 'डेमो मोड: {{otp}} वापरा',
    },
  },

  kyc: {
    title: 'व्यवसाय पडताळणी',
    stepOf: 'पायरी {{current}} / {{total}}',
    saveAndExit: 'सेव्ह करून बाहेर पडा',
    resumeTitle: 'पडताळणी सुरू ठेवा',
    resumeBody: 'तुम्ही पायरी {{step}} वर थांबले होते. तेथूनच पुढे जा.',
    progress: {
      business: 'व्यवसाय',
      identity: 'ओळख',
      bank: 'बँक',
      aadhaar: 'आधार',
    },
    business: {
      title: 'तुमच्या व्यवसायाबद्दल सांगा',
      subtitle: 'ग्राहक स्कॅन करणाऱ्या QR वर हेच दिसेल.',
      name: 'व्यवसायाचे नाव',
      namePlaceholder: 'उदा. शर्मा जनरल स्टोअर',
      nameRequired: 'तुमच्या व्यवसायाचे नाव टाका',
      nameTooShort: 'नाव कमीत कमी 3 अक्षरांचे असावे',
      category: 'व्यवसाय प्रकार',
      categoryPlaceholder: 'प्रकार निवडा',
      categoryRequired: 'तुमचा व्यवसाय प्रकार निवडा',
      categorySheetTitle: 'व्यवसाय प्रकार निवडा',
      addressLine1: 'दुकान / इमारतीचा पत्ता',
      addressPlaceholder: 'दुकान क्रमांक, रस्ता, परिसर',
      addressRequired: 'तुमच्या व्यवसायाचा पत्ता टाका',
      pincode: 'पिन कोड',
      pincodePlaceholder: '6 अंकी पिन कोड',
      pincodeRequired: 'तुमचा पिन कोड टाका',
      pincodeInvalid: 'योग्य 6 अंकी पिन कोड टाका',
      city: 'शहर',
      cityRequired: 'तुमचे शहर टाका',
      state: 'राज्य',
      stateRequired: 'तुमचे राज्य टाका',
      pincodeLookup: 'तुमचा परिसर शोधत आहे…',
    },
    identity: {
      title: 'ओळखीची माहिती',
      subtitle: 'पेमेंट स्वीकारण्यासाठी RBI ने बंधनकारक केले आहे.',
      pan: 'PAN क्रमांक',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'तुमचा PAN क्रमांक टाका',
      panInvalid: 'योग्य PAN टाका (उदा. ABCDE1234F)',
      panHelp: 'तुमच्या PAN कार्डवर छापल्याप्रमाणे.',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'योग्य 15 अक्षरी GSTIN टाका',
      gstinHelp: 'GST बिल हवे असल्यास हे जोडा.',
    },
    bank: {
      title: 'तुमचे पैसे कुठे पाठवायचे?',
      subtitle: 'तुमची जमा रक्कम येथे येईल, सहसा दुसऱ्या दिवशी.',
      accountNumber: 'खाते क्रमांक',
      accountNumberPlaceholder: 'बँक खाते क्रमांक',
      accountNumberRequired: 'तुमचा खाते क्रमांक टाका',
      accountNumberInvalid: 'खाते क्रमांक 9 ते 18 अंकी असावा',
      confirmAccountNumber: 'खाते क्रमांक पुन्हा टाका',
      accountMismatch: 'खाते क्रमांक जुळत नाहीत',
      ifsc: 'IFSC कोड',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'IFSC कोड टाका',
      ifscInvalid: 'योग्य IFSC टाका (उदा. HDFC0001234)',
      holderName: 'खातेदाराचे नाव',
      holderNamePlaceholder: 'बँक नोंदीप्रमाणे नाव',
      holderNameRequired: 'खातेदाराचे नाव टाका',
      verifyCta: 'खाते पडताळा',
      verifying: 'तुमचे खाते पडताळत आहे…',
      verifyingBody: 'हे खाते तुमचेच आहे याची खात्री करण्यासाठी आम्ही ₹1 पाठवत आहोत.',
      verifiedTitle: 'खाते पडताळले',
      verifiedNameAtBank: 'बँकेतील नाव: {{name}}',
      unlockNote: 'या पायरीनंतर मर्यादेसह पेमेंट घेणे सुरू करू शकता, तपासणी पूर्ण होईपर्यंत.',
    },
    aadhaar: {
      title: 'आधार पडताळणी',
      subtitle: 'सर्व सुविधा उघडण्यासाठी शेवटची पायरी.',
      numberLabel: 'आधार क्रमांक',
      numberPlaceholder: '12 अंकी आधार क्रमांक',
      numberRequired: 'तुमचा आधार क्रमांक टाका',
      numberInvalid: 'आधार क्रमांक 12 अंकी असावा',
      consent: 'मी आधार eKYC द्वारे माझी ओळख पडताळण्यास संमती देतो/देते. माझी आधार माहिती केवळ या पडताळणीसाठी वापरली जाईल हे मला समजले आहे.',
      consentRequired: 'पुढे जाण्यासाठी तुमची संमती आवश्यक आहे',
      sendOtp: 'आधार OTP पाठवा',
      otpLabel: 'आधार OTP',
      otpSentTo: 'आधारशी जोडलेल्या मोबाइलवर पाठवलेला कोड टाका.',
      otpRequired: '6 अंकी आधार OTP टाका',
      verifyCta: 'आधार पडताळा',
      verifiedTitle: 'आधार पडताळला',
      skipForNow: 'नंतर करा',
      privacyNote: 'तुमचा पूर्ण आधार क्रमांक आम्ही कधीही साठवत नाही.',
    },
    done: {
      title: 'सर्व तयार!',
      subtitle: 'तुमची माहिती पाठवली गेली. आता तुम्ही पेमेंट घेणे सुरू करू शकता.',
      pendingTitle: 'पडताळणी सुरू आहे',
      pendingSubtitle: 'आम्ही तुमची माहिती तपासत आहोत. सहसा काही तास लागतात.',
      generateQr: 'माझा QR तयार करा',
      goHome: 'डॅशबोर्डवर जा',
      vpaLabel: 'तुमची UPI ID',
      limitsNote: 'पडताळणी पूर्ण होईपर्यंत तुम्ही रोज {{limit}} पर्यंत घेऊ शकता.',
    },
    status: {
      not_started: 'KYC बाकी',
      in_progress: 'KYC अपूर्ण',
      pending_review: 'तपासणीत',
      approved: 'पडताळणी झाली',
      rejected: 'कृती आवश्यक',
    },
    rejected: {
      title: 'आम्हाला पुन्हा पाहावे लागेल',
      reasonLabel: 'कारण',
      retryCta: 'माहिती अद्ययावत करा',
    },
    submitCta: 'पडताळणीसाठी पाठवा',
    mcc: {
      grocery: 'किराणा / जनरल स्टोअर',
      restaurant: 'रेस्टॉरंट / कॅफे',
      apparel: 'कपडे',
      electronics: 'इलेक्ट्रॉनिक्स आणि मोबाइल',
      pharmacy: 'औषध दुकान / मेडिकल',
      salon: 'सलून आणि सौंदर्य',
      hardware: 'हार्डवेअर आणि बांधकाम साहित्य',
      services: 'व्यावसायिक सेवा',
      education: 'शिक्षण आणि कोचिंग',
      transport: 'वाहतूक आणि प्रवास',
      online: 'ऑनलाइन / D2C विक्रेता',
      other: 'इतर',
    },
  },

  home: {
    greeting: 'नमस्कार',
    summary: {
      title: 'आजची जमा',
      collected: 'आज मिळाले',
      txnCount: '{{count}} पेमेंट',
      txnCount_plural: '{{count}} पेमेंट',
      pendingSettlement: 'सेटलमेंट बाकी',
      settlementHint: 'तुमच्या बँक खात्यात जमा होईल',
    },
    collectCta: 'पैसे घ्या',
    quickActions: {
      title: 'झटपट कृती',
      myQr: 'माझा QR',
      paymentLink: 'पेमेंट लिंक',
      reports: 'अहवाल',
      refund: 'परतावा',
    },
    recent: {
      title: 'अलीकडील पेमेंट',
      emptyTitle: 'अजून पेमेंट नाही',
      emptyBody: 'पहिले पेमेंट मिळवण्यासाठी ग्राहकाला तुमचा QR दाखवा.',
      emptyCta: 'माझा QR दाखवा',
    },
    kycNudge: {
      title: 'पडताळणी पूर्ण करा',
      body: 'मर्यादा काढण्यासाठी तुमची माहिती पूर्ण करा.',
      cta: 'पुढे जा',
    },
    error: {
      title: 'डॅशबोर्ड लोड होऊ शकला नाही',
      body: 'जोडणी तपासून पुन्हा प्रयत्न करा.',
    },
  },

  notifications: {
    title: 'सूचना',
    emptyTitle: 'सूचना नाहीत',
    emptyBody: 'पेमेंट आणि सेटलमेंटची माहिती येथे दिसेल.',
  },

  transactions: {
    title: 'व्यवहार',
    status: {
      success: 'मिळाले',
      pending: 'बाकी',
      failed: 'अपयशी',
      refunded: 'परत केले',
      partially_refunded: 'अंशतः परत',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI अ‍ॅप',
      payment_link: 'पेमेंट लिंक',
      card: 'कार्ड',
      netbanking: 'नेट बँकिंग',
      wallet: 'वॉलेट',
    },
    filters: {
      all: 'सर्व',
      success: 'मिळाले',
      pending: 'बाकी',
      failed: 'अपयशी',
      refunded: 'परत केले',
    },
    searchPlaceholder: 'रक्कम, UTR किंवा पाठवणारा शोधा',
    emptyTitle: 'व्यवहार नाहीत',
    emptyBody: 'तुम्हाला मिळणारे पेमेंट येथे दिसतील.',
    emptyFilteredTitle: 'काही जुळले नाही',
    emptyFilteredBody: 'दुसरा फिल्टर किंवा तारीख निवडून पहा.',
    clearFilters: 'फिल्टर काढा',
    resultCount: '{{count}} व्यवहार',
    resultCount_plural: '{{count}} व्यवहार',
    loadingMore: 'अधिक लोड होत आहे…',
    endOfList: 'एवढेच आहे',
    detail: {
      title: 'पेमेंटचा तपशील',
      amountLabel: 'रक्कम',
      statusLabel: 'स्थिती',
      modeLabel: 'कशातून मिळाले',
      txnIdLabel: 'व्यवहार ID',
      utrLabel: 'UTR / RRN',
      timeLabel: 'तारीख आणि वेळ',
      payerLabel: 'पाठवणारा',
      noteLabel: 'टिप्पणी',
      breakdownTitle: 'हिशेब',
      grossLabel: 'मिळालेली रक्कम',
      feeLabel: 'शुल्क (MDR)',
      netLabel: 'तुम्हाला मिळेल',
      noFee: 'शुल्क नाही',
      settlementTitle: 'सेटलमेंट',
      settlementPending: 'तुमच्या बँक खात्यात पाठवले जाईल',
      settlementDone: 'तुमच्या बँक खात्यात पाठवले',
      viewSettlement: 'सेटलमेंट पहा',
      refundedLabel: 'आतापर्यंत परत केले',
      actions: 'कृती',
      refund: 'परतावा',
      shareReceipt: 'पावती शेअर करा',
      raiseDispute: 'तक्रार नोंदवा',
      reportIssue: 'अडचण सांगा',
      notRefundable: 'या पेमेंटचा परतावा होऊ शकत नाही',
      receiptMessage: '{{time}} ला {{amount}} मिळाले. व्यवहार ID: {{id}}.',
    },
  },

  refund: {
    title: 'परतावा द्या',
    originalLabel: 'मूळ पेमेंट',
    refundableLabel: 'परताव्यासाठी उपलब्ध',
    alreadyRefunded: '{{amount}} आधीच परत केले',
    typeFull: 'पूर्ण परतावा',
    typePartial: 'अंशतः परतावा',
    fullBody: 'पूर्ण रक्कम परत करा',
    partialBody: 'रकमेचा काही भाग परत करा',
    amountLabel: 'परताव्याची रक्कम',
    reasonLabel: 'कारण',
    reasonPlaceholder: 'परतावा का? (ऐच्छिक)',
    exceedsRefundable: '{{max}} पेक्षा जास्त परतावा होऊ शकत नाही',
    tooLow: '{{min}} पेक्षा जास्त रक्कम टाका',
    confirmCta: '{{amount}} परत करा',
    reauthReason: '{{amount}} च्या परताव्याची खात्री करा',
    processingTitle: 'परतावा सुरू आहे…',
    processingBody: 'कृपया अ‍ॅप उघडे ठेवा.',
    successTitle: 'परतावा सुरू झाला',
    successBody: '{{amount}} ग्राहकाला परत पाठवले जात आहे. सहसा 3-5 कामकाजाचे दिवस लागतात.',
    successDone: 'झाले',
    offlineTitle: 'इंटरनेट नाही',
    offlineBody: 'परताव्यासाठी इंटरनेट आवश्यक आहे.',
    notEligibleTitle: 'परतावा होऊ शकत नाही',
    notEligibleBody: 'केवळ यशस्वी पेमेंटचा परतावा होऊ शकतो.',
  },

  appLock: {
    title: 'तुम्हीच आहात याची खात्री करा',
    biometricPrompt: 'खात्रीसाठी बोटाचा ठसा किंवा चेहरा वापरा',
    biometricFailed: 'पडताळणी झाली नाही. त्याऐवजी PIN टाका.',
    usePin: 'PIN वापरा',
    pinIncorrect: 'चुकीचा PIN. {{count}} प्रयत्न शिल्लक.',
    lockedOut: 'खूप चुकीचे प्रयत्न. अ‍ॅप बंद करून पुन्हा उघडा.',
    setupTitle: 'अ‍ॅप PIN तयार करा',
    setupBody: 'परतावा आणि इतर महत्त्वाच्या कामांना मंजुरी देण्यासाठी {{min}} अंकी PIN निवडा.',
    confirmTitle: 'PIN पुन्हा टाका',
    pinMismatch: 'PIN जुळले नाहीत. पुन्हा प्रयत्न करा.',
    pinTooShort: 'PIN कमीत कमी {{min}} अंकी असावा',
  },

  reports: {
    title: 'अहवाल',
    chartTitle: 'विक्रीचा कल',
    chartHint: 'त्या दिवसाची एकूण रक्कम पाहण्यासाठी बारवर टॅप करा',
    chartA11y: 'निवडलेल्या कालावधीचा विक्री तक्ता',
    statsTitle: 'सारांश',
    totalSales: 'एकूण विक्री',
    txnCount: 'पेमेंट',
    avgTicket: 'सरासरी विक्री',
    topMode: 'सर्वाधिक वापरलेले',
    bestDay: 'सर्वोत्तम दिवस',
    tradingDays: 'विक्री झालेले दिवस',
    avgPerTradingDay: 'विक्री झालेल्या दिवसाची सरासरी',
    emptyTitle: 'या कालावधीत विक्री नाही',
    emptyBody: 'दुसरी तारीख निवडा, किंवा पेमेंट घेणे सुरू करा.',
    emptyCta: 'पैसे घ्या',
    errorTitle: 'अहवाल लोड होऊ शकला नाही',
    export: {
      cta: 'अहवाल एक्सपोर्ट करा',
      preparing: 'एक्सपोर्ट तयार होत आहे…',
      failed: 'एक्सपोर्ट तयार होऊ शकला नाही. पुन्हा प्रयत्न करा.',
      fileName: 'विक्री अहवाल',
      formatNote: 'CSV फाइल म्हणून सेव्ह होते, जी Excel आणि Google Sheets मध्ये उघडते.',
      colDate: 'तारीख',
      colSales: 'विक्री (INR)',
      colCount: 'पेमेंट',
      totalsLabel: 'एकूण',
      periodLabel: 'कालावधी',
      generatedLabel: 'तयार केले',
    },
    gst: {
      title: 'GST',
      summaryCta: 'GST सारांश एक्सपोर्ट करा',
      summaryBody: 'तुमच्या GSTIN सह कालावधीच्या विक्रीचा सारांश, तुमच्या अकाउंटंटच्या GST फायलिंगसाठी.',
      noGstinTitle: 'GSTIN नोंदवलेला नाही',
      noGstinBody: 'GST एक्सपोर्टमध्ये समाविष्ट करण्यासाठी तुमच्या प्रोफाइलमध्ये GSTIN जोडा.',
      invoiceNote: 'प्रत्येक पेमेंटच्या कर पावतीसाठी ग्राहकाची माहिती आणि वस्तूंची यादी लागते, म्हणून त्या इनव्हॉइसिंग सुविधेतून तयार होतात, पेमेंट नोंदींमधून नाही.',
      gstinLabel: 'GSTIN',
      fileName: 'GST सारांश',
      colField: 'तपशील',
      colValue: 'मूल्य',
      rowBusiness: 'व्यवसायाचे नाव',
      rowGstin: 'GSTIN',
      rowPeriodFrom: 'कालावधी पासून',
      rowPeriodTo: 'कालावधी पर्यंत',
      rowTotalSales: 'एकूण विक्री (INR)',
      rowTxnCount: 'पेमेंटची संख्या',
      rowNote: 'टिप्पणी',
      noteValue: 'मिळालेल्या पेमेंटचा सारांश. ही कर पावती नाही.',
    },
  },

  more: {
    title: 'अधिक',
    reports: 'अहवाल',
    reportsBody: 'विक्रीचे कल आणि एक्सपोर्ट',
    profile: 'व्यवसाय प्रोफाइल',
    profileBody: 'तुमची माहिती, बँक खाते आणि KYC',
    staff: 'स्टाफ',
    staffBody: 'पेमेंट घेणारे लोक जोडा',
    support: 'मदत आणि सहाय्य',
    supportBody: 'प्रश्नोत्तरे, तक्रार नोंदवा, संपर्क करा',
    settings: 'सेटिंग',
    settingsBody: 'भाषा, आवाज, सूचना, अ‍ॅप लॉक',
  },

  profile: {
    title: 'व्यवसाय प्रोफाइल',
    businessTitle: 'व्यवसायाची माहिती',
    nameLabel: 'व्यवसायाचे नाव',
    categoryLabel: 'व्यवसाय प्रकार',
    addressLabel: 'पत्ता',
    gstinLabel: 'GSTIN',
    gstinEmpty: 'जोडलेले नाही',
    panLabel: 'PAN',
    mobileLabel: 'मोबाइल क्रमांक',
    vpaLabel: 'तुमची UPI ID',
    kycTitle: 'पडताळणी',
    kycPendingBody: 'आम्ही तुमची माहिती तपासत आहोत.',
    kycRejectedBody: 'तुमच्या पडताळणीकडे लक्ष देणे आवश्यक आहे. कृपया माहिती अद्ययावत करा.',
    bankTitle: 'सेटलमेंट खाते',
    bankAccountLabel: 'खाते',
    bankIfscLabel: 'IFSC',
    bankHolderLabel: 'खातेदार',
    bankChangeCta: 'सेटलमेंट खाते बदला',
    bankChangeWarning: 'पुढील सर्व सेटलमेंट नवीन खात्यात जाईल. आम्ही ₹1 पाठवून त्याची खात्री करतो.',
    editCta: 'माहिती बदला',
    editTitle: 'व्यवसायाची माहिती बदला',
    saveCta: 'बदल सेव्ह करा',
    saved: 'बदल सेव्ह झाले',
    bankEditTitle: 'सेटलमेंट खाते बदला',
    bankReauthReason: 'सेटलमेंट खाते बदलण्याची खात्री करा',
    bankSubmitCta: 'पडताळून सेव्ह करा',
    bankVerifying: 'तुमचे खाते पडताळत आहे…',
    bankSaved: 'सेटलमेंट खाते अद्ययावत झाले',
    readOnlyNote: 'PAN आणि मोबाइल क्रमांक येथे बदलता येत नाहीत. चुकीचे असल्यास सहाय्याशी संपर्क करा.',
    offlineNote: 'प्रोफाइल बदलण्यासाठी इंटरनेट आवश्यक आहे.',
  },

  staff: {
    title: 'स्टाफ',
    subtitle: 'तुमच्या व्यवसायासाठी पैसे घेऊ शकणारे लोक',
    addCta: 'स्टाफ जोडा',
    emptyTitle: 'स्टाफ जोडलेला नाही',
    emptyBody: 'मॅनेजर किंवा कॅशियर जोडा जेणेकरून ते तुमच्यासाठी पैसे घेऊ शकतील.',
    errorTitle: 'स्टाफ लोड होऊ शकला नाही',
    countLabel: '{{count}} व्यक्ती',
    countLabel_plural: '{{count}} लोक',
    roles: {
      manager: 'मॅनेजर',
      cashier: 'कॅशियर',
    },
    roleHelp: {
      manager: 'पैसे घेऊ शकतात, अहवाल पाहू शकतात आणि परतावा देऊ शकतात',
      cashier: 'फक्त पैसे घेऊ शकतात',
    },
    addTitle: 'स्टाफ जोडा',
    nameLabel: 'पूर्ण नाव',
    namePlaceholder: 'ज्या नावाने ओळखतात',
    nameRequired: 'त्यांचे नाव टाका',
    mobileLabel: 'मोबाइल क्रमांक',
    mobileRequired: 'त्यांचा मोबाइल क्रमांक टाका',
    mobileInvalid: 'योग्य 10 अंकी मोबाइल क्रमांक टाका',
    mobileDuplicate: 'हा मोबाइल क्रमांक आधीच जोडलेला आहे',
    roleLabel: 'भूमिका',
    addSubmit: 'जोडा',
    added: '{{name}} जोडले',
    editRoleTitle: '{{name}} ची भूमिका बदला',
    roleSaved: 'भूमिका अद्ययावत झाली',
    removeCta: 'काढा',
    removeConfirmTitle: '{{name}} काढायचे?',
    removeConfirmBody: 'ते तुमच्यासाठी पैसे घेऊ शकणार नाहीत.',
    removed: '{{name}} काढले',
    offlineNote: 'स्टाफ जोडण्यासाठी किंवा काढण्यासाठी इंटरनेट आवश्यक आहे.',
  },

  settings: {
    title: 'सेटिंग',
    languageTitle: 'भाषा',
    languageBody: 'अ‍ॅपसाठी आणि पेमेंटच्या घोषणेसाठी',
    audioTitle: 'पेमेंटची घोषणा',
    audioEnabledLabel: 'पेमेंटची मोठ्याने घोषणा करा',
    audioEnabledBody: 'पेमेंट आल्यावर रक्कम ऐका, स्क्रीन पाहण्याची गरज नाही',
    audioLanguageLabel: 'घोषणेची भाषा',
    audioVolumeNote: 'घोषणेचा आवाज तुमच्या फोनच्या मीडिया व्हॉल्यूमनुसार असतो.',
    notificationsTitle: 'सूचना',
    pushLabel: 'अ‍ॅप सूचना',
    smsLabel: 'SMS',
    whatsappLabel: 'WhatsApp',
    securityTitle: 'सुरक्षा',
    pinLabel: 'अ‍ॅप PIN',
    pinSetBody: 'परतावा आणि इतर महत्त्वाच्या कामांना मंजुरी देण्यासाठी',
    pinNotSetBody: 'अजून सेट केलेला नाही',
    pinSetCta: 'PIN सेट करा',
    pinChangeCta: 'बदला',
    pinChanged: 'PIN अद्ययावत झाला',
    pinReauthReason: 'PIN बदलण्यापूर्वी तुम्हीच आहात याची खात्री करा',
    biometricLabel: 'बोटाचा ठसा किंवा चेहरा',
    biometricAvailableBody: 'शक्य असेल तेथे PIN ऐवजी वापरले जाते',
    biometricUnavailableBody: 'या फोनवर सेट केलेले नाही',
    themeTitle: 'रूप',
    themeLightOnly: 'अ‍ॅप सध्या फक्त फिकट थीम वापरते.',
    aboutTitle: 'अ‍ॅपविषयी',
    versionLabel: 'अ‍ॅप आवृत्ती',
    logoutCta: 'लॉग आउट',
    logoutConfirmTitle: 'लॉग आउट करायचे?',
    logoutConfirmBody: 'पुन्हा लॉग इन करण्यासाठी मोबाइल क्रमांक आणि OTP लागेल.',
    saveFailed: 'हा बदल सेव्ह होऊ शकला नाही. पुन्हा प्रयत्न करा.',
  },

  support: {
    title: 'मदत आणि सहाय्य',
    searchPlaceholder: 'मदत शोधा',
    faqTitle: 'सामान्य प्रश्न',
    faqEmptyTitle: 'जुळणारा प्रश्न नाही',
    faqEmptyBody: 'दुसरे शब्द वापरून पहा, किंवा तक्रार नोंदवा आणि आम्ही मदत करू.',
    contactTitle: 'आमच्याशी संपर्क',
    callCta: 'सहाय्याला कॉल करा',
    callBody: 'रोज, सकाळी 9 ते रात्री 9',
    whatsappCta: 'WhatsApp वर बोला',
    whatsappBody: 'सहसा एका तासात उत्तर',
    ticketsTitle: 'तुमच्या तक्रारी',
    ticketsEmptyTitle: 'अजून तक्रार नाही',
    ticketsEmptyBody: 'तक्रार नोंदवा आणि आम्ही तुमच्याशी संपर्क करू.',
    raiseCta: 'तक्रार नोंदवा',
    ticketStatus: {
      open: 'उघडी',
      in_progress: 'सुरू आहे',
      resolved: 'सुटली',
      closed: 'बंद',
    },
    raiseTitle: 'तक्रार नोंदवा',
    subjectLabel: 'हे कशाबद्दल आहे?',
    subjectPlaceholder: 'थोडक्यात सारांश',
    subjectRequired: 'थोडक्यात सारांश टाका',
    bodyLabel: 'अधिक सांगा',
    bodyPlaceholder: 'काय झाले? शक्य असल्यास रक्कम किंवा व्यवहार ID लिहा.',
    bodyRequired: 'कृपया अडचण सांगा',
    raiseSubmit: 'पाठवा',
    raised: 'तक्रार नोंदवली. आम्ही तुमच्याशी संपर्क करू.',
    offlineNote: 'तक्रार नोंदवण्यासाठी इंटरनेट आवश्यक आहे.',
    contactFailed: 'हे तुमच्या फोनवर उघडू शकले नाही. तुम्ही {{value}} वर कॉल करू शकता.',
    grievance: {
      title: 'तक्रार पुढे नेा',
      body: 'तुमची अडचण सुटली नाही तर तुम्ही ती पुढे नेऊ शकता. प्रत्येक स्तराची उत्तर देण्याची मुदत आहे.',
      level1Title: 'स्तर 1 — ग्राहक सहाय्य',
      level1Body: 'वर तक्रार नोंदवा. आम्ही 24 तासांत उत्तर देतो.',
      level2Title: 'स्तर 2 — नोडल अधिकारी',
      level2Body: '7 दिवसांत न सुटल्यास आमच्या नोडल अधिकाऱ्यांना लिहा.',
      level3Title: 'स्तर 3 — RBI ओम्बड्समन',
      level3Body: '30 दिवसांत न सुटल्यास तुम्ही डिजिटल व्यवहारांसाठी RBI ओम्बड्समनकडे जाऊ शकता.',
      officerLabel: 'तक्रार अधिकारी',
      emailLabel: 'ईमेल',
      phoneLabel: 'फोन',
      rbiPortalCta: 'RBI तक्रार पोर्टल उघडा',
      placeholderNote: 'हे संपर्क तपशील तात्पुरते आहेत. रिलीजपूर्वी तुमच्या नोंदणीकृत तक्रार अधिकाऱ्याची माहिती टाका.',
    },
    faq: {
      q1: 'मला पैसे कधी मिळतील?',
      a1: 'आज मिळालेले पेमेंट पुढच्या कामकाजाच्या दिवशी तुमच्या बँक खात्यात पाठवले जातात. ते सेटलमेंटमध्ये पाहू शकता. पैसे लवकर हवे असल्यास बाकी बॅचवर "आता सेटल करा" वापरा — त्याला थोडे शुल्क लागते.',
      q2: 'ग्राहकाने पैसे भरले पण मला घोषणा ऐकू आली नाही. काय करू?',
      a2: 'व्यवहार उघडून पेमेंट यादीत आहे का पहा. असेल तर पैसे तुमचेच आहेत, घोषणा वाजली नसली तरी. सेटिंगमध्ये घोषणा चालू आहे आणि फोन सायलेंटवर नाही याची खात्री करा.',
      q3: 'ग्राहकाला पैसे परत कसे करू?',
      a3: 'व्यवहार उघडा, पेमेंटवर टॅप करा, मग परतावा टॅप करा. पूर्ण रक्कम किंवा तिचा भाग परत करू शकता. खात्रीसाठी अ‍ॅप PIN किंवा बोटाचा ठसा विचारला जाईल.',
      q4: 'मी किती घेऊ शकतो यावर मर्यादा का आहे?',
      a4: 'पडताळणी पूर्ण होईपर्यंत तुम्ही रोज एका मर्यादेपर्यंत घेऊ शकता. मर्यादा काढण्यासाठी व्यवसाय प्रोफाइलमधून KYC पूर्ण करा.',
      q5: 'दुसरे कोणी माझ्यासाठी पैसे घेऊ शकते का?',
      a5: 'हो. त्यांना स्टाफमध्ये जोडा. कॅशियर फक्त पैसे घेऊ शकतो; मॅनेजर अहवालही पाहू शकतो आणि परतावाही देऊ शकतो.',
      q6: 'ज्या बँक खात्यात पैसे येतात ते कसे बदलू?',
      a6: 'व्यवसाय प्रोफाइलमध्ये जाऊन "सेटलमेंट खाते बदला" टॅप करा. सुरक्षेसाठी तुमचा PIN किंवा बोटाचा ठसा लागेल, आणि आम्ही नवीन खात्याची खात्री ₹1 पाठवून करतो.',
    },
  },

  dateRange: {
    label: 'तारखेची श्रेणी',
    all: 'सर्व काळ',
    today: 'आज',
    yesterday: 'काल',
    last7: 'गेले 7 दिवस',
    last30: 'गेले 30 दिवस',
    thisMonth: 'या महिन्यात',
    custom: 'स्वतःची श्रेणी',
    from: 'पासून',
    to: 'पर्यंत',
  },

  settlements: {
    title: 'सेटलमेंट',
    status: {
      pending: 'बाकी',
      processing: 'सुरू आहे',
      settled: 'जमा झाले',
      failed: 'अपयशी',
    },
    tabs: {
      pending: 'बाकी',
      settled: 'जमा झाले',
    },
    batchLabel: '{{count}} पेमेंटचा बॅच',
    batchLabel_plural: '{{count}} पेमेंटचा बॅच',
    utrLabel: 'UTR',
    expectedLabel: 'तुमच्या बँक खात्यात येणारे',
    creditedLabel: 'तुमच्या बँक खात्यात जमा',
    emptyPendingTitle: 'काही बाकी नाही',
    emptyPendingBody: 'आज मिळालेले पेमेंट उद्या तुमच्या बँक खात्यात पाठवले जातील.',
    emptySettledTitle: 'अजून सेटलमेंट नाही',
    emptySettledBody: 'पैसे बँक खात्यात पोहोचल्यावर UTR सह येथे दिसतील.',
    errorTitle: 'सेटलमेंट लोड होऊ शकले नाहीत',
    t1Note: 'पैसे पुढच्या कामकाजाच्या दिवशी तुमच्या बँक खात्यात पोहोचतात.',
    detail: {
      title: 'सेटलमेंटचा तपशील',
      breakdownTitle: 'हिशेब',
      grossLabel: 'एकूण मिळाले',
      feeLabel: 'शुल्क',
      netLabel: 'बँकेत जमा',
      bankTitle: 'बँक खाते',
      accountLabel: 'खाते',
      ifscLabel: 'IFSC',
      utrLabel: 'UTR / संदर्भ',
      createdLabel: 'बॅच तयार झाला',
      settledLabel: 'जमा झाले',
      txnTitle: 'या बॅचमधील पेमेंट',
      txnCount: '{{count}} पेमेंट',
      txnCount_plural: '{{count}} पेमेंट',
      reconcileNote: 'खालील सर्व पेमेंट मिळून एकूण रक्कम होते.',
      noTxnTitle: 'पेमेंट यादी नाही',
      noTxnBody: 'या बॅचमधील स्वतंत्र पेमेंट उपलब्ध नाहीत.',
    },
    statement: {
      download: 'स्टेटमेंट डाउनलोड करा',
      preparing: 'स्टेटमेंट तयार होत आहे…',
      failed: 'स्टेटमेंट तयार होऊ शकले नाही. पुन्हा प्रयत्न करा.',
      fileName: 'सेटलमेंट स्टेटमेंट',
      colDate: 'तारीख',
      colTime: 'वेळ',
      colTxnId: 'व्यवहार ID',
      colUtr: 'UTR',
      colMode: 'माध्यम',
      colStatus: 'स्थिती',
      colGross: 'रक्कम (INR)',
      colFee: 'शुल्क (INR)',
      colNet: 'निव्वळ (INR)',
      totalsLabel: 'एकूण',
      formatNote: 'CSV फाइल म्हणून सेव्ह होते, जी Excel आणि Google Sheets मध्ये उघडते.',
    },
    instant: {
      cta: 'आता सेटल करा',
      sheetTitle: 'तात्काळ सेटल करा',
      sheetBody: 'उद्याची वाट न पाहता हे पैसे काही मिनिटांत तुमच्या बँक खात्यात मिळवा.',
      netLabel: 'सेटलमेंटची रक्कम',
      feeLabel: 'तात्काळ सेटलमेंट शुल्क ({{percent}}%)',
      gstLabel: 'शुल्कावरील GST',
      payoutLabel: 'तुम्हाला मिळेल',
      confirmCta: '{{amount}} आता सेटल करा',
      processing: 'सेटल होत आहे…',
      successTitle: 'पैसे पाठवले जात आहेत',
      successBody: '{{amount}} तुमच्या बँक खात्यात जमा होत आहेत. सहसा काही मिनिटांत पोहोचतात.',
      ineligible: {
        already_settled: 'हा बॅच आधीच सेटल झाला आहे.',
        below_minimum: 'तात्काळ सेटलमेंटसाठी कमीत कमी {{min}} लागतात.',
        failed_batch: 'हा बॅच अपयशी झाला, तो तात्काळ सेटल होऊ शकत नाही.',
      },
      offlineBody: 'तात्काळ सेटलमेंटसाठी इंटरनेट आवश्यक आहे.',
    },
  },

  collect: {
    title: 'पैसे घ्या',
    subtitle: 'तुम्हाला पैसे कसे घ्यायचे आहेत?',
    modes: {
      staticQr: 'माझा QR कोड',
      staticQrBody: 'कोणत्याही रकमेसाठी एकच कोड. दाखवा किंवा छापा.',
      dynamicQr: 'रक्कम टाका',
      dynamicQrBody: 'ठराविक रकमेसाठी QR तयार करा.',
      paymentLink: 'पेमेंट लिंक',
      paymentLinkBody: 'WhatsApp किंवा SMS वर लिंक पाठवा.',
    },
    staticQr: {
      title: 'माझा QR कोड',
      instruction: 'ग्राहकाला स्कॅन करून कोणतीही रक्कम भरायला सांगा.',
      vpaLabel: 'UPI ID',
      noQrTitle: 'QR अजून तयार नाही',
      noQrBody: 'QR कोड मिळवण्यासाठी बँक पडताळणी पूर्ण करा.',
      noQrCta: 'पडताळणी पूर्ण करा',
      offlineUsable: 'तुमचा QR इंटरनेटशिवायही चालतो.',
    },
    amount: {
      title: 'रक्कम टाका',
      generateQr: 'QR तयार करा',
      createLink: 'लिंक तयार करा',
      noteLabel: 'टिप्पणी',
      notePlaceholder: 'कशासाठी? (ऐच्छिक)',
      tooLow: '{{min}} पेक्षा जास्त रक्कम टाका',
      limitExceeded: 'पडताळणी पूर्ण होईपर्यंत रोजची मर्यादा {{limit}} आहे',
      upiCap: 'एका UPI पेमेंटसाठी जास्तीत जास्त {{max}}',
    },
    dynamicQr: {
      title: 'पैसे भरण्यासाठी स्कॅन करा',
      waiting: 'पेमेंटची वाट पाहत आहे…',
      waitingBody: 'ग्राहकाला हा कोड स्कॅन करायला सांगा.',
      expiresIn: '{{time}} मध्ये संपेल',
      expiredTitle: 'QR कालबाह्य झाला',
      expiredBody: 'हा कोड आता वैध नाही. नवीन तयार करा.',
      newQr: 'नवीन QR तयार करा',
      cancel: 'रद्द करा',
      checkingSlowly: 'तपासणी सुरू आहे. तुमचे इंटरनेट हळू वाटते.',
      failedTitle: 'पेमेंट अपयशी',
      failedBody: 'ग्राहकाचे पेमेंट झाले नाही. त्यांना पुन्हा प्रयत्न करायला सांगा.',
      offlineTitle: 'इंटरनेट नाही',
      offlineBody: 'ठराविक रकमेच्या QR साठी इंटरनेट आवश्यक आहे. त्याऐवजी तुमचा QR कोड वापरा.',
      useStaticQr: 'माझा QR कोड वापरा',
    },
    link: {
      title: 'पेमेंट लिंक',
      createdTitle: 'लिंक तयार आहे',
      createdBody: 'ही ग्राहकाला पाठवा. ती 24 तासांत संपेल.',
      copy: 'लिंक कॉपी करा',
      copied: 'लिंक कॉपी झाली',
      shareVia: 'लिंक शेअर करा',
      newLink: 'दुसरी तयार करा',
      shareMessage: 'कृपया या लिंकवरून {{amount}} भरा: {{url}}',
    },
    success: {
      title: 'पेमेंट मिळाले!',
      amountLabel: 'मिळालेली रक्कम',
      txnIdLabel: 'व्यवहार ID',
      timeLabel: 'वेळ',
      payerLabel: 'पाठवणारा',
      utrLabel: 'UPI संदर्भ',
      shareReceipt: 'पावती शेअर करा',
      newPayment: 'नवीन पेमेंट',
      done: 'झाले',
      receiptMessage: 'पेमेंट मिळाले: {{time}} ला {{amount}}. व्यवहार ID: {{id}}.',
    },
    audio: {
      received: '{{amount}} रुपये मिळाले',
      mutedHint: 'आवाजाची पुष्टी बंद आहे. सेटिंगमध्ये चालू करा.',
    },
  },
};

export default mr;
