import type { TranslationBundle } from './en';

/** Tamil (தமிழ்) */
export const ta: TranslationBundle = {
  common: {
    appName: 'MerchantOne',
    ok: 'சரி',
    cancel: 'ரத்து',
    continue: 'தொடரவும்',
    back: 'பின்',
    next: 'அடுத்து',
    skip: 'தவிர்',
    done: 'முடிந்தது',
    retry: 'மீண்டும் முயற்சிக்கவும்',
    save: 'சேமி',
    close: 'மூடு',
    share: 'பங்கிடு',
    download: 'பதிவிறக்கு',
    search: 'தேடு',
    viewAll: 'அனைத்தையும் காண்க',
    today: 'இன்று',
    yesterday: 'நேற்று',
    loading: 'ஏற்றுகிறது…',
    yes: 'ஆம்',
    no: 'இல்லை',
    optional: 'விரும்பினால்',
    verified: 'சரிபார்க்கப்பட்டது',
    verifying: 'சரிபார்க்கிறது…',
    edit: 'திருத்து',
    remove: 'நீக்கு',
    confirm: 'உறுதிப்படுத்து',
    comingSoon: 'விரைவில்',
    comingSoonBody: 'இந்தப் பகுதி உருவாக்கப்படுகிறது.',
    months: {
      jan: 'ஜன',
      feb: 'பிப்',
      mar: 'மார்',
      apr: 'ஏப்',
      may: 'மே',
      jun: 'ஜூன்',
      jul: 'ஜூலை',
      aug: 'ஆக',
      sep: 'செப்',
      oct: 'அக்',
      nov: 'நவ',
      dec: 'டிச',
    },
  },

  a11y: {
    back: 'பின் செல்',
    close: 'மூடு',
    notifications: 'அறிவிப்புகள்',
    loading: 'உள்ளடக்கம் ஏற்றுகிறது',
    amount: 'தொகை {{amount}}',
    step: 'படி {{current}} / {{total}}',
  },

  tabs: {
    home: 'முகப்பு',
    collect: 'பணம் பெறு',
    transactions: 'பணப்பட்டுவாடா',
    settlements: 'செட்டில்மென்ட்',
    more: 'மேலும்',
  },

  network: {
    offlineTitle: 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள்',
    offlineBanner: 'இணைய இணைப்பு இல்லை. சேமித்த தகவல் காட்டப்படுகிறது.',
    offlineActionDisabled: 'இதற்கு இணைய இணைப்பு தேவை.',
    backOnline: 'இணைப்பு திரும்பியது',
  },

  errors: {
    title: 'ஏதோ தவறு நடந்தது',
    network_error: 'சர்வரைத் தொடர்பு கொள்ள முடியவில்லை. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    timeout: 'அதிக நேரம் ஆகிறது. மீண்டும் முயற்சிக்கவும்.',
    offline: 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள். இணைந்து மீண்டும் முயற்சிக்கவும்.',
    unauthorized: 'உங்கள் அமர்வு முடிந்தது. மீண்டும் உள்நுழையவும்.',
    forbidden: 'இதைச் செய்ய உங்களுக்கு அனுமதி இல்லை.',
    not_found: 'நீங்கள் தேடியது கிடைக்கவில்லை.',
    validation_error: 'நீங்கள் உள்ளிட்ட விவரங்களைச் சரிபார்க்கவும்.',
    rate_limited: 'அதிக முயற்சிகள். சிறிது நேரம் கழித்து முயற்சிக்கவும்.',
    invalid_otp: 'இந்த OTP தவறு. சரிபார்த்து மீண்டும் உள்ளிடவும்.',
    otp_expired: 'இந்த OTP காலாவதியானது. புதியதைக் கோரவும்.',
    invalid_mobile: 'சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.',
    kyc_incomplete: 'இந்த வசதிக்கு உங்கள் KYC-ஐ முடிக்கவும்.',
    kyc_rejected: 'உங்கள் KYC ஏற்கப்படவில்லை. சரிபார்த்து மீண்டும் சமர்ப்பிக்கவும்.',
    bank_verification_failed: 'இந்த வங்கிக் கணக்கைச் சரிபார்க்க முடியவில்லை. விவரங்களைச் சரிபார்க்கவும்.',
    pan_verification_failed: 'இந்த PAN-ஐச் சரிபார்க்க முடியவில்லை. எண்ணைச் சரிபார்க்கவும்.',
    already_refunded: 'இந்தப் பணப்பட்டுவாடாவுக்கு ஏற்கனவே பணம் திரும்பப் பெறப்பட்டது.',
    refund_limit_exceeded: 'திரும்பப் பெறும் தொகை கிடைக்கும் தொகையை விட அதிகம்.',
    payment_expired: 'இந்தக் கட்டணக் கோரிக்கை காலாவதியானது. புதியதை உருவாக்கவும்.',
    server_error: 'எங்கள் சர்வரில் சிக்கல். சிறிது நேரம் கழித்து முயற்சிக்கவும்.',
    unknown: 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.',
  },

  auth: {
    splash: {
      tagline: 'எளிய பணப்பரிவர்த்தனை',
    },
    login: {
      title: 'வரவேற்கிறோம்',
      subtitle: 'உங்கள் வணிகத்தை நிர்வகிக்க மொபைல் எண்ணுடன் உள்நுழையவும்',
      mobileLabel: 'மொபைல் எண்',
      mobilePlaceholder: '10 இலக்க மொபைல் எண்',
      mobileRequired: 'உங்கள் மொபைல் எண்ணை உள்ளிடவும்',
      mobileInvalid: 'சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்',
      consent: 'சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கிறேன்',
      consentRequired: 'தொடர விதிமுறைகளை ஏற்கவும்',
      getOtp: 'OTP பெறு',
      secureNote: 'உங்கள் எண்ணைச் சரிபார்க்க 6 இலக்கக் குறியீட்டை அனுப்புவோம்.',
    },
    otp: {
      title: 'உங்கள் எண்ணைச் சரிபார்க்கவும்',
      subtitle: '{{mobile}} க்கு அனுப்பிய 6 இலக்கக் குறியீட்டை உள்ளிடவும்',
      otpRequired: '6 இலக்கக் குறியீட்டை உள்ளிடவும்',
      otpInvalid: 'குறியீடு 6 இலக்கமாக இருக்க வேண்டும்',
      verify: 'சரிபார்',
      resend: 'குறியீட்டை மீண்டும் அனுப்பு',
      resendIn: '{{seconds}} வினாடிகளில் மீண்டும் அனுப்பு',
      changeNumber: 'எண்ணை மாற்று',
      autoReadHint: 'அனுமதி இருந்தால் குறியீட்டை தானாகப் படிப்போம்.',
      hintDev: 'டெமோ முறை: {{otp}} உள்ளிடவும்',
    },
  },

  kyc: {
    title: 'வணிகச் சரிபார்ப்பு',
    stepOf: 'படி {{current}} / {{total}}',
    saveAndExit: 'சேமித்து வெளியேறு',
    resumeTitle: 'சரிபார்ப்பைத் தொடரவும்',
    resumeBody: 'நீங்கள் படி {{step}} இல் நிற்கிறீர்கள். அங்கிருந்து தொடரவும்.',
    progress: {
      business: 'வணிகம்',
      identity: 'அடையாளம்',
      bank: 'வங்கி',
      aadhaar: 'ஆதார்',
    },
    business: {
      title: 'உங்கள் வணிகம் பற்றிக் கூறுங்கள்',
      subtitle: 'வாடிக்கையாளர்கள் ஸ்கேன் செய்யும் QR-இல் இது தெரியும்.',
      name: 'வணிகப் பெயர்',
      namePlaceholder: 'உதா. சர்மா ஜெனரல் ஸ்டோர்',
      nameRequired: 'உங்கள் வணிகப் பெயரை உள்ளிடவும்',
      nameTooShort: 'பெயர் குறைந்தது 3 எழுத்துகள் இருக்க வேண்டும்',
      category: 'வணிக வகை',
      categoryPlaceholder: 'ஒரு வகையைத் தேர்ந்தெடுக்கவும்',
      categoryRequired: 'உங்கள் வணிக வகையைத் தேர்ந்தெடுக்கவும்',
      categorySheetTitle: 'வணிக வகையைத் தேர்ந்தெடுக்கவும்',
      addressLine1: 'கடை / கட்டிட முகவரி',
      addressPlaceholder: 'கடை எண், தெரு, பகுதி',
      addressRequired: 'உங்கள் வணிக முகவரியை உள்ளிடவும்',
      pincode: 'PIN குறியீடு',
      pincodePlaceholder: '6 இலக்க PIN குறியீடு',
      pincodeRequired: 'உங்கள் PIN குறியீட்டை உள்ளிடவும்',
      pincodeInvalid: 'சரியான 6 இலக்க PIN குறியீட்டை உள்ளிடவும்',
      city: 'நகரம்',
      cityRequired: 'உங்கள் நகரத்தை உள்ளிடவும்',
      state: 'மாநிலம்',
      stateRequired: 'உங்கள் மாநிலத்தை உள்ளிடவும்',
      pincodeLookup: 'உங்கள் பகுதியைத் தேடுகிறது…',
    },
    identity: {
      title: 'அடையாள விவரங்கள்',
      subtitle: 'பணம் பெற RBI கட்டாயமாக்கியுள்ளது.',
      pan: 'PAN எண்',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'உங்கள் PAN எண்ணை உள்ளிடவும்',
      panInvalid: 'சரியான PAN உள்ளிடவும் (உதா. ABCDE1234F)',
      panHelp: 'உங்கள் PAN அட்டையில் உள்ளது போல.',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'சரியான 15 எழுத்து GSTIN உள்ளிடவும்',
      gstinHelp: 'GST விலைப்பட்டியல் வேண்டுமெனில் இதைச் சேர்க்கவும்.',
    },
    bank: {
      title: 'உங்கள் பணத்தை எங்கு அனுப்ப வேண்டும்?',
      subtitle: 'உங்கள் வசூல் இங்கு வரும், வழக்கமாக அடுத்த நாள்.',
      accountNumber: 'கணக்கு எண்',
      accountNumberPlaceholder: 'வங்கிக் கணக்கு எண்',
      accountNumberRequired: 'உங்கள் கணக்கு எண்ணை உள்ளிடவும்',
      accountNumberInvalid: 'கணக்கு எண் 9 முதல் 18 இலக்கங்களாக இருக்க வேண்டும்',
      confirmAccountNumber: 'கணக்கு எண்ணை மீண்டும் உள்ளிடவும்',
      accountMismatch: 'கணக்கு எண்கள் பொருந்தவில்லை',
      ifsc: 'IFSC குறியீடு',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'IFSC குறியீட்டை உள்ளிடவும்',
      ifscInvalid: 'சரியான IFSC உள்ளிடவும் (உதா. HDFC0001234)',
      holderName: 'கணக்கு வைத்திருப்பவர் பெயர்',
      holderNamePlaceholder: 'வங்கிப் பதிவின் படி பெயர்',
      holderNameRequired: 'கணக்கு வைத்திருப்பவர் பெயரை உள்ளிடவும்',
      verifyCta: 'கணக்கைச் சரிபார்',
      verifying: 'உங்கள் கணக்கைச் சரிபார்க்கிறது…',
      verifyingBody: 'இந்தக் கணக்கு உங்களுடையது என உறுதிப்படுத்த ₹1 அனுப்புகிறோம்.',
      verifiedTitle: 'கணக்கு சரிபார்க்கப்பட்டது',
      verifiedNameAtBank: 'வங்கியில் பெயர்: {{name}}',
      unlockNote: 'இந்தப் படிக்குப் பிறகு வரம்புகளுடன் பணம் பெறத் தொடங்கலாம், சோதனை முடியும் வரை.',
    },
    aadhaar: {
      title: 'ஆதார் சரிபார்ப்பு',
      subtitle: 'அனைத்து வசதிகளையும் திறக்க கடைசிப் படி.',
      numberLabel: 'ஆதார் எண்',
      numberPlaceholder: '12 இலக்க ஆதார் எண்',
      numberRequired: 'உங்கள் ஆதார் எண்ணை உள்ளிடவும்',
      numberInvalid: 'ஆதார் எண் 12 இலக்கமாக இருக்க வேண்டும்',
      consent: 'ஆதார் eKYC மூலம் எனது அடையாளத்தைச் சரிபார்க்க ஒப்புதல் அளிக்கிறேன். எனது ஆதார் விவரங்கள் இந்தச் சரிபார்ப்புக்கு மட்டுமே பயன்படும் என்பதைப் புரிந்துகொள்கிறேன்.',
      consentRequired: 'தொடர உங்கள் ஒப்புதல் தேவை',
      sendOtp: 'ஆதார் OTP அனுப்பு',
      otpLabel: 'ஆதார் OTP',
      otpSentTo: 'ஆதாருடன் இணைந்த மொபைலுக்கு அனுப்பிய குறியீட்டை உள்ளிடவும்.',
      otpRequired: '6 இலக்க ஆதார் OTP உள்ளிடவும்',
      verifyCta: 'ஆதாரைச் சரிபார்',
      verifiedTitle: 'ஆதார் சரிபார்க்கப்பட்டது',
      skipForNow: 'பிறகு செய்',
      privacyNote: 'உங்கள் முழு ஆதார் எண்ணை நாங்கள் சேமிப்பதில்லை.',
    },
    done: {
      title: 'எல்லாம் தயார்!',
      subtitle: 'உங்கள் விவரங்கள் சமர்ப்பிக்கப்பட்டன. இப்போதே பணம் பெறத் தொடங்கலாம்.',
      pendingTitle: 'சரிபார்ப்பு நடக்கிறது',
      pendingSubtitle: 'உங்கள் விவரங்களை ஆய்வு செய்கிறோம். வழக்கமாக சில மணி நேரம் ஆகும்.',
      generateQr: 'எனது QR உருவாக்கு',
      goHome: 'டாஷ்போர்டுக்குச் செல்',
      vpaLabel: 'உங்கள் UPI ID',
      limitsNote: 'சரிபார்ப்பு முடியும் வரை நாளொன்றுக்கு {{limit}} வரை பெறலாம்.',
    },
    status: {
      not_started: 'KYC நிலுவை',
      in_progress: 'KYC முழுமையடையவில்லை',
      pending_review: 'ஆய்வில் உள்ளது',
      approved: 'சரிபார்க்கப்பட்டது',
      rejected: 'நடவடிக்கை தேவை',
    },
    rejected: {
      title: 'மீண்டும் பார்க்க வேண்டும்',
      reasonLabel: 'காரணம்',
      retryCta: 'விவரங்களைப் புதுப்பி',
    },
    submitCta: 'சரிபார்ப்புக்கு சமர்ப்பி',
    mcc: {
      grocery: 'மளிகை / கிரானா கடை',
      restaurant: 'உணவகம் / கஃபே',
      apparel: 'ஆடைகள்',
      electronics: 'மின்னணு பொருட்கள் & மொபைல்',
      pharmacy: 'மருந்தகம் / மருத்துவம்',
      salon: 'சலூன் & அழகு',
      hardware: 'ஹார்டுவேர் & கட்டுமானப் பொருட்கள்',
      services: 'தொழில்முறை சேவைகள்',
      education: 'கல்வி & பயிற்சி',
      transport: 'போக்குவரத்து & பயணம்',
      online: 'ஆன்லைன் / D2C விற்பனையாளர்',
      other: 'மற்றவை',
    },
  },

  home: {
    greeting: 'வணக்கம்',
    summary: {
      title: 'இன்றைய வசூல்',
      collected: 'இன்று பெற்றது',
      txnCount: '{{count}} பணம்',
      txnCount_plural: '{{count}} பணப்பட்டுவாடா',
      pendingSettlement: 'செட்டில்மென்ட் நிலுவை',
      settlementHint: 'உங்கள் வங்கிக் கணக்கில் வரவு வைக்கப்படும்',
    },
    collectCta: 'பணம் பெறு',
    quickActions: {
      title: 'விரைவு செயல்கள்',
      myQr: 'எனது QR',
      paymentLink: 'கட்டண இணைப்பு',
      reports: 'அறிக்கைகள்',
      refund: 'திரும்பப் பணம்',
    },
    recent: {
      title: 'சமீபத்திய பணம்',
      emptyTitle: 'இன்னும் பணம் இல்லை',
      emptyBody: 'முதல் பணத்தைப் பெற வாடிக்கையாளரிடம் உங்கள் QR-ஐக் காட்டுங்கள்.',
      emptyCta: 'எனது QR காட்டு',
    },
    kycNudge: {
      title: 'சரிபார்ப்பை முடிக்கவும்',
      body: 'வரம்புகளை நீக்க உங்கள் விவரங்களை முடிக்கவும்.',
      cta: 'தொடரவும்',
    },
    error: {
      title: 'டாஷ்போர்டை ஏற்ற முடியவில்லை',
      body: 'இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    },
  },

  notifications: {
    title: 'அறிவிப்புகள்',
    emptyTitle: 'அறிவிப்புகள் இல்லை',
    emptyBody: 'பணம் மற்றும் செட்டில்மென்ட் புதுப்பிப்புகள் இங்கு தெரியும்.',
  },

  transactions: {
    title: 'பணப்பட்டுவாடா',
    status: {
      success: 'கிடைத்தது',
      pending: 'நிலுவை',
      failed: 'தோல்வி',
      refunded: 'திரும்பியது',
      partially_refunded: 'பகுதி திரும்பியது',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI செயலி',
      payment_link: 'கட்டண இணைப்பு',
      card: 'அட்டை',
      netbanking: 'நெட் பேங்கிங்',
      wallet: 'வாலட்',
    },
    filters: {
      all: 'அனைத்தும்',
      success: 'கிடைத்தது',
      pending: 'நிலுவை',
      failed: 'தோல்வி',
      refunded: 'திரும்பியது',
    },
    searchPlaceholder: 'தொகை, UTR அல்லது செலுத்தியவரைத் தேடு',
    emptyTitle: 'பணப்பட்டுவாடா இல்லை',
    emptyBody: 'நீங்கள் பெறும் பணம் இங்கு தெரியும்.',
    emptyFilteredTitle: 'எதுவும் பொருந்தவில்லை',
    emptyFilteredBody: 'வேறு வடிகட்டி அல்லது தேதியைத் தேர்ந்தெடுக்கவும்.',
    clearFilters: 'வடிகட்டிகளை நீக்கு',
    resultCount: '{{count}} பணப்பட்டுவாடா',
    resultCount_plural: '{{count}} பணப்பட்டுவாடாக்கள்',
    loadingMore: 'மேலும் ஏற்றுகிறது…',
    endOfList: 'இதுவே அனைத்தும்',
    detail: {
      title: 'கட்டண விவரங்கள்',
      amountLabel: 'தொகை',
      statusLabel: 'நிலை',
      modeLabel: 'எதன் மூலம்',
      txnIdLabel: 'பணப்பட்டுவாடா ID',
      utrLabel: 'UTR / RRN',
      timeLabel: 'தேதி மற்றும் நேரம்',
      payerLabel: 'செலுத்தியவர்',
      noteLabel: 'குறிப்பு',
      breakdownTitle: 'விவரக்கணக்கு',
      grossLabel: 'பெற்ற தொகை',
      feeLabel: 'கட்டணம் (MDR)',
      netLabel: 'உங்களுக்கு கிடைக்கும்',
      noFee: 'கட்டணம் இல்லை',
      settlementTitle: 'செட்டில்மென்ட்',
      settlementPending: 'உங்கள் வங்கிக் கணக்கில் அனுப்பப்படும்',
      settlementDone: 'உங்கள் வங்கிக் கணக்கில் அனுப்பப்பட்டது',
      viewSettlement: 'செட்டில்மென்ட்டைப் பார்',
      refundedLabel: 'இதுவரை திரும்பியது',
      actions: 'செயல்கள்',
      refund: 'திரும்பப் பணம்',
      shareReceipt: 'ரசீதைப் பங்கிடு',
      raiseDispute: 'புகார் அளி',
      reportIssue: 'சிக்கலைத் தெரிவி',
      notRefundable: 'இந்தக் கட்டணத்தைத் திரும்ப அளிக்க முடியாது',
      receiptMessage: '{{time}} இல் {{amount}} கிடைத்தது. பணப்பட்டுவாடா ID: {{id}}.',
    },
  },

  refund: {
    title: 'பணம் திரும்ப அளி',
    originalLabel: 'அசல் கட்டணம்',
    refundableLabel: 'திரும்ப அளிக்கக் கிடைக்கும்',
    alreadyRefunded: '{{amount}} ஏற்கனவே திரும்ப அளிக்கப்பட்டது',
    typeFull: 'முழு தொகை',
    typePartial: 'பகுதி தொகை',
    fullBody: 'முழுத் தொகையையும் திரும்ப அளி',
    partialBody: 'தொகையின் ஒரு பகுதியைத் திரும்ப அளி',
    amountLabel: 'திரும்ப அளிக்கும் தொகை',
    reasonLabel: 'காரணம்',
    reasonPlaceholder: 'ஏன் திரும்ப அளிக்கிறீர்கள்? (விரும்பினால்)',
    exceedsRefundable: '{{max}} க்கு மேல் திரும்ப அளிக்க முடியாது',
    tooLow: '{{min}} க்கு மேல் தொகையை உள்ளிடவும்',
    confirmCta: '{{amount}} திரும்ப அளி',
    reauthReason: '{{amount}} திரும்ப அளிப்பதை உறுதிப்படுத்தவும்',
    processingTitle: 'திரும்ப அளிக்கிறது…',
    processingBody: 'செயலியைத் திறந்தே வைக்கவும்.',
    successTitle: 'திரும்ப அளிப்பு தொடங்கியது',
    successBody: '{{amount}} வாடிக்கையாளருக்குத் திரும்ப அனுப்பப்படுகிறது. வழக்கமாக 3-5 வேலை நாட்கள் ஆகும்.',
    successDone: 'முடிந்தது',
    offlineTitle: 'இணையம் இல்லை',
    offlineBody: 'திரும்ப அளிக்க இணைய இணைப்பு தேவை.',
    notEligibleTitle: 'திரும்ப அளிக்க முடியாது',
    notEligibleBody: 'வெற்றிபெற்ற கட்டணங்களை மட்டுமே திரும்ப அளிக்க முடியும்.',
  },

  appLock: {
    title: 'நீங்களே என்பதை உறுதிப்படுத்தவும்',
    biometricPrompt: 'உறுதிப்படுத்த கைரேகை அல்லது முகத்தைப் பயன்படுத்தவும்',
    biometricFailed: 'சரிபார்க்க முடியவில்லை. அதற்குப் பதிலாக PIN உள்ளிடவும்.',
    usePin: 'PIN பயன்படுத்து',
    pinIncorrect: 'தவறான PIN. {{count}} முயற்சிகள் உள்ளன.',
    lockedOut: 'பல தவறான முயற்சிகள். செயலியை மூடி மீண்டும் திறக்கவும்.',
    setupTitle: 'செயலி PIN உருவாக்கு',
    setupBody: 'திரும்ப அளிப்பு போன்ற முக்கியச் செயல்களை அனுமதிக்க {{min}} இலக்க PIN தேர்ந்தெடுக்கவும்.',
    confirmTitle: 'PIN மீண்டும் உள்ளிடவும்',
    pinMismatch: 'PIN பொருந்தவில்லை. மீண்டும் முயற்சிக்கவும்.',
    pinTooShort: 'PIN குறைந்தது {{min}} இலக்கமாக இருக்க வேண்டும்',
  },

  dateRange: {
    label: 'தேதி வரம்பு',
    all: 'எல்லா நேரமும்',
    today: 'இன்று',
    yesterday: 'நேற்று',
    last7: 'கடந்த 7 நாட்கள்',
    last30: 'கடந்த 30 நாட்கள்',
    thisMonth: 'இந்த மாதம்',
    custom: 'சொந்த வரம்பு',
    from: 'முதல்',
    to: 'வரை',
  },

  settlements: {
    title: 'செட்டில்மென்ட்',
    status: {
      pending: 'நிலுவை',
      processing: 'நடைபெறுகிறது',
      settled: 'வரவு வைக்கப்பட்டது',
      failed: 'தோல்வி',
    },
  },

  collect: {
    title: 'பணம் பெறு',
    subtitle: 'எப்படி பணம் பெற விரும்புகிறீர்கள்?',
    modes: {
      staticQr: 'எனது QR குறியீடு',
      staticQrBody: 'எந்தத் தொகைக்கும் ஒரே குறியீடு. காட்டுங்கள் அல்லது அச்சிடுங்கள்.',
      dynamicQr: 'தொகையை உள்ளிடு',
      dynamicQrBody: 'குறிப்பிட்ட தொகைக்கு QR உருவாக்குங்கள்.',
      paymentLink: 'கட்டண இணைப்பு',
      paymentLinkBody: 'WhatsApp அல்லது SMS இல் இணைப்பை அனுப்புங்கள்.',
    },
    staticQr: {
      title: 'எனது QR குறியீடு',
      instruction: 'ஸ்கேன் செய்து எந்தத் தொகையையும் செலுத்தச் சொல்லுங்கள்.',
      vpaLabel: 'UPI ID',
      noQrTitle: 'QR இன்னும் தயாராகவில்லை',
      noQrBody: 'QR குறியீடு பெற வங்கி சரிபார்ப்பை முடிக்கவும்.',
      noQrCta: 'சரிபார்ப்பை முடிக்கவும்',
      offlineUsable: 'உங்கள் QR இணையம் இல்லாமலும் வேலை செய்யும்.',
    },
    amount: {
      title: 'தொகையை உள்ளிடு',
      generateQr: 'QR உருவாக்கு',
      createLink: 'இணைப்பை உருவாக்கு',
      noteLabel: 'குறிப்பு',
      notePlaceholder: 'எதற்காக? (விரும்பினால்)',
      tooLow: '{{min}} க்கு மேல் தொகையை உள்ளிடவும்',
      limitExceeded: 'சரிபார்ப்பு முடியும் வரை தினசரி வரம்பு {{limit}}',
      upiCap: 'ஒரு UPI கட்டணத்திற்கு அதிகபட்சம் {{max}}',
    },
    dynamicQr: {
      title: 'செலுத்த ஸ்கேன் செய்யுங்கள்',
      waiting: 'பணத்திற்குக் காத்திருக்கிறது…',
      waitingBody: 'இந்தக் குறியீட்டை ஸ்கேன் செய்யச் சொல்லுங்கள்.',
      expiresIn: '{{time}} இல் காலாவதியாகும்',
      expiredTitle: 'QR காலாவதியானது',
      expiredBody: 'இந்தக் குறியீடு இப்போது செல்லாது. புதியதை உருவாக்குங்கள்.',
      newQr: 'புதிய QR உருவாக்கு',
      cancel: 'ரத்து',
      checkingSlowly: 'இன்னும் சரிபார்க்கிறது. உங்கள் இணைப்பு மெதுவாக உள்ளது.',
      failedTitle: 'கட்டணம் தோல்வி',
      failedBody: 'வாடிக்கையாளரின் கட்டணம் நிறைவேறவில்லை. மீண்டும் முயற்சிக்கச் சொல்லுங்கள்.',
      offlineTitle: 'இணையம் இல்லை',
      offlineBody: 'நிலையான தொகைக்கான QR க்கு இணையம் தேவை. அதற்குப் பதிலாக உங்கள் QR-ஐப் பயன்படுத்துங்கள்.',
      useStaticQr: 'எனது QR-ஐப் பயன்படுத்து',
    },
    link: {
      title: 'கட்டண இணைப்பு',
      createdTitle: 'இணைப்பு தயார்',
      createdBody: 'இதை வாடிக்கையாளருக்கு அனுப்புங்கள். 24 மணி நேரத்தில் காலாவதியாகும்.',
      copy: 'இணைப்பை நகலெடு',
      copied: 'இணைப்பு நகலெடுக்கப்பட்டது',
      shareVia: 'இணைப்பைப் பங்கிடு',
      newLink: 'மற்றொன்றை உருவாக்கு',
      shareMessage: 'இந்த இணைப்பைப் பயன்படுத்தி {{amount}} செலுத்துங்கள்: {{url}}',
    },
    success: {
      title: 'பணம் கிடைத்தது!',
      amountLabel: 'பெற்ற தொகை',
      txnIdLabel: 'பணப்பட்டுவாடா ID',
      timeLabel: 'நேரம்',
      payerLabel: 'செலுத்தியவர்',
      utrLabel: 'UPI குறிப்பு',
      shareReceipt: 'ரசீதைப் பங்கிடு',
      newPayment: 'புதிய கட்டணம்',
      done: 'முடிந்தது',
      receiptMessage: 'பணம் கிடைத்தது: {{time}} இல் {{amount}}. பணப்பட்டுவாடா ID: {{id}}.',
    },
    audio: {
      received: '{{amount}} ரூபாய் கிடைத்தது',
      mutedHint: 'ஒலி உறுதிப்படுத்தல் அணைக்கப்பட்டுள்ளது. அமைப்புகளில் இயக்கவும்.',
    },
  },
};

export default ta;
