import type { TranslationBundle } from './en';

/** Tamil (தமிழ்) */
export const ta: TranslationBundle = {
  common: {
    appName: 'MerchantOne',
    ok: 'சரி',
    cancel: 'ரத்து',
    continue: 'தொடரவும்',
    back: 'பின்',
    next: 'அடுத்து',
    skip: 'தவிர்',
    done: 'முடிந்தது',
    retry: 'மீண்டும் முயற்சிக்கவும்',
    save: 'சேமி',
    close: 'மூடு',
    share: 'பங்கிடு',
    download: 'பதிவிறக்கு',
    search: 'தேடு',
    viewAll: 'அனைத்தையும் காண்க',
    today: 'இன்று',
    yesterday: 'நேற்று',
    loading: 'ஏற்றுகிறது…',
    yes: 'ஆம்',
    no: 'இல்லை',
    optional: 'விரும்பினால்',
    verified: 'சரிபார்க்கப்பட்டது',
    verifying: 'சரிபார்க்கிறது…',
    edit: 'திருத்து',
    remove: 'நீக்கு',
    confirm: 'உறுதிப்படுத்து',
    comingSoon: 'விரைவில்',
    comingSoonBody: 'இந்தப் பகுதி உருவாக்கப்படுகிறது.',
    months: {
      jan: 'ஜன',
      feb: 'பிப்',
      mar: 'மார்',
      apr: 'ஏப்',
      may: 'மே',
      jun: 'ஜூன்',
      jul: 'ஜூலை',
      aug: 'ஆக',
      sep: 'செப்',
      oct: 'அக்',
      nov: 'நவ',
      dec: 'டிச',
    },
  },

  a11y: {
    back: 'பின் செல்',
    close: 'மூடு',
    notifications: 'அறிவிப்புகள்',
    loading: 'உள்ளடக்கம் ஏற்றுகிறது',
    amount: 'தொகை {{amount}}',
    step: 'படி {{current}} / {{total}}',
  },

  tabs: {
    home: 'முகப்பு',
    collect: 'பணம் பெறு',
    transactions: 'பணப்பட்டுவாடா',
    settlements: 'செட்டில்மென்ட்',
    more: 'மேலும்',
  },

  network: {
    offlineTitle: 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள்',
    offlineBanner: 'இணைய இணைப்பு இல்லை. சேமித்த தகவல் காட்டப்படுகிறது.',
    offlineActionDisabled: 'இதற்கு இணைய இணைப்பு தேவை.',
    backOnline: 'இணைப்பு திரும்பியது',
  },

  errors: {
    title: 'ஏதோ தவறு நடந்தது',
    network_error: 'சர்வரைத் தொடர்பு கொள்ள முடியவில்லை. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    timeout: 'அதிக நேரம் ஆகிறது. மீண்டும் முயற்சிக்கவும்.',
    offline: 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள். இணைந்து மீண்டும் முயற்சிக்கவும்.',
    unauthorized: 'உங்கள் அமர்வு முடிந்தது. மீண்டும் உள்நுழையவும்.',
    forbidden: 'இதைச் செய்ய உங்களுக்கு அனுமதி இல்லை.',
    not_found: 'நீங்கள் தேடியது கிடைக்கவில்லை.',
    validation_error: 'நீங்கள் உள்ளிட்ட விவரங்களைச் சரிபார்க்கவும்.',
    rate_limited: 'அதிக முயற்சிகள். சிறிது நேரம் கழித்து முயற்சிக்கவும்.',
    invalid_otp: 'இந்த OTP தவறு. சரிபார்த்து மீண்டும் உள்ளிடவும்.',
    otp_expired: 'இந்த OTP காலாவதியானது. புதியதைக் கோரவும்.',
    invalid_mobile: 'சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.',
    kyc_incomplete: 'இந்த வசதிக்கு உங்கள் KYC-ஐ முடிக்கவும்.',
    kyc_rejected: 'உங்கள் KYC ஏற்கப்படவில்லை. சரிபார்த்து மீண்டும் சமர்ப்பிக்கவும்.',
    bank_verification_failed: 'இந்த வங்கிக் கணக்கைச் சரிபார்க்க முடியவில்லை. விவரங்களைச் சரிபார்க்கவும்.',
    pan_verification_failed: 'இந்த PAN-ஐச் சரிபார்க்க முடியவில்லை. எண்ணைச் சரிபார்க்கவும்.',
    already_refunded: 'இந்தப் பணப்பட்டுவாடாவுக்கு ஏற்கனவே பணம் திரும்பப் பெறப்பட்டது.',
    refund_limit_exceeded: 'திரும்பப் பெறும் தொகை கிடைக்கும் தொகையை விட அதிகம்.',
    payment_expired: 'இந்தக் கட்டணக் கோரிக்கை காலாவதியானது. புதியதை உருவாக்கவும்.',
    server_error: 'எங்கள் சர்வரில் சிக்கல். சிறிது நேரம் கழித்து முயற்சிக்கவும்.',
    unknown: 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.',
  },

  auth: {
    splash: {
      tagline: 'எளிய பணப்பரிவர்த்தனை',
    },
    login: {
      title: 'வரவேற்கிறோம்',
      subtitle: 'உங்கள் வணிகத்தை நிர்வகிக்க மொபைல் எண்ணுடன் உள்நுழையவும்',
      mobileLabel: 'மொபைல் எண்',
      mobilePlaceholder: '10 இலக்க மொபைல் எண்',
      mobileRequired: 'உங்கள் மொபைல் எண்ணை உள்ளிடவும்',
      mobileInvalid: 'சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்',
      consent: 'சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கிறேன்',
      consentRequired: 'தொடர விதிமுறைகளை ஏற்கவும்',
      getOtp: 'OTP பெறு',
      secureNote: 'உங்கள் எண்ணைச் சரிபார்க்க 6 இலக்கக் குறியீட்டை அனுப்புவோம்.',
    },
    otp: {
      title: 'உங்கள் எண்ணைச் சரிபார்க்கவும்',
      subtitle: '{{mobile}} க்கு அனுப்பிய 6 இலக்கக் குறியீட்டை உள்ளிடவும்',
      otpRequired: '6 இலக்கக் குறியீட்டை உள்ளிடவும்',
      otpInvalid: 'குறியீடு 6 இலக்கமாக இருக்க வேண்டும்',
      verify: 'சரிபார்',
      resend: 'குறியீட்டை மீண்டும் அனுப்பு',
      resendIn: '{{seconds}} வினாடிகளில் மீண்டும் அனுப்பு',
      changeNumber: 'எண்ணை மாற்று',
      autoReadHint: 'அனுமதி இருந்தால் குறியீட்டை தானாகப் படிப்போம்.',
      hintDev: 'டெமோ முறை: {{otp}} உள்ளிடவும்',
    },
  },

  kyc: {
    title: 'வணிகச் சரிபார்ப்பு',
    stepOf: 'படி {{current}} / {{total}}',
    saveAndExit: 'சேமித்து வெளியேறு',
    resumeTitle: 'சரிபார்ப்பைத் தொடரவும்',
    resumeBody: 'நீங்கள் படி {{step}} இல் நிற்கிறீர்கள். அங்கிருந்து தொடரவும்.',
    progress: {
      business: 'வணிகம்',
      identity: 'அடையாளம்',
      bank: 'வங்கி',
      aadhaar: 'ஆதார்',
    },
    business: {
      title: 'உங்கள் வணிகம் பற்றிக் கூறுங்கள்',
      subtitle: 'வாடிக்கையாளர்கள் ஸ்கேன் செய்யும் QR-இல் இது தெரியும்.',
      name: 'வணிகப் பெயர்',
      namePlaceholder: 'உதா. சர்மா ஜெனரல் ஸ்டோர்',
      nameRequired: 'உங்கள் வணிகப் பெயரை உள்ளிடவும்',
      nameTooShort: 'பெயர் குறைந்தது 3 எழுத்துகள் இருக்க வேண்டும்',
      category: 'வணிக வகை',
      categoryPlaceholder: 'ஒரு வகையைத் தேர்ந்தெடுக்கவும்',
      categoryRequired: 'உங்கள் வணிக வகையைத் தேர்ந்தெடுக்கவும்',
      categorySheetTitle: 'வணிக வகையைத் தேர்ந்தெடுக்கவும்',
      addressLine1: 'கடை / கட்டிட முகவரி',
      addressPlaceholder: 'கடை எண், தெரு, பகுதி',
      addressRequired: 'உங்கள் வணிக முகவரியை உள்ளிடவும்',
      pincode: 'PIN குறியீடு',
      pincodePlaceholder: '6 இலக்க PIN குறியீடு',
      pincodeRequired: 'உங்கள் PIN குறியீட்டை உள்ளிடவும்',
      pincodeInvalid: 'சரியான 6 இலக்க PIN குறியீட்டை உள்ளிடவும்',
      city: 'நகரம்',
      cityRequired: 'உங்கள் நகரத்தை உள்ளிடவும்',
      state: 'மாநிலம்',
      stateRequired: 'உங்கள் மாநிலத்தை உள்ளிடவும்',
      pincodeLookup: 'உங்கள் பகுதியைத் தேடுகிறது…',
    },
    identity: {
      title: 'அடையாள விவரங்கள்',
      subtitle: 'பணம் பெற RBI கட்டாயமாக்கியுள்ளது.',
      pan: 'PAN எண்',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'உங்கள் PAN எண்ணை உள்ளிடவும்',
      panInvalid: 'சரியான PAN உள்ளிடவும் (உதா. ABCDE1234F)',
      panHelp: 'உங்கள் PAN அட்டையில் உள்ளது போல.',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'சரியான 15 எழுத்து GSTIN உள்ளிடவும்',
      gstinHelp: 'GST விலைப்பட்டியல் வேண்டுமெனில் இதைச் சேர்க்கவும்.',
    },
    bank: {
      title: 'உங்கள் பணத்தை எங்கு அனுப்ப வேண்டும்?',
      subtitle: 'உங்கள் வசூல் இங்கு வரும், வழக்கமாக அடுத்த நாள்.',
      accountNumber: 'கணக்கு எண்',
      accountNumberPlaceholder: 'வங்கிக் கணக்கு எண்',
      accountNumberRequired: 'உங்கள் கணக்கு எண்ணை உள்ளிடவும்',
      accountNumberInvalid: 'கணக்கு எண் 9 முதல் 18 இலக்கங்களாக இருக்க வேண்டும்',
      confirmAccountNumber: 'கணக்கு எண்ணை மீண்டும் உள்ளிடவும்',
      accountMismatch: 'கணக்கு எண்கள் பொருந்தவில்லை',
      ifsc: 'IFSC குறியீடு',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'IFSC குறியீட்டை உள்ளிடவும்',
      ifscInvalid: 'சரியான IFSC உள்ளிடவும் (உதா. HDFC0001234)',
      holderName: 'கணக்கு வைத்திருப்பவர் பெயர்',
      holderNamePlaceholder: 'வங்கிப் பதிவின் படி பெயர்',
      holderNameRequired: 'கணக்கு வைத்திருப்பவர் பெயரை உள்ளிடவும்',
      verifyCta: 'கணக்கைச் சரிபார்',
      verifying: 'உங்கள் கணக்கைச் சரிபார்க்கிறது…',
      verifyingBody: 'இந்தக் கணக்கு உங்களுடையது என உறுதிப்படுத்த ₹1 அனுப்புகிறோம்.',
      verifiedTitle: 'கணக்கு சரிபார்க்கப்பட்டது',
      verifiedNameAtBank: 'வங்கியில் பெயர்: {{name}}',
      unlockNote: 'இந்தப் படிக்குப் பிறகு வரம்புகளுடன் பணம் பெறத் தொடங்கலாம், சோதனை முடியும் வரை.',
    },
    aadhaar: {
      title: 'ஆதார் சரிபார்ப்பு',
      subtitle: 'அனைத்து வசதிகளையும் திறக்க கடைசிப் படி.',
      numberLabel: 'ஆதார் எண்',
      numberPlaceholder: '12 இலக்க ஆதார் எண்',
      numberRequired: 'உங்கள் ஆதார் எண்ணை உள்ளிடவும்',
      numberInvalid: 'ஆதார் எண் 12 இலக்கமாக இருக்க வேண்டும்',
      consent: 'ஆதார் eKYC மூலம் எனது அடையாளத்தைச் சரிபார்க்க ஒப்புதல் அளிக்கிறேன். எனது ஆதார் விவரங்கள் இந்தச் சரிபார்ப்புக்கு மட்டுமே பயன்படும் என்பதைப் புரிந்துகொள்கிறேன்.',
      consentRequired: 'தொடர உங்கள் ஒப்புதல் தேவை',
      sendOtp: 'ஆதார் OTP அனுப்பு',
      otpLabel: 'ஆதார் OTP',
      otpSentTo: 'ஆதாருடன் இணைந்த மொபைலுக்கு அனுப்பிய குறியீட்டை உள்ளிடவும்.',
      otpRequired: '6 இலக்க ஆதார் OTP உள்ளிடவும்',
      verifyCta: 'ஆதாரைச் சரிபார்',
      verifiedTitle: 'ஆதார் சரிபார்க்கப்பட்டது',
      skipForNow: 'பிறகு செய்',
      privacyNote: 'உங்கள் முழு ஆதார் எண்ணை நாங்கள் சேமிப்பதில்லை.',
    },
    done: {
      title: 'எல்லாம் தயார்!',
      subtitle: 'உங்கள் விவரங்கள் சமர்ப்பிக்கப்பட்டன. இப்போதே பணம் பெறத் தொடங்கலாம்.',
      pendingTitle: 'சரிபார்ப்பு நடக்கிறது',
      pendingSubtitle: 'உங்கள் விவரங்களை ஆய்வு செய்கிறோம். வழக்கமாக சில மணி நேரம் ஆகும்.',
      generateQr: 'எனது QR உருவாக்கு',
      goHome: 'டாஷ்போர்டுக்குச் செல்',
      vpaLabel: 'உங்கள் UPI ID',
      limitsNote: 'சரிபார்ப்பு முடியும் வரை நாளொன்றுக்கு {{limit}} வரை பெறலாம்.',
    },
    status: {
      not_started: 'KYC நிலுவை',
      in_progress: 'KYC முழுமையடையவில்லை',
      pending_review: 'ஆய்வில் உள்ளது',
      approved: 'சரிபார்க்கப்பட்டது',
      rejected: 'நடவடிக்கை தேவை',
    },
    rejected: {
      title: 'மீண்டும் பார்க்க வேண்டும்',
      reasonLabel: 'காரணம்',
      retryCta: 'விவரங்களைப் புதுப்பி',
    },
    submitCta: 'சரிபார்ப்புக்கு சமர்ப்பி',
    mcc: {
      grocery: 'மளிகை / கிரானா கடை',
      restaurant: 'உணவகம் / கஃபே',
      apparel: 'ஆடைகள்',
      electronics: 'மின்னணு பொருட்கள் & மொபைல்',
      pharmacy: 'மருந்தகம் / மருத்துவம்',
      salon: 'சலூன் & அழகு',
      hardware: 'ஹார்டுவேர் & கட்டுமானப் பொருட்கள்',
      services: 'தொழில்முறை சேவைகள்',
      education: 'கல்வி & பயிற்சி',
      transport: 'போக்குவரத்து & பயணம்',
      online: 'ஆன்லைன் / D2C விற்பனையாளர்',
      other: 'மற்றவை',
    },
  },

  home: {
    greeting: 'வணக்கம்',
    summary: {
      title: 'இன்றைய வசூல்',
      collected: 'இன்று பெற்றது',
      txnCount: '{{count}} பணம்',
      txnCount_plural: '{{count}} பணப்பட்டுவாடா',
      pendingSettlement: 'செட்டில்மென்ட் நிலுவை',
      settlementHint: 'உங்கள் வங்கிக் கணக்கில் வரவு வைக்கப்படும்',
    },
    collectCta: 'பணம் பெறு',
    quickActions: {
      title: 'விரைவு செயல்கள்',
      myQr: 'எனது QR',
      paymentLink: 'கட்டண இணைப்பு',
      reports: 'அறிக்கைகள்',
      refund: 'திரும்பப் பணம்',
    },
    recent: {
      title: 'சமீபத்திய பணம்',
      emptyTitle: 'இன்னும் பணம் இல்லை',
      emptyBody: 'முதல் பணத்தைப் பெற வாடிக்கையாளரிடம் உங்கள் QR-ஐக் காட்டுங்கள்.',
      emptyCta: 'எனது QR காட்டு',
    },
    kycNudge: {
      title: 'சரிபார்ப்பை முடிக்கவும்',
      body: 'வரம்புகளை நீக்க உங்கள் விவரங்களை முடிக்கவும்.',
      cta: 'தொடரவும்',
    },
    error: {
      title: 'டாஷ்போர்டை ஏற்ற முடியவில்லை',
      body: 'இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    },
  },

  notifications: {
    title: 'அறிவிப்புகள்',
    emptyTitle: 'அறிவிப்புகள் இல்லை',
    emptyBody: 'பணம் மற்றும் செட்டில்மென்ட் புதுப்பிப்புகள் இங்கு தெரியும்.',
  },

  transactions: {
    title: 'பணப்பட்டுவாடா',
    status: {
      success: 'கிடைத்தது',
      pending: 'நிலுவை',
      failed: 'தோல்வி',
      refunded: 'திரும்பியது',
      partially_refunded: 'பகுதி திரும்பியது',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI செயலி',
      payment_link: 'கட்டண இணைப்பு',
      card: 'அட்டை',
      netbanking: 'நெட் பேங்கிங்',
      wallet: 'வாலட்',
    },
  },

  settlements: {
    title: 'செட்டில்மென்ட்',
    status: {
      pending: 'நிலுவை',
      processing: 'நடைபெறுகிறது',
      settled: 'வரவு வைக்கப்பட்டது',
      failed: 'தோல்வி',
    },
  },
};

export default ta;
