import type { TranslationBundle } from './en';

/** Telugu (తెలుగు) */
export const te: TranslationBundle = {
  common: {
    appName: 'MerchantOne',
    ok: 'సరే',
    cancel: 'రద్దు',
    continue: 'కొనసాగించు',
    back: 'వెనుక',
    next: 'తదుపరి',
    skip: 'దాటవేయి',
    done: 'పూర్తయింది',
    retry: 'మళ్లీ ప్రయత్నించండి',
    save: 'సేవ్ చేయి',
    close: 'మూసివేయి',
    share: 'షేర్ చేయి',
    download: 'డౌన్‌లోడ్',
    search: 'వెతుకు',
    viewAll: 'అన్నీ చూడు',
    today: 'ఈరోజు',
    yesterday: 'నిన్న',
    loading: 'లోడ్ అవుతోంది…',
    yes: 'అవును',
    no: 'కాదు',
    optional: 'ఐచ్ఛికం',
    verified: 'ధృవీకరించబడింది',
    verifying: 'ధృవీకరిస్తోంది…',
    edit: 'మార్చు',
    remove: 'తీసివేయి',
    confirm: 'నిర్ధారించు',
    comingSoon: 'త్వరలో',
    comingSoonBody: 'ఈ విభాగం తయారవుతోంది.',
    months: {
      jan: 'జన',
      feb: 'ఫిబ్ర',
      mar: 'మార్చి',
      apr: 'ఏప్రి',
      may: 'మే',
      jun: 'జూన్',
      jul: 'జూలై',
      aug: 'ఆగ',
      sep: 'సెప్',
      oct: 'అక్టో',
      nov: 'నవం',
      dec: 'డిసం',
    },
  },

  a11y: {
    back: 'వెనక్కి వెళ్లు',
    close: 'మూసివేయి',
    notifications: 'నోటిఫికేషన్లు',
    loading: 'కంటెంట్ లోడ్ అవుతోంది',
    amount: 'మొత్తం {{amount}}',
    step: 'దశ {{current}} / {{total}}',
  },

  tabs: {
    home: 'హోమ్',
    collect: 'డబ్బు తీసుకో',
    transactions: 'లావాదేవీలు',
    settlements: 'సెటిల్‌మెంట్లు',
    more: 'మరిన్ని',
  },

  network: {
    offlineTitle: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు',
    offlineBanner: 'ఇంటర్నెట్ లేదు. సేవ్ చేసిన డేటా చూపిస్తోంది.',
    offlineActionDisabled: 'దీనికి ఇంటర్నెట్ కనెక్షన్ అవసరం.',
    backOnline: 'ఇంటర్నెట్ తిరిగి వచ్చింది',
  },

  errors: {
    title: 'ఏదో తప్పు జరిగింది',
    network_error: 'సర్వర్‌ను చేరుకోలేకపోతున్నాము. కనెక్షన్ చూసి మళ్లీ ప్రయత్నించండి.',
    timeout: 'చాలా సమయం పడుతోంది. మళ్లీ ప్రయత్నించండి.',
    offline: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు. ఇంటర్నెట్‌కు కనెక్ట్ అయి మళ్లీ ప్రయత్నించండి.',
    unauthorized: 'మీ సెషన్ ముగిసింది. దయచేసి మళ్లీ లాగిన్ అవ్వండి.',
    forbidden: 'ఇది చేయడానికి మీకు అనుమతి లేదు.',
    not_found: 'మీరు వెతుకుతున్నది కనబడలేదు.',
    validation_error: 'మీరు నమోదు చేసిన వివరాలను తనిఖీ చేయండి.',
    rate_limited: 'చాలా ప్రయత్నాలు. కొద్దిసేపు ఆగి ప్రయత్నించండి.',
    invalid_otp: 'ఈ OTP తప్పు. తనిఖీ చేసి మళ్లీ నమోదు చేయండి.',
    otp_expired: 'ఈ OTP గడువు ముగిసింది. కొత్తది అడగండి.',
    invalid_mobile: 'సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి.',
    kyc_incomplete: 'ఈ ఫీచర్ కోసం మీ KYC పూర్తి చేయండి.',
    kyc_rejected: 'మీ KYC ఆమోదించబడలేదు. తనిఖీ చేసి మళ్లీ సమర్పించండి.',
    bank_verification_failed: 'ఈ బ్యాంక్ ఖాతాను ధృవీకరించలేకపోయాము. వివరాలు తనిఖీ చేయండి.',
    pan_verification_failed: 'ఈ PAN ధృవీకరించలేకపోయాము. నంబర్ తనిఖీ చేయండి.',
    already_refunded: 'ఈ లావాదేవీకి ఇప్పటికే రీఫండ్ జరిగింది.',
    refund_limit_exceeded: 'రీఫండ్ మొత్తం అందుబాటులో ఉన్న మొత్తానికి మించి ఉంది.',
    payment_expired: 'ఈ చెల్లింపు అభ్యర్థన గడువు ముగిసింది. కొత్తది సృష్టించండి.',
    server_error: 'మా సర్వర్లలో సమస్య. కొద్దిసేపటి తర్వాత ప్రయత్నించండి.',
    unknown: 'ఏదో తప్పు జరిగింది. మళ్లీ ప్రయత్నించండి.',
  },

  auth: {
    splash: {
      tagline: 'చెల్లింపులు ఇప్పుడు సులభం',
    },
    login: {
      title: 'స్వాగతం',
      subtitle: 'మీ వ్యాపారాన్ని నిర్వహించడానికి మొబైల్ నంబర్‌తో లాగిన్ అవ్వండి',
      mobileLabel: 'మొబైల్ నంబర్',
      mobilePlaceholder: '10 అంకెల మొబైల్ నంబర్',
      mobileRequired: 'మీ మొబైల్ నంబర్ నమోదు చేయండి',
      mobileInvalid: 'సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి',
      consent: 'నేను సేవా నిబంధనలు మరియు గోప్యతా విధానాన్ని అంగీకరిస్తున్నాను',
      consentRequired: 'కొనసాగించడానికి నిబంధనలను అంగీకరించండి',
      getOtp: 'OTP పొందు',
      secureNote: 'మీ నంబర్ ధృవీకరించడానికి 6 అంకెల కోడ్ పంపుతాము.',
    },
    otp: {
      title: 'మీ నంబర్ ధృవీకరించండి',
      subtitle: '{{mobile}} కు పంపిన 6 అంకెల కోడ్ నమోదు చేయండి',
      otpRequired: '6 అంకెల కోడ్ నమోదు చేయండి',
      otpInvalid: 'కోడ్ 6 అంకెలు ఉండాలి',
      verify: 'ధృవీకరించు',
      resend: 'కోడ్ మళ్లీ పంపు',
      resendIn: '{{seconds}} సెకన్లలో మళ్లీ పంపు',
      changeNumber: 'నంబర్ మార్చు',
      autoReadHint: 'అనుమతి ఉంటే కోడ్‌ను మేమే చదువుతాము.',
      hintDev: 'డెమో మోడ్: {{otp}} వాడండి',
    },
  },

  kyc: {
    title: 'వ్యాపార ధృవీకరణ',
    stepOf: 'దశ {{current}} / {{total}}',
    saveAndExit: 'సేవ్ చేసి బయటకు',
    resumeTitle: 'ధృవీకరణ కొనసాగించు',
    resumeBody: 'మీరు దశ {{step}} వద్ద ఆగారు. అక్కడి నుంచి కొనసాగించండి.',
    progress: {
      business: 'వ్యాపారం',
      identity: 'గుర్తింపు',
      bank: 'బ్యాంక్',
      aadhaar: 'ఆధార్',
    },
    business: {
      title: 'మీ వ్యాపారం గురించి చెప్పండి',
      subtitle: 'కస్టమర్లు స్కాన్ చేసే QR పై ఇది కనిపిస్తుంది.',
      name: 'వ్యాపార పేరు',
      namePlaceholder: 'ఉదా. శర్మ జనరల్ స్టోర్',
      nameRequired: 'మీ వ్యాపార పేరు నమోదు చేయండి',
      nameTooShort: 'పేరు కనీసం 3 అక్షరాలు ఉండాలి',
      category: 'వ్యాపార విభాగం',
      categoryPlaceholder: 'ఒక విభాగాన్ని ఎంచుకోండి',
      categoryRequired: 'మీ వ్యాపార విభాగాన్ని ఎంచుకోండి',
      categorySheetTitle: 'వ్యాపార విభాగాన్ని ఎంచుకోండి',
      addressLine1: 'దుకాణం / భవనం చిరునామా',
      addressPlaceholder: 'దుకాణం నంబర్, వీధి, ప్రాంతం',
      addressRequired: 'మీ వ్యాపార చిరునామా నమోదు చేయండి',
      pincode: 'పిన్ కోడ్',
      pincodePlaceholder: '6 అంకెల పిన్ కోడ్',
      pincodeRequired: 'మీ పిన్ కోడ్ నమోదు చేయండి',
      pincodeInvalid: 'సరైన 6 అంకెల పిన్ కోడ్ నమోదు చేయండి',
      city: 'నగరం',
      cityRequired: 'మీ నగరం నమోదు చేయండి',
      state: 'రాష్ట్రం',
      stateRequired: 'మీ రాష్ట్రం నమోదు చేయండి',
      pincodeLookup: 'మీ ప్రాంతాన్ని వెతుకుతోంది…',
    },
    identity: {
      title: 'గుర్తింపు వివరాలు',
      subtitle: 'చెల్లింపులు స్వీకరించడానికి RBI తప్పనిసరి చేసింది.',
      pan: 'PAN నంబర్',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'మీ PAN నంబర్ నమోదు చేయండి',
      panInvalid: 'సరైన PAN నమోదు చేయండి (ఉదా. ABCDE1234F)',
      panHelp: 'మీ PAN కార్డుపై ఉన్నట్లుగా.',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'సరైన 15 అక్షరాల GSTIN నమోదు చేయండి',
      gstinHelp: 'GST బిల్లులు కావాలంటే ఇది జోడించండి.',
    },
    bank: {
      title: 'మీ డబ్బు ఎక్కడ జమ చేయాలి?',
      subtitle: 'మీ వసూళ్లు ఇక్కడ జమ అవుతాయి, సాధారణంగా మరుసటి రోజు.',
      accountNumber: 'ఖాతా నంబర్',
      accountNumberPlaceholder: 'బ్యాంక్ ఖాతా నంబర్',
      accountNumberRequired: 'మీ ఖాతా నంబర్ నమోదు చేయండి',
      accountNumberInvalid: 'ఖాతా నంబర్ 9 నుంచి 18 అంకెలు ఉండాలి',
      confirmAccountNumber: 'ఖాతా నంబర్ మళ్లీ నమోదు చేయండి',
      accountMismatch: 'ఖాతా నంబర్లు సరిపోలలేదు',
      ifsc: 'IFSC కోడ్',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'IFSC కోడ్ నమోదు చేయండి',
      ifscInvalid: 'సరైన IFSC నమోదు చేయండి (ఉదా. HDFC0001234)',
      holderName: 'ఖాతాదారు పేరు',
      holderNamePlaceholder: 'బ్యాంక్ రికార్డుల ప్రకారం పేరు',
      holderNameRequired: 'ఖాతాదారు పేరు నమోదు చేయండి',
      verifyCta: 'ఖాతా ధృవీకరించు',
      verifying: 'మీ ఖాతా ధృవీకరిస్తోంది…',
      verifyingBody: 'ఈ ఖాతా మీదేనని నిర్ధారించడానికి ₹1 పంపుతున్నాము.',
      verifiedTitle: 'ఖాతా ధృవీకరించబడింది',
      verifiedNameAtBank: 'బ్యాంకులో పేరు: {{name}}',
      unlockNote: 'ఈ దశ తర్వాత పరిమితులతో చెల్లింపులు స్వీకరించడం మొదలుపెట్టవచ్చు, తనిఖీలు పూర్తయ్యే వరకు.',
    },
    aadhaar: {
      title: 'ఆధార్ ధృవీకరణ',
      subtitle: 'అన్ని ఫీచర్లు తెరవడానికి చివరి దశ.',
      numberLabel: 'ఆధార్ నంబర్',
      numberPlaceholder: '12 అంకెల ఆధార్ నంబర్',
      numberRequired: 'మీ ఆధార్ నంబర్ నమోదు చేయండి',
      numberInvalid: 'ఆధార్ నంబర్ 12 అంకెలు ఉండాలి',
      consent: 'ఆధార్ eKYC ద్వారా నా గుర్తింపును ధృవీకరించడానికి నేను సమ్మతిస్తున్నాను. నా ఆధార్ వివరాలు ఈ ధృవీకరణ కోసమే వాడతారని నేను అర్థం చేసుకున్నాను.',
      consentRequired: 'కొనసాగడానికి మీ సమ్మతి అవసరం',
      sendOtp: 'ఆధార్ OTP పంపు',
      otpLabel: 'ఆధార్ OTP',
      otpSentTo: 'ఆధార్‌తో అనుసంధానమైన మొబైల్‌కు పంపిన కోడ్ నమోదు చేయండి.',
      otpRequired: '6 అంకెల ఆధార్ OTP నమోదు చేయండి',
      verifyCta: 'ఆధార్ ధృవీకరించు',
      verifiedTitle: 'ఆధార్ ధృవీకరించబడింది',
      skipForNow: 'తర్వాత చేయి',
      privacyNote: 'మీ పూర్తి ఆధార్ నంబర్‌ను మేము ఎప్పుడూ నిల్వ చేయము.',
    },
    done: {
      title: 'అంతా సిద్ధం!',
      subtitle: 'మీ వివరాలు సమర్పించబడ్డాయి. ఇప్పుడే చెల్లింపులు స్వీకరించవచ్చు.',
      pendingTitle: 'ధృవీకరణ జరుగుతోంది',
      pendingSubtitle: 'మీ వివరాలను పరిశీలిస్తున్నాము. సాధారణంగా కొన్ని గంటలు పడుతుంది.',
      generateQr: 'నా QR తయారు చేయి',
      goHome: 'డాష్‌బోర్డుకు వెళ్లు',
      vpaLabel: 'మీ UPI ID',
      limitsNote: 'ధృవీకరణ పూర్తయ్యే వరకు రోజుకు {{limit}} వరకు తీసుకోవచ్చు.',
    },
    status: {
      not_started: 'KYC పెండింగ్',
      in_progress: 'KYC అసంపూర్ణం',
      pending_review: 'పరిశీలనలో',
      approved: 'ధృవీకరించబడింది',
      rejected: 'చర్య అవసరం',
    },
    rejected: {
      title: 'మరోసారి చూడాలి',
      reasonLabel: 'కారణం',
      retryCta: 'వివరాలు నవీకరించు',
    },
    submitCta: 'ధృవీకరణకు సమర్పించు',
    mcc: {
      grocery: 'కిరాణా / జనరల్ స్టోర్',
      restaurant: 'రెస్టారెంట్ / కేఫ్',
      apparel: 'దుస్తులు',
      electronics: 'ఎలక్ట్రానిక్స్ & మొబైల్స్',
      pharmacy: 'మెడికల్ / ఫార్మసీ',
      salon: 'సెలూన్ & బ్యూటీ',
      hardware: 'హార్డ్‌వేర్ & నిర్మాణ సామగ్రి',
      services: 'వృత్తిపరమైన సేవలు',
      education: 'విద్య & కోచింగ్',
      transport: 'రవాణా & ప్రయాణం',
      online: 'ఆన్‌లైన్ / D2C విక్రేత',
      other: 'ఇతరం',
    },
  },

  home: {
    greeting: 'నమస్తే',
    summary: {
      title: 'ఈరోజు వసూళ్లు',
      collected: 'ఈరోజు వచ్చింది',
      txnCount: '{{count}} చెల్లింపు',
      txnCount_plural: '{{count}} చెల్లింపులు',
      pendingSettlement: 'సెటిల్‌మెంట్ పెండింగ్',
      settlementHint: 'మీ బ్యాంక్ ఖాతాలో జమ అవుతుంది',
    },
    collectCta: 'డబ్బు తీసుకో',
    quickActions: {
      title: 'త్వరిత చర్యలు',
      myQr: 'నా QR',
      paymentLink: 'చెల్లింపు లింక్',
      reports: 'నివేదికలు',
      refund: 'రీఫండ్',
    },
    recent: {
      title: 'ఇటీవలి చెల్లింపులు',
      emptyTitle: 'ఇంకా చెల్లింపులు లేవు',
      emptyBody: 'మొదటి చెల్లింపు పొందడానికి కస్టమర్‌కు మీ QR చూపించండి.',
      emptyCta: 'నా QR చూపించు',
    },
    kycNudge: {
      title: 'ధృవీకరణ పూర్తి చేయండి',
      body: 'పరిమితులు తొలగించడానికి మీ వివరాలు పూర్తి చేయండి.',
      cta: 'కొనసాగించు',
    },
    error: {
      title: 'డాష్‌బోర్డ్ లోడ్ కాలేదు',
      body: 'కనెక్షన్ చూసి మళ్లీ ప్రయత్నించండి.',
    },
  },

  notifications: {
    title: 'నోటిఫికేషన్లు',
    emptyTitle: 'నోటిఫికేషన్లు లేవు',
    emptyBody: 'చెల్లింపు మరియు సెటిల్‌మెంట్ అప్‌డేట్లు ఇక్కడ కనిపిస్తాయి.',
  },

  transactions: {
    title: 'లావాదేవీలు',
    status: {
      success: 'వచ్చింది',
      pending: 'పెండింగ్',
      failed: 'విఫలం',
      refunded: 'తిరిగి ఇచ్చాం',
      partially_refunded: 'పాక్షిక రీఫండ్',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI యాప్',
      payment_link: 'చెల్లింపు లింక్',
      card: 'కార్డ్',
      netbanking: 'నెట్ బ్యాంకింగ్',
      wallet: 'వాలెట్',
    },
    filters: {
      all: 'అన్నీ',
      success: 'వచ్చింది',
      pending: 'పెండింగ్',
      failed: 'విఫలం',
      refunded: 'తిరిగి ఇచ్చాం',
    },
    searchPlaceholder: 'మొత్తం, UTR లేదా చెల్లించినవారిని వెతకండి',
    emptyTitle: 'లావాదేవీలు లేవు',
    emptyBody: 'మీకు వచ్చే చెల్లింపులు ఇక్కడ కనిపిస్తాయి.',
    emptyFilteredTitle: 'ఏదీ సరిపోలలేదు',
    emptyFilteredBody: 'వేరే ఫిల్టర్ లేదా తేదీ ఎంచుకోండి.',
    clearFilters: 'ఫిల్టర్లు తీసివేయి',
    resultCount: '{{count}} లావాదేవీ',
    resultCount_plural: '{{count}} లావాదేవీలు',
    loadingMore: 'మరిన్ని లోడ్ అవుతోంది…',
    endOfList: 'ఇంతే',
    detail: {
      title: 'చెల్లింపు వివరాలు',
      amountLabel: 'మొత్తం',
      statusLabel: 'స్థితి',
      modeLabel: 'ఎలా వచ్చింది',
      txnIdLabel: 'లావాదేవీ ID',
      utrLabel: 'UTR / RRN',
      timeLabel: 'తేదీ మరియు సమయం',
      payerLabel: 'చెల్లించినవారు',
      noteLabel: 'గమనిక',
      breakdownTitle: 'వివరణ',
      grossLabel: 'వచ్చిన మొత్తం',
      feeLabel: 'ఫీజు (MDR)',
      netLabel: 'మీకు వస్తుంది',
      noFee: 'ఫీజు లేదు',
      settlementTitle: 'సెటిల్‌మెంట్',
      settlementPending: 'మీ బ్యాంక్ ఖాతాలో జమ చేయబడుతుంది',
      settlementDone: 'మీ బ్యాంక్ ఖాతాలో జమ చేశాం',
      viewSettlement: 'సెటిల్‌మెంట్ చూడు',
      refundedLabel: 'ఇప్పటివరకు తిరిగి ఇచ్చింది',
      actions: 'చర్యలు',
      refund: 'రీఫండ్',
      shareReceipt: 'రసీదు షేర్ చేయి',
      raiseDispute: 'ఫిర్యాదు చేయి',
      reportIssue: 'సమస్య తెలియజేయి',
      notRefundable: 'ఈ చెల్లింపుకు రీఫండ్ చేయలేం',
      receiptMessage: '{{time}} కి {{amount}} వచ్చింది. లావాదేవీ ID: {{id}}.',
    },
  },

  refund: {
    title: 'రీఫండ్ చేయి',
    originalLabel: 'అసలు చెల్లింపు',
    refundableLabel: 'రీఫండ్‌కు అందుబాటులో',
    alreadyRefunded: '{{amount}} ఇప్పటికే తిరిగి ఇచ్చాం',
    typeFull: 'పూర్తి రీఫండ్',
    typePartial: 'పాక్షిక రీఫండ్',
    fullBody: 'మొత్తం సొమ్ము తిరిగి ఇవ్వండి',
    partialBody: 'కొంత భాగం తిరిగి ఇవ్వండి',
    amountLabel: 'రీఫండ్ మొత్తం',
    reasonLabel: 'కారణం',
    reasonPlaceholder: 'రీఫండ్ ఎందుకు? (ఐచ్ఛికం)',
    exceedsRefundable: '{{max}} కంటే ఎక్కువ రీఫండ్ చేయలేం',
    tooLow: '{{min}} కంటే ఎక్కువ మొత్తం నమోదు చేయండి',
    confirmCta: '{{amount}} రీఫండ్ చేయి',
    reauthReason: '{{amount}} రీఫండ్‌ను నిర్ధారించండి',
    processingTitle: 'రీఫండ్ జరుగుతోంది…',
    processingBody: 'యాప్‌ను తెరిచి ఉంచండి.',
    successTitle: 'రీఫండ్ మొదలైంది',
    successBody: '{{amount}} కస్టమర్‌కు తిరిగి పంపుతున్నాం. సాధారణంగా 3-5 పని దినాలు పడుతుంది.',
    successDone: 'పూర్తయింది',
    offlineTitle: 'ఇంటర్నెట్ లేదు',
    offlineBody: 'రీఫండ్‌కు ఇంటర్నెట్ కనెక్షన్ అవసరం.',
    notEligibleTitle: 'రీఫండ్ చేయలేం',
    notEligibleBody: 'విజయవంతమైన చెల్లింపులకు మాత్రమే రీఫండ్ చేయగలం.',
  },

  appLock: {
    title: 'మీరేనా అని నిర్ధారించండి',
    biometricPrompt: 'నిర్ధారించడానికి వేలిముద్ర లేదా ముఖం వాడండి',
    biometricFailed: 'ధృవీకరించలేకపోయాం. దానికి బదులు PIN నమోదు చేయండి.',
    usePin: 'PIN వాడు',
    pinIncorrect: 'తప్పు PIN. {{count}} ప్రయత్నాలు మిగిలాయి.',
    lockedOut: 'చాలా తప్పు ప్రయత్నాలు. యాప్ మూసి తిరిగి తెరవండి.',
    setupTitle: 'యాప్ PIN సృష్టించండి',
    setupBody: 'రీఫండ్ వంటి కీలక చర్యలను ఆమోదించడానికి {{min}} అంకెల PIN ఎంచుకోండి.',
    confirmTitle: 'PIN మళ్లీ నమోదు చేయండి',
    pinMismatch: 'PIN సరిపోలలేదు. మళ్లీ ప్రయత్నించండి.',
    pinTooShort: 'PIN కనీసం {{min}} అంకెలు ఉండాలి',
  },

  reports: {
    title: 'నివేదికలు',
    chartTitle: 'అమ్మకాల ధోరణి',
    chartHint: 'ఆ రోజు మొత్తం చూడడానికి బార్‌ను నొక్కండి',
    chartA11y: 'ఎంచుకున్న కాలానికి అమ్మకాల చార్ట్',
    statsTitle: 'సారాంశం',
    totalSales: 'మొత్తం అమ్మకాలు',
    txnCount: 'చెల్లింపులు',
    avgTicket: 'సగటు అమ్మకం',
    topMode: 'ఎక్కువగా వాడినది',
    bestDay: 'ఉత్తమ రోజు',
    tradingDays: 'అమ్మకాలు జరిగిన రోజులు',
    avgPerTradingDay: 'అమ్మకాలు జరిగిన రోజు సగటు',
    emptyTitle: 'ఈ కాలంలో అమ్మకాలు లేవు',
    emptyBody: 'వేరే తేదీ ఎంచుకోండి, లేదా చెల్లింపులు స్వీకరించడం మొదలుపెట్టండి.',
    emptyCta: 'డబ్బు తీసుకో',
    errorTitle: 'నివేదిక లోడ్ కాలేదు',
    export: {
      cta: 'నివేదిక ఎక్స్‌పోర్ట్ చేయి',
      preparing: 'ఎక్స్‌పోర్ట్ సిద్ధమవుతోంది…',
      failed: 'ఎక్స్‌పోర్ట్ సృష్టించలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
      fileName: 'అమ్మకాల నివేదిక',
      formatNote: 'CSV ఫైల్‌గా సేవ్ అవుతుంది, ఇది Excel మరియు Google Sheets లో తెరుచుకుంటుంది.',
      colDate: 'తేదీ',
      colSales: 'అమ్మకాలు (INR)',
      colCount: 'చెల్లింపులు',
      totalsLabel: 'మొత్తం',
      periodLabel: 'కాలం',
      generatedLabel: 'తయారు చేసిన సమయం',
    },
    gst: {
      title: 'GST',
      summaryCta: 'GST సారాంశం ఎక్స్‌పోర్ట్ చేయి',
      summaryBody: 'మీ GSTIN తో కాలపు అమ్మకాల సారాంశం, మీ అకౌంటెంట్ GST ఫైలింగ్ కోసం.',
      noGstinTitle: 'GSTIN నమోదు కాలేదు',
      noGstinBody: 'GST ఎక్స్‌పోర్ట్‌లో చేర్చడానికి మీ ప్రొఫైల్‌లో GSTIN జోడించండి.',
      invoiceNote: 'ప్రతి చెల్లింపుకు పన్ను ఇన్‌వాయిస్‌కు కస్టమర్ వివరాలు మరియు వస్తువుల జాబితా అవసరం, కాబట్టి అవి ఇన్‌వాయిసింగ్ ఫీచర్ నుంచి జారీ అవుతాయి, చెల్లింపు రికార్డుల నుంచి కాదు.',
      gstinLabel: 'GSTIN',
      fileName: 'GST సారాంశం',
      colField: 'వివరం',
      colValue: 'విలువ',
      rowBusiness: 'వ్యాపార పేరు',
      rowGstin: 'GSTIN',
      rowPeriodFrom: 'కాలం నుంచి',
      rowPeriodTo: 'కాలం వరకు',
      rowTotalSales: 'మొత్తం అమ్మకాలు (INR)',
      rowTxnCount: 'చెల్లింపుల సంఖ్య',
      rowNote: 'గమనిక',
      noteValue: 'అందిన చెల్లింపుల సారాంశం. ఇది పన్ను ఇన్‌వాయిస్ కాదు.',
    },
  },

  more: {
    title: 'మరిన్ని',
    reports: 'నివేదికలు',
    reportsBody: 'అమ్మకాల ధోరణులు మరియు ఎక్స్‌పోర్ట్',
    profile: 'వ్యాపార ప్రొఫైల్',
    profileBody: 'మీ వివరాలు, బ్యాంక్ ఖాతా మరియు KYC',
    staff: 'సిబ్బంది',
    staffBody: 'చెల్లింపులు స్వీకరించగల వ్యక్తులను జోడించండి',
    support: 'సహాయం మరియు మద్దతు',
    supportBody: 'ప్రశ్నలు, ఫిర్యాదు నమోదు, మమ్మల్ని సంప్రదించండి',
    settings: 'సెట్టింగ్‌లు',
    settingsBody: 'భాష, ఆడియో, నోటిఫికేషన్లు, యాప్ లాక్',
    comingSoonBadge: 'త్వరలో',
  },

  dateRange: {
    label: 'తేదీ పరిధి',
    all: 'అన్ని సమయాలు',
    today: 'ఈరోజు',
    yesterday: 'నిన్న',
    last7: 'గత 7 రోజులు',
    last30: 'గత 30 రోజులు',
    thisMonth: 'ఈ నెల',
    custom: 'మీ పరిధి',
    from: 'నుంచి',
    to: 'వరకు',
  },

  settlements: {
    title: 'సెటిల్‌మెంట్లు',
    status: {
      pending: 'పెండింగ్',
      processing: 'జరుగుతోంది',
      settled: 'జమ అయింది',
      failed: 'విఫలం',
    },
    tabs: {
      pending: 'పెండింగ్',
      settled: 'జమ అయింది',
    },
    batchLabel: '{{count}} చెల్లింపు బ్యాచ్',
    batchLabel_plural: '{{count}} చెల్లింపుల బ్యాచ్',
    utrLabel: 'UTR',
    expectedLabel: 'మీ బ్యాంక్ ఖాతాలో రావాల్సినది',
    creditedLabel: 'మీ బ్యాంక్ ఖాతాలో జమ అయింది',
    emptyPendingTitle: 'పెండింగ్‌లో ఏమీ లేదు',
    emptyPendingBody: 'ఈరోజు వచ్చిన చెల్లింపులు రేపు మీ బ్యాంక్ ఖాతాకు పంపబడతాయి.',
    emptySettledTitle: 'ఇంకా సెటిల్‌మెంట్లు లేవు',
    emptySettledBody: 'డబ్బు బ్యాంక్ ఖాతాకు చేరిన తర్వాత UTR తో ఇక్కడ కనిపిస్తుంది.',
    errorTitle: 'సెటిల్‌మెంట్లు లోడ్ కాలేదు',
    t1Note: 'తదుపరి పని దినంలో డబ్బు మీ బ్యాంక్ ఖాతాకు చేరుతుంది.',
    detail: {
      title: 'సెటిల్‌మెంట్ వివరాలు',
      breakdownTitle: 'వివరణ',
      grossLabel: 'మొత్తం వచ్చింది',
      feeLabel: 'ఫీజులు',
      netLabel: 'బ్యాంకులో జమ',
      bankTitle: 'బ్యాంక్ ఖాతా',
      accountLabel: 'ఖాతా',
      ifscLabel: 'IFSC',
      utrLabel: 'UTR / రిఫరెన్స్',
      createdLabel: 'బ్యాచ్ సృష్టించబడింది',
      settledLabel: 'జమ అయిన తేదీ',
      txnTitle: 'ఈ బ్యాచ్‌లోని చెల్లింపులు',
      txnCount: '{{count}} చెల్లింపు',
      txnCount_plural: '{{count}} చెల్లింపులు',
      reconcileNote: 'కింది చెల్లింపులన్నీ కలిపి మొత్తం అవుతుంది.',
      noTxnTitle: 'చెల్లింపుల జాబితా లేదు',
      noTxnBody: 'ఈ బ్యాచ్‌లోని విడి చెల్లింపులు అందుబాటులో లేవు.',
    },
    statement: {
      download: 'స్టేట్‌మెంట్ డౌన్‌లోడ్ చేయి',
      preparing: 'స్టేట్‌మెంట్ సిద్ధమవుతోంది…',
      failed: 'స్టేట్‌మెంట్ సృష్టించలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
      fileName: 'సెటిల్‌మెంట్ స్టేట్‌మెంట్',
      colDate: 'తేదీ',
      colTime: 'సమయం',
      colTxnId: 'లావాదేవీ ID',
      colUtr: 'UTR',
      colMode: 'విధానం',
      colStatus: 'స్థితి',
      colGross: 'మొత్తం (INR)',
      colFee: 'ఫీజు (INR)',
      colNet: 'నికర (INR)',
      totalsLabel: 'మొత్తం',
      formatNote: 'CSV ఫైల్‌గా సేవ్ అవుతుంది, ఇది Excel మరియు Google Sheets లో తెరుచుకుంటుంది.',
    },
    instant: {
      cta: 'ఇప్పుడే సెటిల్ చేయి',
      sheetTitle: 'తక్షణమే సెటిల్ చేయి',
      sheetBody: 'రేపు వరకు ఆగకుండా ఈ డబ్బును కొన్ని నిమిషాల్లో మీ బ్యాంక్ ఖాతాలో పొందండి.',
      netLabel: 'సెటిల్‌మెంట్ మొత్తం',
      feeLabel: 'తక్షణ సెటిల్‌మెంట్ ఫీజు ({{percent}}%)',
      gstLabel: 'ఫీజుపై GST',
      payoutLabel: 'మీకు అందుతుంది',
      confirmCta: '{{amount}} ఇప్పుడే సెటిల్ చేయి',
      processing: 'సెటిల్ అవుతోంది…',
      successTitle: 'డబ్బు పంపబడుతోంది',
      successBody: '{{amount}} మీ బ్యాంక్ ఖాతాలో జమ అవుతోంది. సాధారణంగా కొన్ని నిమిషాల్లో చేరుతుంది.',
      ineligible: {
        already_settled: 'ఈ బ్యాచ్ ఇప్పటికే సెటిల్ అయింది.',
        below_minimum: 'తక్షణ సెటిల్‌మెంట్‌కు కనీసం {{min}} కావాలి.',
        failed_batch: 'ఈ బ్యాచ్ విఫలమైంది, తక్షణమే సెటిల్ చేయలేం.',
      },
      offlineBody: 'తక్షణ సెటిల్‌మెంట్‌కు ఇంటర్నెట్ కనెక్షన్ అవసరం.',
    },
  },

  collect: {
    title: 'డబ్బు తీసుకో',
    subtitle: 'మీరు ఎలా డబ్బు తీసుకోవాలనుకుంటున్నారు?',
    modes: {
      staticQr: 'నా QR కోడ్',
      staticQrBody: 'ఏ మొత్తానికైనా ఒకే కోడ్. చూపించండి లేదా ప్రింట్ చేయండి.',
      dynamicQr: 'మొత్తం నమోదు చేయి',
      dynamicQrBody: 'నిర్దిష్ట మొత్తానికి QR సృష్టించండి.',
      paymentLink: 'చెల్లింపు లింక్',
      paymentLinkBody: 'WhatsApp లేదా SMS లో లింక్ పంపండి.',
    },
    staticQr: {
      title: 'నా QR కోడ్',
      instruction: 'స్కాన్ చేసి ఏ మొత్తమైనా చెల్లించమని కస్టమర్‌ను అడగండి.',
      vpaLabel: 'UPI ID',
      noQrTitle: 'QR ఇంకా సిద్ధం కాలేదు',
      noQrBody: 'QR కోడ్ పొందడానికి బ్యాంక్ ధృవీకరణ పూర్తి చేయండి.',
      noQrCta: 'ధృవీకరణ పూర్తి చేయి',
      offlineUsable: 'మీ QR ఇంటర్నెట్ లేకుండా కూడా పనిచేస్తుంది.',
    },
    amount: {
      title: 'మొత్తం నమోదు చేయి',
      generateQr: 'QR సృష్టించు',
      createLink: 'లింక్ సృష్టించు',
      noteLabel: 'గమనిక',
      notePlaceholder: 'ఎందుకు? (ఐచ్ఛికం)',
      tooLow: '{{min}} కంటే ఎక్కువ మొత్తం నమోదు చేయండి',
      limitExceeded: 'ధృవీకరణ పూర్తయ్యే వరకు రోజువారీ పరిమితి {{limit}}',
      upiCap: 'ఒక UPI చెల్లింపుకు గరిష్ఠం {{max}}',
    },
    dynamicQr: {
      title: 'చెల్లించడానికి స్కాన్ చేయండి',
      waiting: 'చెల్లింపు కోసం వేచి ఉంది…',
      waitingBody: 'ఈ కోడ్‌ను స్కాన్ చేయమని కస్టమర్‌ను అడగండి.',
      expiresIn: '{{time}} లో గడువు ముగుస్తుంది',
      expiredTitle: 'QR గడువు ముగిసింది',
      expiredBody: 'ఈ కోడ్ ఇకపై చెల్లదు. కొత్తది సృష్టించండి.',
      newQr: 'కొత్త QR సృష్టించు',
      cancel: 'రద్దు',
      checkingSlowly: 'ఇంకా తనిఖీ చేస్తోంది. మీ కనెక్షన్ నెమ్మదిగా ఉంది.',
      failedTitle: 'చెల్లింపు విఫలమైంది',
      failedBody: 'కస్టమర్ చెల్లింపు జరగలేదు. మళ్లీ ప్రయత్నించమని అడగండి.',
      offlineTitle: 'ఇంటర్నెట్ లేదు',
      offlineBody: 'నిర్దిష్ట మొత్తం QR కి ఇంటర్నెట్ అవసరం. దానికి బదులు మీ QR కోడ్ వాడండి.',
      useStaticQr: 'నా QR కోడ్ వాడు',
    },
    link: {
      title: 'చెల్లింపు లింక్',
      createdTitle: 'లింక్ సిద్ధం',
      createdBody: 'ఇది మీ కస్టమర్‌కు పంపండి. 24 గంటల్లో గడువు ముగుస్తుంది.',
      copy: 'లింక్ కాపీ చేయి',
      copied: 'లింక్ కాపీ అయింది',
      shareVia: 'లింక్ షేర్ చేయి',
      newLink: 'మరొకటి సృష్టించు',
      shareMessage: 'ఈ లింక్ ద్వారా {{amount}} చెల్లించండి: {{url}}',
    },
    success: {
      title: 'చెల్లింపు వచ్చింది!',
      amountLabel: 'వచ్చిన మొత్తం',
      txnIdLabel: 'లావాదేవీ ID',
      timeLabel: 'సమయం',
      payerLabel: 'చెల్లించినవారు',
      utrLabel: 'UPI రిఫరెన్స్',
      shareReceipt: 'రసీదు షేర్ చేయి',
      newPayment: 'కొత్త చెల్లింపు',
      done: 'పూర్తయింది',
      receiptMessage: 'చెల్లింపు వచ్చింది: {{time}} కి {{amount}}. లావాదేవీ ID: {{id}}.',
    },
    audio: {
      received: '{{amount}} రూపాయలు వచ్చాయి',
      mutedHint: 'ఆడియో నిర్ధారణ ఆఫ్‌లో ఉంది. సెట్టింగ్స్‌లో ఆన్ చేయండి.',
    },
  },
};

export default te;
