import type { TranslationBundle } from './en';

/** Telugu (తెలుగు) */
export const te: TranslationBundle = {
  common: {
    appName: 'MerchantOne',
    ok: 'సరే',
    cancel: 'రద్దు',
    continue: 'కొనసాగించు',
    back: 'వెనుక',
    next: 'తదుపరి',
    skip: 'దాటవేయి',
    done: 'పూర్తయింది',
    retry: 'మళ్లీ ప్రయత్నించండి',
    save: 'సేవ్ చేయి',
    close: 'మూసివేయి',
    share: 'షేర్ చేయి',
    download: 'డౌన్‌లోడ్',
    search: 'వెతుకు',
    viewAll: 'అన్నీ చూడు',
    today: 'ఈరోజు',
    yesterday: 'నిన్న',
    loading: 'లోడ్ అవుతోంది…',
    yes: 'అవును',
    no: 'కాదు',
    optional: 'ఐచ్ఛికం',
    verified: 'ధృవీకరించబడింది',
    verifying: 'ధృవీకరిస్తోంది…',
    edit: 'మార్చు',
    remove: 'తీసివేయి',
    confirm: 'నిర్ధారించు',
    comingSoon: 'త్వరలో',
    comingSoonBody: 'ఈ విభాగం తయారవుతోంది.',
    months: {
      jan: 'జన',
      feb: 'ఫిబ్ర',
      mar: 'మార్చి',
      apr: 'ఏప్రి',
      may: 'మే',
      jun: 'జూన్',
      jul: 'జూలై',
      aug: 'ఆగ',
      sep: 'సెప్',
      oct: 'అక్టో',
      nov: 'నవం',
      dec: 'డిసం',
    },
  },

  a11y: {
    back: 'వెనక్కి వెళ్లు',
    close: 'మూసివేయి',
    notifications: 'నోటిఫికేషన్లు',
    loading: 'కంటెంట్ లోడ్ అవుతోంది',
    amount: 'మొత్తం {{amount}}',
    step: 'దశ {{current}} / {{total}}',
  },

  tabs: {
    home: 'హోమ్',
    collect: 'డబ్బు తీసుకో',
    transactions: 'లావాదేవీలు',
    settlements: 'సెటిల్‌మెంట్లు',
    more: 'మరిన్ని',
  },

  network: {
    offlineTitle: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు',
    offlineBanner: 'ఇంటర్నెట్ లేదు. సేవ్ చేసిన డేటా చూపిస్తోంది.',
    offlineActionDisabled: 'దీనికి ఇంటర్నెట్ కనెక్షన్ అవసరం.',
    backOnline: 'ఇంటర్నెట్ తిరిగి వచ్చింది',
  },

  errors: {
    title: 'ఏదో తప్పు జరిగింది',
    network_error: 'సర్వర్‌ను చేరుకోలేకపోతున్నాము. కనెక్షన్ చూసి మళ్లీ ప్రయత్నించండి.',
    timeout: 'చాలా సమయం పడుతోంది. మళ్లీ ప్రయత్నించండి.',
    offline: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు. ఇంటర్నెట్‌కు కనెక్ట్ అయి మళ్లీ ప్రయత్నించండి.',
    unauthorized: 'మీ సెషన్ ముగిసింది. దయచేసి మళ్లీ లాగిన్ అవ్వండి.',
    forbidden: 'ఇది చేయడానికి మీకు అనుమతి లేదు.',
    not_found: 'మీరు వెతుకుతున్నది కనబడలేదు.',
    validation_error: 'మీరు నమోదు చేసిన వివరాలను తనిఖీ చేయండి.',
    rate_limited: 'చాలా ప్రయత్నాలు. కొద్దిసేపు ఆగి ప్రయత్నించండి.',
    invalid_otp: 'ఈ OTP తప్పు. తనిఖీ చేసి మళ్లీ నమోదు చేయండి.',
    otp_expired: 'ఈ OTP గడువు ముగిసింది. కొత్తది అడగండి.',
    invalid_mobile: 'సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి.',
    kyc_incomplete: 'ఈ ఫీచర్ కోసం మీ KYC పూర్తి చేయండి.',
    kyc_rejected: 'మీ KYC ఆమోదించబడలేదు. తనిఖీ చేసి మళ్లీ సమర్పించండి.',
    bank_verification_failed: 'ఈ బ్యాంక్ ఖాతాను ధృవీకరించలేకపోయాము. వివరాలు తనిఖీ చేయండి.',
    pan_verification_failed: 'ఈ PAN ధృవీకరించలేకపోయాము. నంబర్ తనిఖీ చేయండి.',
    already_refunded: 'ఈ లావాదేవీకి ఇప్పటికే రీఫండ్ జరిగింది.',
    refund_limit_exceeded: 'రీఫండ్ మొత్తం అందుబాటులో ఉన్న మొత్తానికి మించి ఉంది.',
    payment_expired: 'ఈ చెల్లింపు అభ్యర్థన గడువు ముగిసింది. కొత్తది సృష్టించండి.',
    server_error: 'మా సర్వర్లలో సమస్య. కొద్దిసేపటి తర్వాత ప్రయత్నించండి.',
    unknown: 'ఏదో తప్పు జరిగింది. మళ్లీ ప్రయత్నించండి.',
  },

  auth: {
    splash: {
      tagline: 'చెల్లింపులు ఇప్పుడు సులభం',
    },
    login: {
      title: 'స్వాగతం',
      subtitle: 'మీ వ్యాపారాన్ని నిర్వహించడానికి మొబైల్ నంబర్‌తో లాగిన్ అవ్వండి',
      mobileLabel: 'మొబైల్ నంబర్',
      mobilePlaceholder: '10 అంకెల మొబైల్ నంబర్',
      mobileRequired: 'మీ మొబైల్ నంబర్ నమోదు చేయండి',
      mobileInvalid: 'సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి',
      consent: 'నేను సేవా నిబంధనలు మరియు గోప్యతా విధానాన్ని అంగీకరిస్తున్నాను',
      consentRequired: 'కొనసాగించడానికి నిబంధనలను అంగీకరించండి',
      getOtp: 'OTP పొందు',
      secureNote: 'మీ నంబర్ ధృవీకరించడానికి 6 అంకెల కోడ్ పంపుతాము.',
    },
    otp: {
      title: 'మీ నంబర్ ధృవీకరించండి',
      subtitle: '{{mobile}} కు పంపిన 6 అంకెల కోడ్ నమోదు చేయండి',
      otpRequired: '6 అంకెల కోడ్ నమోదు చేయండి',
      otpInvalid: 'కోడ్ 6 అంకెలు ఉండాలి',
      verify: 'ధృవీకరించు',
      resend: 'కోడ్ మళ్లీ పంపు',
      resendIn: '{{seconds}} సెకన్లలో మళ్లీ పంపు',
      changeNumber: 'నంబర్ మార్చు',
      autoReadHint: 'అనుమతి ఉంటే కోడ్‌ను మేమే చదువుతాము.',
      hintDev: 'డెమో మోడ్: {{otp}} వాడండి',
    },
  },

  kyc: {
    title: 'వ్యాపార ధృవీకరణ',
    stepOf: 'దశ {{current}} / {{total}}',
    saveAndExit: 'సేవ్ చేసి బయటకు',
    resumeTitle: 'ధృవీకరణ కొనసాగించు',
    resumeBody: 'మీరు దశ {{step}} వద్ద ఆగారు. అక్కడి నుంచి కొనసాగించండి.',
    progress: {
      business: 'వ్యాపారం',
      identity: 'గుర్తింపు',
      bank: 'బ్యాంక్',
      aadhaar: 'ఆధార్',
    },
    business: {
      title: 'మీ వ్యాపారం గురించి చెప్పండి',
      subtitle: 'కస్టమర్లు స్కాన్ చేసే QR పై ఇది కనిపిస్తుంది.',
      name: 'వ్యాపార పేరు',
      namePlaceholder: 'ఉదా. శర్మ జనరల్ స్టోర్',
      nameRequired: 'మీ వ్యాపార పేరు నమోదు చేయండి',
      nameTooShort: 'పేరు కనీసం 3 అక్షరాలు ఉండాలి',
      category: 'వ్యాపార విభాగం',
      categoryPlaceholder: 'ఒక విభాగాన్ని ఎంచుకోండి',
      categoryRequired: 'మీ వ్యాపార విభాగాన్ని ఎంచుకోండి',
      categorySheetTitle: 'వ్యాపార విభాగాన్ని ఎంచుకోండి',
      addressLine1: 'దుకాణం / భవనం చిరునామా',
      addressPlaceholder: 'దుకాణం నంబర్, వీధి, ప్రాంతం',
      addressRequired: 'మీ వ్యాపార చిరునామా నమోదు చేయండి',
      pincode: 'పిన్ కోడ్',
      pincodePlaceholder: '6 అంకెల పిన్ కోడ్',
      pincodeRequired: 'మీ పిన్ కోడ్ నమోదు చేయండి',
      pincodeInvalid: 'సరైన 6 అంకెల పిన్ కోడ్ నమోదు చేయండి',
      city: 'నగరం',
      cityRequired: 'మీ నగరం నమోదు చేయండి',
      state: 'రాష్ట్రం',
      stateRequired: 'మీ రాష్ట్రం నమోదు చేయండి',
      pincodeLookup: 'మీ ప్రాంతాన్ని వెతుకుతోంది…',
    },
    identity: {
      title: 'గుర్తింపు వివరాలు',
      subtitle: 'చెల్లింపులు స్వీకరించడానికి RBI తప్పనిసరి చేసింది.',
      pan: 'PAN నంబర్',
      panPlaceholder: 'ABCDE1234F',
      panRequired: 'మీ PAN నంబర్ నమోదు చేయండి',
      panInvalid: 'సరైన PAN నమోదు చేయండి (ఉదా. ABCDE1234F)',
      panHelp: 'మీ PAN కార్డుపై ఉన్నట్లుగా.',
      gstin: 'GSTIN',
      gstinPlaceholder: '22ABCDE1234F1Z5',
      gstinInvalid: 'సరైన 15 అక్షరాల GSTIN నమోదు చేయండి',
      gstinHelp: 'GST బిల్లులు కావాలంటే ఇది జోడించండి.',
    },
    bank: {
      title: 'మీ డబ్బు ఎక్కడ జమ చేయాలి?',
      subtitle: 'మీ వసూళ్లు ఇక్కడ జమ అవుతాయి, సాధారణంగా మరుసటి రోజు.',
      accountNumber: 'ఖాతా నంబర్',
      accountNumberPlaceholder: 'బ్యాంక్ ఖాతా నంబర్',
      accountNumberRequired: 'మీ ఖాతా నంబర్ నమోదు చేయండి',
      accountNumberInvalid: 'ఖాతా నంబర్ 9 నుంచి 18 అంకెలు ఉండాలి',
      confirmAccountNumber: 'ఖాతా నంబర్ మళ్లీ నమోదు చేయండి',
      accountMismatch: 'ఖాతా నంబర్లు సరిపోలలేదు',
      ifsc: 'IFSC కోడ్',
      ifscPlaceholder: 'HDFC0001234',
      ifscRequired: 'IFSC కోడ్ నమోదు చేయండి',
      ifscInvalid: 'సరైన IFSC నమోదు చేయండి (ఉదా. HDFC0001234)',
      holderName: 'ఖాతాదారు పేరు',
      holderNamePlaceholder: 'బ్యాంక్ రికార్డుల ప్రకారం పేరు',
      holderNameRequired: 'ఖాతాదారు పేరు నమోదు చేయండి',
      verifyCta: 'ఖాతా ధృవీకరించు',
      verifying: 'మీ ఖాతా ధృవీకరిస్తోంది…',
      verifyingBody: 'ఈ ఖాతా మీదేనని నిర్ధారించడానికి ₹1 పంపుతున్నాము.',
      verifiedTitle: 'ఖాతా ధృవీకరించబడింది',
      verifiedNameAtBank: 'బ్యాంకులో పేరు: {{name}}',
      unlockNote: 'ఈ దశ తర్వాత పరిమితులతో చెల్లింపులు స్వీకరించడం మొదలుపెట్టవచ్చు, తనిఖీలు పూర్తయ్యే వరకు.',
    },
    aadhaar: {
      title: 'ఆధార్ ధృవీకరణ',
      subtitle: 'అన్ని ఫీచర్లు తెరవడానికి చివరి దశ.',
      numberLabel: 'ఆధార్ నంబర్',
      numberPlaceholder: '12 అంకెల ఆధార్ నంబర్',
      numberRequired: 'మీ ఆధార్ నంబర్ నమోదు చేయండి',
      numberInvalid: 'ఆధార్ నంబర్ 12 అంకెలు ఉండాలి',
      consent: 'ఆధార్ eKYC ద్వారా నా గుర్తింపును ధృవీకరించడానికి నేను సమ్మతిస్తున్నాను. నా ఆధార్ వివరాలు ఈ ధృవీకరణ కోసమే వాడతారని నేను అర్థం చేసుకున్నాను.',
      consentRequired: 'కొనసాగడానికి మీ సమ్మతి అవసరం',
      sendOtp: 'ఆధార్ OTP పంపు',
      otpLabel: 'ఆధార్ OTP',
      otpSentTo: 'ఆధార్‌తో అనుసంధానమైన మొబైల్‌కు పంపిన కోడ్ నమోదు చేయండి.',
      otpRequired: '6 అంకెల ఆధార్ OTP నమోదు చేయండి',
      verifyCta: 'ఆధార్ ధృవీకరించు',
      verifiedTitle: 'ఆధార్ ధృవీకరించబడింది',
      skipForNow: 'తర్వాత చేయి',
      privacyNote: 'మీ పూర్తి ఆధార్ నంబర్‌ను మేము ఎప్పుడూ నిల్వ చేయము.',
    },
    done: {
      title: 'అంతా సిద్ధం!',
      subtitle: 'మీ వివరాలు సమర్పించబడ్డాయి. ఇప్పుడే చెల్లింపులు స్వీకరించవచ్చు.',
      pendingTitle: 'ధృవీకరణ జరుగుతోంది',
      pendingSubtitle: 'మీ వివరాలను పరిశీలిస్తున్నాము. సాధారణంగా కొన్ని గంటలు పడుతుంది.',
      generateQr: 'నా QR తయారు చేయి',
      goHome: 'డాష్‌బోర్డుకు వెళ్లు',
      vpaLabel: 'మీ UPI ID',
      limitsNote: 'ధృవీకరణ పూర్తయ్యే వరకు రోజుకు {{limit}} వరకు తీసుకోవచ్చు.',
    },
    status: {
      not_started: 'KYC పెండింగ్',
      in_progress: 'KYC అసంపూర్ణం',
      pending_review: 'పరిశీలనలో',
      approved: 'ధృవీకరించబడింది',
      rejected: 'చర్య అవసరం',
    },
    rejected: {
      title: 'మరోసారి చూడాలి',
      reasonLabel: 'కారణం',
      retryCta: 'వివరాలు నవీకరించు',
    },
    submitCta: 'ధృవీకరణకు సమర్పించు',
    mcc: {
      grocery: 'కిరాణా / జనరల్ స్టోర్',
      restaurant: 'రెస్టారెంట్ / కేఫ్',
      apparel: 'దుస్తులు',
      electronics: 'ఎలక్ట్రానిక్స్ & మొబైల్స్',
      pharmacy: 'మెడికల్ / ఫార్మసీ',
      salon: 'సెలూన్ & బ్యూటీ',
      hardware: 'హార్డ్‌వేర్ & నిర్మాణ సామగ్రి',
      services: 'వృత్తిపరమైన సేవలు',
      education: 'విద్య & కోచింగ్',
      transport: 'రవాణా & ప్రయాణం',
      online: 'ఆన్‌లైన్ / D2C విక్రేత',
      other: 'ఇతరం',
    },
  },

  home: {
    greeting: 'నమస్తే',
    summary: {
      title: 'ఈరోజు వసూళ్లు',
      collected: 'ఈరోజు వచ్చింది',
      txnCount: '{{count}} చెల్లింపు',
      txnCount_plural: '{{count}} చెల్లింపులు',
      pendingSettlement: 'సెటిల్‌మెంట్ పెండింగ్',
      settlementHint: 'మీ బ్యాంక్ ఖాతాలో జమ అవుతుంది',
    },
    collectCta: 'డబ్బు తీసుకో',
    quickActions: {
      title: 'త్వరిత చర్యలు',
      myQr: 'నా QR',
      paymentLink: 'చెల్లింపు లింక్',
      reports: 'నివేదికలు',
      refund: 'రీఫండ్',
    },
    recent: {
      title: 'ఇటీవలి చెల్లింపులు',
      emptyTitle: 'ఇంకా చెల్లింపులు లేవు',
      emptyBody: 'మొదటి చెల్లింపు పొందడానికి కస్టమర్‌కు మీ QR చూపించండి.',
      emptyCta: 'నా QR చూపించు',
    },
    kycNudge: {
      title: 'ధృవీకరణ పూర్తి చేయండి',
      body: 'పరిమితులు తొలగించడానికి మీ వివరాలు పూర్తి చేయండి.',
      cta: 'కొనసాగించు',
    },
    error: {
      title: 'డాష్‌బోర్డ్ లోడ్ కాలేదు',
      body: 'కనెక్షన్ చూసి మళ్లీ ప్రయత్నించండి.',
    },
  },

  notifications: {
    title: 'నోటిఫికేషన్లు',
    emptyTitle: 'నోటిఫికేషన్లు లేవు',
    emptyBody: 'చెల్లింపు మరియు సెటిల్‌మెంట్ అప్‌డేట్లు ఇక్కడ కనిపిస్తాయి.',
  },

  transactions: {
    title: 'లావాదేవీలు',
    status: {
      success: 'వచ్చింది',
      pending: 'పెండింగ్',
      failed: 'విఫలం',
      refunded: 'తిరిగి ఇచ్చాం',
      partially_refunded: 'పాక్షిక రీఫండ్',
    },
    mode: {
      upi_qr: 'UPI QR',
      upi_intent: 'UPI యాప్',
      payment_link: 'చెల్లింపు లింక్',
      card: 'కార్డ్',
      netbanking: 'నెట్ బ్యాంకింగ్',
      wallet: 'వాలెట్',
    },
  },

  settlements: {
    title: 'సెటిల్‌మెంట్లు',
    status: {
      pending: 'పెండింగ్',
      processing: 'జరుగుతోంది',
      settled: 'జమ అయింది',
      failed: 'విఫలం',
    },
  },
};

export default te;
